### ISSUE TITLE
"Edit in Github" feature for the published docs

### ISSUE THREAD

**Issue by hirenoble** [stoplightio/studio#100]
**User story.**
As a user, I should be able to suggest changes by clicking on "Edit in Github" on the published docs page.

**Is your feature request related to a problem?**
No
**Describe the solution you'd like**
I want the user of my published docs to be able to suggest an edit in github repo.

**Comment by philsturgeon** [comment]
Thanks for htis feedback @hirenoble and sorry we didn't respond sooner. We've put the feedback in our productboard and we'll be prioritizing it against other suggestions!
