### ISSUE TITLE
Web App cuts off bottom meta bar on small screens 

### ISSUE THREAD

**Issue by rowa97** [stoplightio/studio#105]
**Describe the bug**
Small screens don't meet the minimum height requirements so it doesn't display the git functions on the bottom bar 

**To Reproduce**

1. Open the web app on a small screen 
2. Try to view the git bar 

**Expected behavior**
Git bar is displayed no matter what screen size 

**Environment (remove any that are not applicable):**
 - Studio version: [1.1]
 - OS: [MacOS]
 - Browser: [Chrome v76]

**Comment by rowa97** [comment]
![Screen Shot 2019-09-11 at 1.46.50 PM.png](https://images.zenhubusercontent.com/5d793db9fb288f0001cebad0/6806c6fa-f198-4131-809b-d9d51caae6ae)

**Comment by rowa97** [comment]
on larger screens, if you pass a certain width (around 1400px) the bottom bar disappears as well

**Comment by mallachari** [comment]
I was able to reproduce it in a case which seems similar to what @rowa97 mentioned. When the window is shrinked meta panel disappears. I couldn't spot it for small windows (which are not resized) though.
Could you make a short gif showing how it occurs?

**Comment by rowa97** [comment]
it looks like the small window issue occurs exclusively when looking at docs, it removes the ability to see the "assets/images" section and anything else down there 
![Sep-17-2019 11-07-21](https://user-images.githubusercontent.com/29557510/65059287-5bebf900-d93b-11e9-852c-5ad893361c52.gif)
