### ISSUE TITLE
Be able to resize editor views/windows

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#107]
**User story.**
As a user, I would like to resize the editor sidebar.

**Is your feature request related to a problem?**
Using Studio on smaller screens is sometimes difficult do to the views and sidebar being static with minimum widths.

**Describe the solution you'd like**

The editor sidebar should allow for resizing via dragging the separators.

- [ ] The sidebar should be resizable horizontally, as well as vertically for the divider between top and bottom trees. 
- [ ] The resize state should be cached / remembered between reloads.
- [ ] Suggest using https://github.com/tomkp/react-split-pane. We've had success in the past with version 2 of the library: https://github.com/tomkp/react-split-pane/tree/v2

<img width="360" alt="Screen Shot 2019-10-29 at 4 57 02 PM" src="https://user-images.githubusercontent.com/847542/67812673-b796bf80-fa6d-11e9-92ca-9305fdaf5553.png">

**Comment by StoplightDeb** [comment]
Chrome - ✅ 
Firefox - ✅ 
Safari - Currently blocked for testing by https://github.com/stoplightio/studio-internal/issues/1384

**Comment by StoplightDeb** [comment]
Looks good on staging!

**Comment by StoplightDeb** [comment]
@chris-miaskowski 
https://stoplight.testrail.io/index.php?/cases/view/6088
