### ISSUE TITLE
Add security schemes for header and query parameters to http operation docs

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#108]
Security schemes (API key, HTTP auth, etc) are not included in the Read view or published documentation.

Similar to how we're adding [security schemes](https://github.com/stoplightio/request-maker/blob/master/src/utils/getOperationData.ts#L11) in TryIt, we should also pass the security schemes into the http operation [request component](https://github.com/stoplightio/elements/blob/master/src/components/HttpOperation/index.tsx#L31) and render them in the correct [parameters](https://github.com/stoplightio/elements/blob/master/src/components/HttpOperation/Request.tsx#L16)

For example, the following http operation should result in 2 query parameters. One for "limit" and the other of "apikey":

```json
{
  "method": "get",
  "path": "/example",
  "request": {
    "query": [
      {
        "schema": {
          "type": "string"
        },
        "name": "limit",
        "style": "form"
      }
    ]
  },
  "security": [
    {
      "type": "apiKey",
      "name": "apikey",
      "in": "query"
    }
  ]
}

```

**Comment by philsturgeon** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/67381/67810122-44577280-fa9a-11e9-9c95-4d264db4463b.png">

**Comment by rossmcdonald** [comment]
@ssspear Does your work on this issue include adding security schemes to the "Try It" tab as well, or should I open a separate issue for that?

**Comment by lottamus** [comment]
@rossmcdonald "Try It" should already include schemes in headers and query parameters with the exception of [OAuth 1/2 tokens](https://github.com/stoplightio/request-maker/issues/89)

**Comment by rossmcdonald** [comment]
@lottamus Awesome, thanks for clarifying.

**Comment by chris-miaskowski** [comment]
Assuming that you meant embedded request maker @rossmcdonald it looks good
![image.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/00d6d47a-16b4-4b78-8161-679cf4b39f59)
I found a bug while testing it https://github.com/stoplightio/studio-internal/issues/1319

**Comment by philsturgeon** [comment]
@chris-miaskowski I believe this ticket is about docs not about request maker. When looking at docs it is important that we know what security scheme is required to make a successful request. Request maker is a different thing, also in Read view, but under a different tab than the "Docs" bit in question.

**Comment by StoplightDeb** [comment]
@chris-miaskowski -
https://stoplight.testrail.io/index.php?/cases/view/5342
https://stoplight.testrail.io/index.php?/cases/view/5343
https://stoplight.testrail.io/index.php?/cases/view/5344

**Comment by rossmcdonald** [comment]
This is probably my fault for not specifying, but we should also be displaying global security settings at the endpoint level. @lottamus should I open a separate issue for that, or should I re-open this one?

**Comment by lottamus** [comment]
@rossmcdonald I've created an issue here: https://github.com/stoplightio/http-spec/issues/44

**Comment by chris-miaskowski** [comment]
I reopened this issue. I looks like the issue description is not entirely valid.

```{
  "method": "get",
  "path": "/example",
  "request": {
    "query": [
      {
        "schema": {
          "type": "string"
        },
        "name": "limit",
        "style": "form"
      }
    ]
  },
  "security": [
    {
      "type": "apiKey",
      "name": "apikey",
      "in": "query"
    }
  ]
}
```

This is not a valid OAS3 file ^

Specifically, 
```
  "security": [
    {
      "type": "apiKey",
      "name": "apikey",
      "in": "query"
    }
  ]
```

Is not something one can put on an [Operation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject). `security` should be of type [Security Requirement Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securityRequirementObject)

I'm not sure what was implemented in this issue but definitely not

>For example, the following http operation should result in 2 query parameters. 

;)

@rossmcdonald @lottamus let me know what we do with this one. I moved to `In progress`, feel free to move back to QA when ready.

**Comment by lottamus** [comment]
@chris-miaskowski the issue description is referring to the IHttpOperation interface which is used to power docs and the request maker: https://github.com/stoplightio/types/blob/master/src/http-spec.ts#L32-L41
