### ISSUE TITLE
Error publishing docs

### ISSUE THREAD

**Issue by Ollegio** [stoplightio/studio#109]
**Describe the bug**
I tried to add request body to a path and then when i pushed changes and tried to publish docs, it said 
Variable "$build" got invalid value [{ buildnode: [object], changelog: [], action: "modified", semver: "unknown" }, { buildnode: [object], changelog: [array], action: "modified", semver: "major" }]; expected type changecontext at value[1].changelog[0].context.. 

**To Reproduce**
1. Create POST request
2. Add request body with type application/json
3. Add object with email: string and password: string
4. Commit changes
5. Press publish
6. Error

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25530070/64911511-a9961500-d733-11e9-8ea6-8af98266f4b4.png)

**Environment:**
 - Studio version: Web
 - OS: Xubuntu 19.04
 - Browser: Firefox 69

**Comment by lottamus** [comment]
A fix for this issue has been release in v1.1.3: https://github.com/stoplightio/studio/releases/tag/v1.1.3. Thanks for reporting!
