### ISSUE TITLE
When diagnostics tab is open, you cannot scroll to the bottom of file

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#110]
**Describe the bug**
When the diagnostics panel is expanded, it hides a portion of the editor window behind it. This can prevent you from seeing certain parts of the file.

**Screenshots**

![image](https://user-images.githubusercontent.com/4060903/64966487-7c954f80-d864-11e9-86d8-f6da71bb5f75.png)

**Comment by rossmcdonald** [comment]
@mallachari Can you tackle this when you're working on #94 ?

**Comment by mallachari** [comment]
Sure, I'll look into that. So far I thought it was done this way on purpose. Kind of popover.
