### ISSUE TITLE
Must sometimes double click on path operation tab to select it in form panel

### ISSUE THREAD

**Issue by marbemac** [stoplightio/studio#118]
**Describe the bug**

Must sometimes double click on path operation tab to select it if it does not already exist.

**To Reproduce**

1. Navigate to a post operation (must not be first operation that exists, e.g. get).
2. Click on the tab of an operation that does not exist
3. Note how get is selected.

**Expected behavior**

Should activate the operation tab that was clicked on.

**Screenshots**

![Sep-17-2019 01-37-05](https://user-images.githubusercontent.com/847542/65017370-3388de00-d8ec-11e9-809a-6e47d3dadf5e.gif)

**Environment (remove any that are not applicable):**

 - Studio version: 1.1.2

**Comment by StoplightDeb** [comment]
Looks great on staging!
