### ISSUE TITLE
Support running lint rules on JSON schema objects

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#122]
Related to https://github.com/stoplightio/spectral/issues/571. We should allow users to override the per-rule format in their Spectral configurations to run validations on JSON schema objects. I'm not sure what else is needed from the Studio side, but I wanted to open this issue just in case.

**Comment by P0lip** [comment]
Studio part has been implemented in https://github.com/stoplightio/studio-internal/pull/792
For the list of available formats, please refer to https://github.com/stoplightio/spectral/blob/develop/docs/getting-started/rulesets.md#formats
