### ISSUE TITLE
Defining Path + Query Parameters not exposing format + examples

### ISSUE THREAD

**Issue by mrum-cuscal** [stoplightio/studio#124]
When defining parameters, stoplight does not allow definition of  such things as 
- format type
- example 

This causes loss of information in the spec but also when trying an API request these fields cant be populated from example.

See the 2 screen shots. Both show additional properties defined for a string of type date time. The  first is a model, with a rich set of options, the second for a parameter. 

The issue occurs for both path and query parameters.

<img width="239" alt="model-DateTime" src="https://user-images.githubusercontent.com/55524081/65305932-9f5a9780-dbc7-11e9-83cc-44166e35fff8.png">
<img width="249" alt="param-DateTime" src="https://user-images.githubusercontent.com/55524081/65305933-9f5a9780-dbc7-11e9-96d1-d481421d3934.png">

**Comment by philsturgeon** [comment]
Thank you @mrum-cuscal, it turns out we both noticed this and I reported #134 shortly after you. I'm going to close this one and keep that one, as the video illustrates things just a smidge more. Follow that issue if you're interested in updates!
