### ISSUE TITLE
When using OpenAPIv2, use 'example' for storing examples instead of 'x-examples'

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#125]
Currently Studio uses a blanket `x-examples` extension for storing examples, when `example` is valid and supported for models within OpenAPIv2. 

OAS2 can have `example` for anything in a schema object, or any properties using the schema keyword, and for any other parameters it should use `x-example`. 

**Bonus Points:** If we want multiple examples we could then use `x-examples`. Creating the interface for this would make sense as OpenAPI v3.1 is going to have `examples` in the schema object too.

**Comment by philsturgeon** [comment]
`example` is not a valid OpenAPI v2 keyword, but the two vendor extensions are x-example or x-examples. I bumped into `x-example` the most in the wild, but... there is no good solution that works for everyone. If we change it from `x-examples` to `x-example` for user A then user B will be upset, and if we change it to `example` then user A and B will be upset.

**Comment by rossmcdonald** [comment]
@philsturgeon I believe `example` is valid in OpenAPIv2 for schemas: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object

**Comment by philsturgeon** [comment]
@rossmcdonald phew! I have been mislead by Apiary, carrying around false information without ever rechecking it. They wrote here that it is not allowed and I never got too stuck into OpenAPI v2.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/67381/65786852-97e64180-e125-11e9-8ae9-078d15a727c8.png">

Great, so `example` it is for anything in a schema object, or any of those weird kinda-schema-objects like headers, parameters, etc.

For response examples, I agree that jumping straight to `x-examples` is possibly heavy handed. If possible using the `example` keyword (which is different from the other `example` keyword ☝️ ) is probably fine. if they add multiple examples we can let them do that, but defaulting to always using extensions all the time is limiting the portability of the produced file.

**Comment by philsturgeon** [comment]
Inside a schema it works fine:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/67381/81120244-34768a80-8f24-11ea-9514-564183a30bf8.png">

x-example is not definiable for query parameters:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/67381/81120307-596afd80-8f24-11ea-8396-b9c836bffacd.png">

@lottamus can we add this to the keyword support matrix? x-example is common in OAS2, supported by ReDoc and other similar tools.

**Comment by philsturgeon** [comment]
This seems rather related to #381, which is the other rather confusing thread about example/examples. 

@lottamus is this going to be resolved at the same time? I'm not really sure what is happening for either of them but confusion about `x-examples` has come up in conversation a few times as its being used in places it's not needed.

**Comment by dgrstl** [comment]
Like @philsturgeon I was wondering about this in relation to [#381](https://github.com/stoplightio/studio/issues/381); Runtastic reported it awhile ago.

**Comment by lottamus** [comment]
@philsturgeon @dgrstl I don't believe we've solve this one in the work for #381 which was primarily focused on request/response/schema examples. The issue now seems to focus on adding support for `x-example` for OpenAPI v2 parameters. Is that right?

**Comment by philsturgeon** [comment]
I thought both issues were just about generally getting example and examples inside a schema done correctly, but... yeah?

I’m not sure why we’d ever have x-examples inside a schema object or for a parameter of any sort, but we could and should have either example or x-example depending on where, as the x-example screenshot I shared explains. 

1. let’s ditch x-examples as our interface doesn’t even let you define multiple examples for a schema property
2. Let’s use example in OAS2 wherever the spec says it’s allowed 
3. Let’s use x-example for OAS2 wherever the spec does not allow example, as can be seen by the vendor extension

**Comment by philsturgeon** [comment]
Starting a new issue for fixing example keywords over here https://github.com/stoplightio/studio/issues/491
