### ISSUE TITLE
Export dereferenced files from Studio

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#126]
Currently there is no way to retrieve a fully dereferenced API description from Studio directly (you have to publish and then retrieve it from the docs/explorer).

**Comment by philsturgeon** [comment]
Can we have an "Export" right click on the API?

<img width="461" alt="Screen Shot 2019-10-02 at 19 53 56" src="https://user-images.githubusercontent.com/67381/66069089-fb6dd600-e54e-11e9-825c-f7838279b0eb.png">

Could also be a floaty icon next to the API, maybe some triple dots or something. 

For now just do it in the appropriate format, we can do Export (in other formats) later.

**Comment by philsturgeon** [comment]
@benjdl @miguelgf giving you both a quick mention so you get notifications, as you both wanted this functionality. 

@benjdl you mentioned YAML/JSON, that's a good point, my screenshot would not cover giving users the choice. 

If the context menu (and ... for those who don't think to / cant right click) is just "Export" then we can have a little modal asking for which data format: 

- OpenAPI v3.0 JSON
- OpenAPI v3.0 YAML

In the future this could offer OpenAPI v3.1 and RAML and whatever else but we dont have to deal with that now.

**Comment by benjdl** [comment]
I'm currently using the package https://github.com/WindomZ/swagger-merger to do this "export":
```
./node_modules/swagger-merger/bin/swagger-merger.js -i ./documentation/reference/*my-api*/openapi.yaml -o full-documentation.yaml
```

Maybe it could help you, anyway if someone needs a temporary solution here it is.

**Comment by marbemac** [comment]
How about as a first step, an "Export Dereferenced" context menu item on api and model files, that copies to clipboard + displays a success notification to let the user know it's in their clipboard? Nice and simple to start - thoughts @P0lip @philsturgeon @benjdl @rossmcdonald?

**Comment by P0lip** [comment]
@marbemac 
Sounds good. I believe we might need some progress bar or something similar, as JSON schema models are not dereferenced by default, meaning it might take a bit of time in certain circumstances for dereference to take place.

**Comment by mallachari** [comment]
> @marbemac
> Sounds good. I believe we might need some progress bar or something similar

Maybe just two notifications and disabling export during dereferencing?

**Comment by benjdl** [comment]
@philsturgeon I think we should have these two options:
- "Export bundled files
      -> Save to JSON
      -> Save to Yaml"
- "Export dereferenced file
     -> Save to JSON
     -> Save to Yaml
     -> Copy to Clipboard"

The package I've shared use the dereferenced method and it does it really quick, although I've not used it intensively or with a very large documentation.

**Comment by philsturgeon** [comment]
Considering that we may well need an export modal for "OpenAPI v3.0 JSON" and "OpenAPI v3.0 YAML", we might also offer a "bundled" vs "derefferenced" toggle. These words are not well known so it might be a case of just offering `[x] Dereferenced` with a link to a page explaining what that means.

**Comment by philsturgeon** [comment]
This is happening in a very simple form with just copy to clipboard, but will return in the future with a fancy options modal. We're not going to be able to avoid offering various options for Export.

**Comment by marbemac** [comment]
Initial delivery in Studio v1.5 (right click on model or openapi file, see export option) - closing this one. Can open separate issue later for bundled export, which is more involved.

**Comment by philsturgeon** [comment]
Exporting as a file got done too! Look out for it in an upcoming version. Thanks everyone, especially @mallachari!

![69497311-77184d80-0f16-11ea-972b-8d478ce2cb81](https://user-images.githubusercontent.com/67381/69572020-2b6baf80-0fbb-11ea-9a84-4a022a8fcbee.gif)

**Comment by benjdl** [comment]
Great Job, thank you very much ! ;)
