### ISSUE TITLE
See a list of models in folder structure

### ISSUE THREAD

**Issue by Relequestual** [stoplightio/studio#127]
**User story.**
As a developer viewing the docs, I can see individual models in a hierarchical structure, so that I can see and understand individual models I could use in my application.

**Is your feature request related to a problem?**
Not really

**Describe the solution you'd like**
When docs are generated, the models are listed under "other", but I'd like to be able to see them listed under "models" in the folder structure they were found in.

As possible minimal fix would be to generate a single "models" page, which lists all of the known models and links to them.

**Additional context**
This project has a number of schemas which are defined in a hierarchical structure. This is important and useful information to developers viewing the models.

**Comment by P0lip** [comment]
Implemented as a part of https://github.com/stoplightio/studio/issues/57

**Comment by rossmcdonald** [comment]
@P0lip I don't think that #57 resolves this one. This issue has to do with the generated documentation, so this is less related to Studio and more with the new platform docs format (so more in Visibility team's realm).

**Comment by Relequestual** [comment]
@P0lip Yes, @rossmcdonald is correct.

For my use case, I want to only define models. I don't need or want to define APIs.
I like to have the folder structure on my file system respected in the generated docs.

**Comment by P0lip** [comment]
> @P0lip I don't think that #57 resolves this one. This issue has to do with the generated documentation, so this is less related to Studio and more with the new platform docs format (so more in Visibility team's realm).

Ah true, #57 certainly does not fix the issue in docs. I actually thought @Relequestual meant the Studio tree, but I misread it.

**Comment by philsturgeon** [comment]
If this is for docs lets move the feedback over to https://roadmap.stoplight.io which is the new home for all product feedback on anything. This is an old studio-only place that we're trying to ween people off. Thanks Ben!
