### ISSUE TITLE
description field blank lines double

### ISSUE THREAD

**Issue by moltar** [stoplightio/studio#131]
**Describe the bug**

There is something really strange happening with the description in the Paths section. Specifically the description of the HTTP method. It is difficult to describe, and even reproduce reliably, but I'll try to provide as much detail as possible.

For some snippets of text, the whole formatting breaks down and extra blank lines are added. Sometimes the lines can be added multiple times when switching back and forth resulting in many blank lines in the description text.

Some symptoms.

The description property YAML seems to be arbitrarily switching between the following formats:

```yaml
description: "..."
```

```yaml
description: |-
```

```yaml
description: >-
```

Also the presentation formatting is messed up:

![image](https://user-images.githubusercontent.com/491247/65551208-5e2bf580-deef-11e9-8036-4375776d13c9.png)

Offending code snippet:

```
Returns a `SessionCursor` object for the given session and `iterator`.

When `iterator` equal to:

* `previous` returns the previous Section ID and Item ID. I.e. what would normally show up in the "Previous Item" secondary navbar.
* `next` returns the next Section ID and Item ID. I.e. what would normally show up in the "Next Item" secondary navbar.
* `current` returns the current Section ID and Item ID. This can be used to restore a crashed session.
```

**To Reproduce**

See video demo below.

**Expected behavior**

1. No re-formatting of text.
2. Properly support Markdown syntax highlighting and rendering.

**Screenshots**

Video: https://drive.google.com/file/d/15TsxQrXqpGseni4T2RgineCsfd8i1t7V/view?usp=drivesdk

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.1.3 (1.1.3.6088)
 - OS: macOS 10.14.6
 - Browser: N/A (Desktop App)

**Comment by moltar** [comment]
Confirmed that this happens on the web version too.

**Comment by P0lip** [comment]
Hey @moltar.
We have decided to stick to literal style for block YAML scalars, therefore new lines should be kept now and follow the contents of form fields.
The change should be shipped in the next version of Studio.
A similar issue has been reported here https://github.com/stoplightio/studio/issues/68

**Comment by moltar** [comment]
Any idea when the next version will ship? I’m trying to migrate from apicurio and convinced all stakeholders, but hit this snag now 😅

Thank you for your quick response!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by P0lip** [comment]
> Any idea when the next version will ship? I’m trying to migrate from apicurio and convinced all stakeholders, but hit this snag now sweat_smile

Next week. :)

**Comment by moltar** [comment]
Thanks! I'll close the issue then, since there is another one tracking this.
