### ISSUE TITLE
Cannot view bottom of write panel

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#133]
The tabs are floating over the top of the text and I cannot read what is down there. 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/67381/65646178-32307300-dfc8-11e9-8690-8010ac0352ff.png">

It is also obscuring error messages for some users:

![image](https://user-images.githubusercontent.com/67381/65646207-50966e80-dfc8-11e9-8cea-476aa9810645.png)

**Comment by P0lip** [comment]
I'm pretty sure @mallachari has recently fixed it, but let's double-check.
@mallachari could you verify that?

**Comment by mallachari** [comment]
Right. There's already similar issue https://github.com/stoplightio/studio/issues/110
And there's also PR for that https://github.com/stoplightio/studio-internal/pull/789

**Comment by mallachari** [comment]
Fixed with https://github.com/stoplightio/studio-internal/pull/789

**Comment by philsturgeon** [comment]
Thank you!
