### ISSUE TITLE
Response header form missing "example" and "default" inputs

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#134]
**User story.**
As a Studio user trying to use Try it Now, I have to provide default values for all headers which might not actually have a default value. 

**Is your feature request related to a problem?**

Users are unable to provide an example for headers through the form view, meaning Try it Now is often not useful initially unless you pollute default.

<img width="583" alt="Screen Shot 2019-09-25 at 08 39 05" src="https://user-images.githubusercontent.com/67381/65646606-8daf3080-dfc9-11e9-818f-9b10d5f0e03d.png">

On similar lines, Security Schemes are treated differently to headers/properties, and do not have default _or_ example. This means folks struggle to use Try it Now. 

![Screen Recording 2019-09-25 at 19 14 09](https://user-images.githubusercontent.com/67381/65646677-d49d2600-dfc9-11e9-9593-5fafdc4d0502.gif)

**Describe the solution you'd like**

All properties, parameters, headers, etc that are capable of having a `default` and a `example` should in fact have both, for the sake of consistency. They should not be hidden under "Validation" as some are now, because they are not validation keywords. 

Adding these keywords will enable simple things like storing "good enough" keys for hitting the mock server, or an actual test/sandbox API key that'll respond with something useful when folks try it now.

**Comment by lottamus** [comment]
@philsturgeon a more feature rich options editor has been merged. You can expect this to land in Studio Web soon and Studio Desktop v1.11 next week! 🎉 


_Note it only includes valid options for the parameter depending on the spec version (v2/v3) and parameter type_

**OpenAPI v3**

![image](https://user-images.githubusercontent.com/7423098/76996042-cc8dc580-691e-11ea-9827-1d237b3d86af.png)

**OpenAPI v2**

![image](https://user-images.githubusercontent.com/7423098/76996146-fe9f2780-691e-11ea-90e1-4dfa0bfff27c.png)

**Comment by philsturgeon** [comment]
YAAAAAAAY great work!
