### ISSUE TITLE
Generate operation IDs for new endpoints

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#136]
Now that you can set operation IDs for an operation from the Forms view (#16), it would be great if an automatically-generated operation ID would be also be included when creating new operations from Studio. This could be helpful for a few reasons:

- Operation IDs are only required to be unique, and can be easily generated from the path + verb itself. For example, the operation `GET /todos` could be converted into `get_todos`. Automating the creation would be helpful for new users who do not understand why an operation ID might be needed.

- There is a default lint rule for warning when operation IDs are not present. This would allow for new operations to be created without new warnings being generated in the diagnostics tab.

- This can be a small value-add for Studio users, who now no longer need to think about operation IDs.

**Comment by NikVandewouwer** [comment]
Currently I have to set the operationId myself in the specs itself in order to get rid of the spectral error. You mention that "now" you can set the operation ID from the Forms view, but I cannot find it?

**Comment by rossmcdonald** [comment]
@NikVandewouwer It's not as obvious as it could be, but in the Form view you can see it here:

![Screen Shot 2019-10-08 at 10 07 38 AM](https://user-images.githubusercontent.com/4060903/66407832-81f14000-e9b3-11e9-9cac-1a75a43184d8.png)

**Comment by NikVandewouwer** [comment]
@rossmcdonald I can tell you with 100% certainty I don’t have that field on mac/win desktop client (1.1.4)

**Comment by rossmcdonald** [comment]
@NikVandewouwer Sorry for the confusion, you're absolutely right. Since #16 was closed a couple weeks ago I thought it was already in the stable release, but it doesn't look like this made it into v1.1.4 somehow. 

It will be going out in the v1.1.5 release this week, though, which should be available tomorrow.

**Comment by chris-miaskowski** [comment]
Looks good on staging environment. Coming out in 1.6.0! Good job @P0lip, let's ship it!
All new operations will come with an ID generate from the path and method (snake cased).

**Comment by StoplightDeb** [comment]
@chris-miaskowski - https://stoplight.testrail.io/index.php?/cases/view/5314
