### ISSUE TITLE
Order schema attributes in Read view by order they appear in object

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#139]
Currently rendering schema objects in Studio's Read view is not always deterministic, which can make it difficult to compare two objects by looking at them. Historically we have rendered objects by their ordering in the object itself, so I think it makes sense to continue that trend.

![image](https://user-images.githubusercontent.com/4060903/65776309-7b3b1100-e107-11e9-89c5-dc504a12ea4d.png)

**Comment by rossmcdonald** [comment]
Seems related to https://github.com/stoplightio/studio/issues/135

**Comment by lottamus** [comment]
Closing in favor of https://github.com/stoplightio/studio/issues/135
