### ISSUE TITLE
Switching git branches does not remove empty directories

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#14]
**Describe the bug**

A directory that exists on the current git branch will show up as an empty folder when switching to a git branch that does not have that same directory.

**To Reproduce**

1. Open a git project that has multiple branches
2. Create a new directory and add a file
3. Switch to another branch
4. Notice the directory is still there as an empty folder.

**Expected behavior**

Directories that do not exist in a git branch should not be displayed in the file tree.

**Environment (remove any that are not applicable):**
 - Studio version: 1.0.0-beta.8

**Comment by wmhilton** [comment]
Note: Between steps 2 and 3 of those reproduction steps, be sure to _commit_ that file. Otherwise it won't be deleted when switching branches at all.

**Comment by chris-miaskowski** [comment]
Tests passed on staging. Leaving for @StoplightDeb add tests to TR and then close.
