### ISSUE TITLE
Generate CURL requests for API calls

### ISSUE THREAD

**Issue by glennblock** [stoplightio/studio#146]
**User story.**
As a developer, I can generate a CURL request for an API + Method that I have selected, so that I can easily use CURL to make requests against my service

**Is your feature request related to a problem?**
CURL requests are easy to share with others, and embed in documentation for illustrating how to interact with the API.

**Describe the solution you'd like**
I'd like to be able to right click or press a button to generate a CURL request. The request could be displayed in a window where it could be copied to the clip board.

**Comment by philsturgeon** [comment]
@lottamus we could probably use https://github.com/ErikWittern/swagger-snippet for this one and get the feature done quicker. OSS FTW?

**Comment by lottamus** [comment]
@philsturgeon this is the same issue as https://github.com/stoplightio/platform-internal/issues/116 and I'm planning to use https://github.com/Kong/httpsnippet. We've used it in the past and it works quite well.

**Comment by philsturgeon** [comment]
This one is underway! :D

**Comment by glennblock** [comment]
Great!

**Comment by lottamus** [comment]
@glennblock sorry for the delay, this feature has been released with Studio v1.7. You should now see a "Code Generation" tab in the request maker. It offers cURL and a number of other languages. Let us know if there's one that's missing!

<img width="1305" alt="lottamus___vega___Studio___Stoplight" src="https://user-images.githubusercontent.com/7423098/71731256-da48aa00-2e09-11ea-8e5e-aca57a8203fa.png">
