### ISSUE TITLE
Allow ordering the fields of a model

### ISSUE THREAD

**Issue by glennblock** [stoplightio/studio#147]
**User story.**
As a user, I can re-order properties within the definition of my model, so that the properties are in an order that is more suitable to readability.

**Is your feature request related to a problem?**
The problem is I have no way to sort the fields. I have tried editing the underlying model definition file and changing the order and it does not seem to affect anything / the sort info appears to be stored elsewhere. 

**Describe the solution you'd like**
A common pattern in other products is to have arrows that I can use to move up or move down a property. Allowing me to drag with the mouse would be event better.

**Comment by philsturgeon** [comment]
This has come up a few times in conversations and #305, so it's back on our radar. v2.0 is nearly here, then we can get focused on nice little changes like this. 😎

**Comment by philsturgeon** [comment]
In an effort to keep all feature requests in the same place we're moving them to productboard, which lets people vote for stuff they wanna see and help us prioritize. I've been doing what I can to sneak this one up in priority, so fingers crossed it wont be long. Vote for it if you want it, it helps! https://roadmap.stoplight.io/c/98-drag-and-drop-ordering-in-json-schema-editor
