### ISSUE TITLE
Allow renaming fields in the designer

### ISSUE THREAD

**Issue by glennblock** [stoplightio/studio#148]
**User story.**
As a user, I can rename a field for a model in the UI.

**Is your feature request related to a problem?**
The problem is there is no way in the UI without falling to editing the config file to rename.

**Describe the solution you'd like**
Let me right click and have a rename option, similar to delete.

**Comment by lottamus** [comment]
Hey @glennblock,

If you click on the text where the field's name is, you should see a cursor and be able to type:

![2019-09-27 23 15 51](https://user-images.githubusercontent.com/7423098/65811354-c80cff00-e17c-11e9-913a-ee503aacc5ed.gif)

You might also be looking at the Read view as it looks very similar to the Form view.  Let us know if this helps or if you mean something different!
