### ISSUE TITLE
Add ability to import models

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#149]
Similar to the ability to import an API from a file, Studio should be able to import a model from file as well.

**Comment by chris-miaskowski** [comment]
@marbemac @P0lip 1.6.0 or 1.7.0?

**Comment by StoplightDeb** [comment]
@chris-miaskowski - looks like 1.7.0 unless I am missing a merge somewhere.

**Comment by P0lip** [comment]
I don't remember. Should be either 1.6.0 or 1.7.0 :laughing: 
More likely 1.7.0

**Comment by rossmcdonald** [comment]
It looks like this is present in v1.6.0.

**Comment by StoplightDeb** [comment]
Looks good on staging (current 1.7.0) too.
