### ISSUE TITLE
Stoplight studio removes quotations around examples making it of type integer instead of string

### ISSUE THREAD

**Issue by paulyk1983** [stoplightio/studio#151]
**Describe the bug**
When working with embedded models, any time I add a new property using form editor, any examples included in that model and that are string (with quotes) and include only numbers are converted into integers (quotes removed). This triggers the warning: "<property>.example" property type should be string". 

There is no way to prevent this happening, so I am forced to ignore the error, which is very much undesired and potentially hazardous when an ensuring an error-free document.

**To Reproduce**

1. Added an embbeded model to an API
2. In form editing view, add a property with type string to that model and give an example with just integers
3. In code view, add quotes around the example value, making it a string (this should be done automatically but the tool does not include this feature)
4. Add another property 
After adding another property, the example value sheds the quotation marks making it an integer again and mismatching against the defined type.

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.3
 - OS: Windows 10
 - Browser: None - using on-prem version

**Additional context**

**Comment by P0lip** [comment]
Fix should land in the next release.

**Comment by StoplightDeb** [comment]
Not able to reproduce the type change/mismatch anymore - fix slated for next release.
