### ISSUE TITLE
Order of properties does not keep when copying them into an object model

### ISSUE THREAD

**Issue by paulyk1983** [stoplightio/studio#152]
**Describe the bug**
 When copying and pasting code, properties from a separate document into stoplight studio code view, the properties do not remain in the same order. I have to restart the tool in order for the change to reflect in editor view. This makes migrating from next.stoplight to stoplight studio very frustrating since there is no way to reorder the properties easily using the form editor.

**To Reproduce**
1. Given the properties of a model in json format:

    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "address": {
      "type": "string"
    },
    "favorites": {
      "type": "string"
    },
    "history": {
      "type": "string"
    }

2. First, create a new object in stoplight studio
3. copy and paste the properties of the provided test object into the code view of the new model
4. In form editor view, the order of properties are not the same as in code view. For example, the 'history' property shows up underneath 'id' when it was originally located at the very bottom. Saving does not do anything
5. Restart the tool and the order now matches.

**Expected behavior**
The order of the properties should not change after pasting them in. I should not have to restart the tool for them to reorganize properly.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.3
 - OS: Windows 10
 - Browser: none - using on-prem version

**Additional context**
This also happens when copying and pasting properties within the same object. For example when I want to move the 'id' field to the top of the list.

**Comment by P0lip** [comment]
Related to https://github.com/stoplightio/studio/issues/135.

**Comment by lottamus** [comment]
Unfortunately we have not fixed this issue yet but it's on our radar! I'm going to close this issue to consolidate with https://github.com/stoplightio/studio/issues/135
