### ISSUE TITLE
Zoom in/out not working

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#155]
**Describe the bug**
Clicking the zoom in and zoom out through the Window menu doesn't seem to do anything.

**To Reproduce**

1. Click the Window menu
2. Click menu item for Zoom in or zoom out
3. nothing happens
4. Try keyboard shortcuts
5. nothing happens

**Expected behavior**
Text of ui should get larger/smaller

**Screenshots**
![Screenshot from 2019-10-01 11-45-15](https://user-images.githubusercontent.com/284451/65979040-a93f8e80-e442-11e9-94a6-d1b4698e12da.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.1
 - OS: Ubuntu 18.04
 - Browser: 71.0.3578.98 (Official Build) (64-bit)

**Comment by adamculp** [comment]
As added context. This functionality works with similar apps, like Slack.

**Comment by mallachari** [comment]
It looks like this issue was solved somewhere on the way as it's quite old one.
It zooms in/out fine now.

**Comment by philsturgeon** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/76329871-6802b300-62ed-11ea-8c62-17845b8479ce.png">

Sure does! Sorry for the delay @adamculp but we got you!
