### ISSUE TITLE
Check for update dialog not able to close

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#156]
**Describe the bug**
If I click Check for update in the Help menu, it works fine. However, the dialog saying I'm up to date has no way to close it. Forcing it closed causes the entire app to close.

**To Reproduce**

1. Click Help menu
2. Select Check for update
3. Dialog opens and informs it is up to date
4. Cannot close dialog
5. Cannot use Studio while dialog is open, even if in the background

**Expected behavior**
There should be some way to close the dialog

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.1
 - OS: Ubuntu 18.04
 - Browser: 71.0.3578.98 (Official Build) (64-bit)

**Comment by XVincentX** [comment]
@adamculp Can you elaborate more on the "Cannot close the dialog"? I've been trying multiple combination and I've always been able to close it out with no problems.

Do you mean that, when clicking on the X button, nothing happens? Can you move the dialogbox around or is it completely frozen?

**Comment by adamculp** [comment]
I haven't tried the latest version, so maybe it was fixed. However, when I submitted this, the dialog would display over top of everything, and there was nothing to click for closing it. There was no X button at that time.

I'll get the latest version over the next couple days and try again.

**Comment by adamculp** [comment]
@XVincentX  I decided to get the latest version and knock this out. The latest version dialog closes as expected when you click away from it. So, this appears to be fixed now. Therefore, I will close this ticket with this comment.

Thank you.

**Comment by marbemac** [comment]
Thanks for checking @adamculp!
