### ISSUE TITLE
Updates to top-level servers properties are not propagated

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#157]
- Within an OpenAPIv3 file, change the top-level server attribute
- Navigate to an operation within the API
- Notice that the changed server is not picked up

**Comment by marbemac** [comment]
@StoplightDeb @chris-miaskowski I believe this actually just made the 1.1.6 cutoff last Wednesday, so we should probably verify when you have a moment. Relevant PR is https://github.com/stoplightio/studio-internal/pull/896
