### ISSUE TITLE
Generate schema from example JSON

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#159]
**User Story**

As a user "creating documentation" (or trying to make description docs in general) for an existing API, it is not just incredibly time consuming to manually write up schemas for existing endpoints, but the chance for human error is immense. There are many many ways I can [bodge bits of schema and OpenAPI together using various tooling](https://apisyouwonthate.com/blog/creating-api-specifications-from-bullst), but if Studio could look at a real response and offer me a "Generate Schema" button, I'd be a very happy customer. 

**Details**

Updated requirements: https://github.com/stoplightio/studio/issues/159#issuecomment-655280252

Preserving the original issue comment below in case helpful, but the requirements described below are stale.

---

There are plans for Prism to handle recording traffic to local files, and/or record traffic to the database in hosted mode, all of which could be used to somehow get "Learning" or "Schema Generation" done.b All of these features are a bit far off, with some of it not out of discussion mode yet. 

In the mean time, I think it would be incredibly useful for our customers if Request Maker (in Studio under Try it Now) had some sort of "Generate Schema" button, which would convert a JSON response to JSON Schema.

There are a lot of tools out there which do this already, primarily https://app.quicktype.io/

![Screen Shot 2019-10-02 at 14.31.29.png](https://images.zenhubusercontent.com/5d1f7c5b8a1fa426d066830f/6fbe3418-c0ba-44b8-9a04-88cd68125f40)

This generates JSON Schema Draft 06, which gets complicated. If we were to shove that JSON Schema D6 and shove it straight into the Model, it would be invalid OpenAPI. There is also the question of how to handle JSON Schema Standalone, which for us is generally "OpenAPI-flavoured JSON Schema (a.k.a Draft 4 but not really).

We can either pass it through https://github.com/wework/json-schema-to-openapi-schema, or we can pass it into http-spec along with other information about the request and response to make a full "Operation", as this should normalize the schema. 

So, if the Generate Schema button takes the JSON, passed it to [quicktype JS API](https://github.com/quicktype/quicktype), then normalizes it through http-spec, we can hopefully have Studio take that http-spec and merge it with the existing operation. 

Keeping it as simple as possible, I think it should either only show up if no response bodies exist (for that mime type), _or_ when you click that button it overrides. 

Alternatively, if all of the above is too complex, the "Generate Schema" button could just show a popup which gives the user the OpenAPI Schema content to copy and paste. This would be more useful than sending them off to quicktype.

@marbemac feedback appreciated before this goes off to be worked on.

**Comment by Lizhooh** [comment]
Try using `generate-schema`

https://www.npmjs.com/package/generate-schema#example-1

**Comment by philsturgeon** [comment]
We can evaluate it but probably going with https://github.com/quicktype/quicktype

**Comment by philsturgeon** [comment]
This one is getting a lot of duplicate requests. We should bump it up the list if possible, it should be a quick win.

**Comment by oligriffiths** [comment]
A++ would love

**Comment by philsturgeon** [comment]
This one is a key "Next parity" feature.

<img width="760" alt="Screen Shot 2020-06-09 at 2 47 20 PM" src="https://user-images.githubusercontent.com/67381/84149127-3fab6180-aa60-11ea-96d9-5b97675135a7.png">

**Comment by marbemac** [comment]
I suggest we stick with tried and true for now, from next:

```js
import JsonSchemaGenerator from 'json-schema-generator';

const schema = JsonSchemaGenerator(example);
```

And a generate schema button above the json schema editor, that when clicked opens a dialog for user to paste example in any press go, thus generating and setting the schema.

<img width="285" alt="Screen Shot 2020-07-07 at 11 39 45 PM" src="https://user-images.githubusercontent.com/847542/86877007-929e2600-c0ab-11ea-8e06-6cf6d0117119.png">

---

Trying to accomplish this from the try it UI is too disconnected IMHO, and is closer to learning which is a related but different use case that requires a lot more work and UX thought.

**Comment by philsturgeon** [comment]
However it comes is fine, it's intended to be a quick solution on the way to proper learning so however we want to go about it is good with me!

**Comment by philsturgeon** [comment]
We did this! Check it out in Studio Web right now, and it'll be in the next release of Studio Desktop. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/67381/95343972-687e1f00-08b9-11eb-8748-871ec6de57e3.png">

**Comment by oligriffiths** [comment]
@philsturgeon any chance this is also a node module so it can be used in automated/cli tools too?

**Comment by philsturgeon** [comment]
@oligriffiths here you go mate! https://github.com/stoplightio/json-schema-generator

Glad to hear you're still alive too! Hope NYC is treating you well, or you managed to escape. 👋

**Comment by oligriffiths** [comment]
Thanks @philsturgeon that's great!

Just about alive, still in NYC. Should catch up about your reforestation soon, fixing the world one tree at a time!
