### ISSUE TITLE
Add operationId input to the "operation" form

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#16]
**User story.**
As a user, I should be able to edit my operation's `operationId` via an input on the operation form.

**Describe the solution you'd like**

- Add an input below the operation's path that updates the operation's "operationId" property

**Additional context**

<img width="1509" alt="Stoplight_Studio" src="https://user-images.githubusercontent.com/7423098/62025153-ec5c5780-b19c-11e9-80e7-eac132f1a762.png">

**Comment by philsturgeon** [comment]
This is an old issue but I think the work was done, or is being done at the moment? @lottamus
