### ISSUE TITLE
Publish from Studio Desktop

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#164]
**User story.**
As a Studio Desktop user, I can publish from Studio Desktop, so that I don't need to switch to Studio Web.

**Is your feature request related to a problem?**

Studio Web and Studio Desktop can generally do all the same things, but there are [a few big differences](https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/web-vs-desktop-app.md).

One of these is the lack of a Publish button on Studio. It takes the user to Studio Web, which can be confusing, and even if they understand what is happening it is not the optimal workflow.

_For any users seeing this, one workaround is using [Stoplight CLI on your Continuous Integration](https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/07-publish-via-ci.md)._

**Describe the solution you'd like**

The desired functionality is getting an identical flow as Studio Web. Click that button, have it show you the diff, etc. Some way to see a docs preview at this point would be extra bonus yes please points.

Technically I'm not entirely sure, probably running whatever code the Stoplight CLI is running in the background, but that would involve Studio knowing the project token. I guess this is being grabbed by GraphQL in the background, and if not, we gotta figure out how to do that. (Log into Studio, or match by GitHub/GL/etc authenticated users somehow, etc.)

**Comment by StoplightDeb** [comment]
@lottamus @chris-miaskowski - what is the expected behavior here for logged in and non-logged in users?

**Comment by chris-miaskowski** [comment]
@StoplightDeb 

The following says it:

> The desired functionality is getting an identical flow as Studio Web. Click that button, have it show you the diff, etc. Some way to see a docs preview at this point would be extra bonus yes please points.

Basically, the expected behavior is to be able to publish directly from Studio.

Anonymous users cannot publish as far as I remember so the same is expected in Desktop app.

All is good, I'm signing off.

Good job @lottamus
Excellent description @philsturgeon

**Comment by StoplightDeb** [comment]
@chris-miaskowski  - https://stoplight.testrail.io/index.php?/cases/view/5312
