### ISSUE TITLE
Ref Builder > Search for models in project to reference should not be case-sensitive

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#165]
To Reproduce:

- Create a model with file name 'Orange.yaml' (or json) and add some data to it
- Under an endpoint, navigate to response body and open reference dialog
- Type "orange", see no results

![Screen Shot 2019-10-03 at 12 23 24 PM](https://user-images.githubusercontent.com/4060903/66149413-a8d8fc00-e5d8-11e9-8ced-2307931e0067.png)

![Screen Shot 2019-10-03 at 12 23 30 PM](https://user-images.githubusercontent.com/4060903/66149405-a676a200-e5d8-11e9-8a9a-42367152fd0b.png)

**Comment by lottamus** [comment]
Just need to change this from an `.includes` to a case-insensitive match: https://github.com/stoplightio/studio-internal/blob/develop/src/components/JsonSchemaEditor/hooks/useRefProviders.ts#L18

**Comment by StoplightDeb** [comment]
Looks good :)
