### ISSUE TITLE
Stoplight Flavored Markdown: local $refs in json_schema do not resolve

### ISSUE THREAD

**Issue by jbourquin** [stoplightio/studio#166]
**Describe the bug**
When using Stoplight Flavored Markdown in docs, json_schema is not able to resolve references to local models. References to external models appear to work, but local references relative to the current markdown file fail.

**To Reproduce**

1. Create an API model in Stoplight Studio
2. Create a new article and add a json_schema element to it.
3. Create a schema reference to the API model in step 1.

```
{
  "$ref": "../reference/common/models/test.v1.json"
}
```

**Expected behavior**
The json_schema element should be able to resolve local references to API models.

**Screenshots**
![Screenshot 2019-10-03 14 34 33](https://user-images.githubusercontent.com/1550943/66162574-c95e8180-e5eb-11e9-9bb1-d1cc90f517bf.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.4.6744
 - OS: macOS 10.14.6

**Comment by StoplightDeb** [comment]
I like it! Link resolves correctly now with no error.

**Comment by xSke** [comment]
This seems to still be an issue.

**Comment by rossmcdonald** [comment]
Thanks @xSke. This is indeed re-occurring.

**Comment by sebfie** [comment]
Yes, I also have this issue !

**Comment by sebfie** [comment]
up !

**Comment by P0lip** [comment]
Hey! This issue should no longer be occurring.

**Comment by sebfie** [comment]
Thank you so much !
