### ISSUE TITLE
Indicate invalid JSON/YAML more clearly

### ISSUE THREAD

**Issue by glennblock** [stoplightio/studio#169]
Using the write view I was able to modify my JSON model definition such that it was invalid JSON. My change saved and resulted in only showing the JSON / no longer allowing the read / form view when I loaded. See the screen shot below.

<img width="1552" alt="Screen Shot 2019-10-06 at 11 09 36 AM" src="https://user-images.githubusercontent.com/141124/66273629-6149ae80-e82a-11e9-84cf-b2b651330822.png">

This should show as invalid JSON in the diagnostics panel at the bottom, and maybe do a little more:

- Do not auto-save invalid JSON/YAML
- Hide save button and block Ctrl + S if invalid

We are only talking about "literally not valid JSON" and not "Spectral found linter warnings" or anything like that.

**Comment by P0lip** [comment]
![image](https://user-images.githubusercontent.com/9273484/66612925-ec78ca80-ebc3-11e9-8dd0-88757ce9201a.png)
These errors say the syntax of JSON file is wrong. I agree they might cause confusion, therefore we could try to make them human-friendly. What do you think?

> Do not auto-save invalid JSON/YAML
> Hide save button and block Ctrl + S if invalid

This is a bit tricky, as there are cases where the syntax is considered as non-standard and hence invalid for us. For instance, one might want to put comments in JSON - yeah, they are not really a part of any spec AFAIK, but certain parsers support them, i.e jsonc-parser, and they are also very commonly used in some config files, i.e `tsconfig.json`.

That said, we could indicate the error state better, as right now it's in fact pretty easy to lose the track of it.
Would having a warning showing when you try to save a file with syntax errors might be a fair compromise?

cc @marbemac @philsturgeon

**Comment by marbemac** [comment]
If the JSON/YAML cannot be parsed, we won't be able to do much in Studio in any case. I suggest we require a confirm on save if save is attempted (wether by auto-save, or manually) and the json/yaml is invalid. Would have to be careful here re auto-save, as json/yaml can be temporarily invalid as end user types. Would be pretty annoying to get the notification when just changing the document.

Suggest an error notification, with a confirm button. Should be "unique" e.g. pressing saving multiple times does not stack the notification. Should automatically dismiss when file becomes inactive (navigating to another file).

This makes it much more apparent that there is a critical issue that should be addressed, but leaves an escape hatch for users that really want to save an invalid file, or just in case we mistakenly flag something as invalid that is not invalid (`jsonc`, for example).

**Comment by StoplightDeb** [comment]
@P0lip - I see suggestions from the user and from you and Marc on how to address this, what is the expected behavior with invalid syntax?

**Comment by P0lip** [comment]
@StoplightDeb 
I implemented suggestions from @marbemac

**Comment by chris-miaskowski** [comment]
Something's not right @P0lip. See the screencast:

![invalid-json.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/550c671d-c7b7-4143-9a16-e20fe716fd3a)

Issue 1 (warning not shown the second time I save invalid json):
- open file (refreshed browser window)
- type invalid json
- press ctrl+s
- shows warning (yay!)
- save
- remove invalid json and save
- type invalid json again, save
- no warning :(

Issue 2 (warning not shows on autosave):
- open jsno
- type invalid stuff
- wait
- file saves (see the commit button turns green)
- warning not shown, but should be

**Comment by P0lip** [comment]
> Issue 1 (warning not shown the second time I save invalid json):

That's expected.

Re the second issue - will take a look

**Comment by chris-miaskowski** [comment]
@P0lip any updates?

**Comment by P0lip** [comment]
@chris-miaskowski 
Just tried it out and I cannot reproduce the second issue.
![image](https://user-images.githubusercontent.com/9273484/71983776-d19c0d80-3227-11ea-803a-1089a682d2ef.png)

**Comment by wmhilton** [comment]
@P0lip it appears that the "Confirm" button is a one-time opt-in-forever kind of deal? E.g. with auto-save if I hit confirm, it'll continue to auto-save invalid JSON in future edits to the file. Makes sense to me.

@chris-miaskowski I think it's basically working as intended, no? Albeit not as the PR description describes it.

**Comment by wmhilton** [comment]
right right I won't touch the Ready To Test status @P0lip lol.

**Comment by P0lip** [comment]
> @P0lip it appears that the "Confirm" button is a one-time opt-in-forever kind of deal? E.g. with auto-save if I hit confirm, it'll continue to auto-save invalid JSON in future edits to the file. Makes sense to me.

Yeah, exactly this. It'd be annoying to confirm each save, wouldn't it?

**Comment by glennblock** [comment]
Great to see the fixes. I have not gotten to try out the new version yet,
but I will this week!

**Comment by chris-miaskowski** [comment]
@P0lip, gotcha, I'm cool with that - let's ship it :shipit:

**Comment by philsturgeon** [comment]
Let us know if this works Glenn, and if it doesn’t we can reopen the issue. 🙌🏻

**Comment by chris-miaskowski** [comment]
I will reopen for bookkeeping, want to add some test cases before I close. Other than nothing to watch here ;)

**Comment by mmiask** [comment]
Created a new test case in TR: https://stoplight.testrail.io/index.php?/cases/view/8205
