### ISSUE TITLE
"operation" form body should include the "name" property

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#17]
**Describe the bug**

In OpenAPI v2, parameters have a required "name" property. When adding a request body via the operation form, the name property is not added and there is not an input to add one.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7

**To Reproduce**

1. Create an OAS2 specification
2. Create a POST operation
3. Create a "JSON Request Body"

**Expected behavior**

The required "name" attribute would be included in the new body parameter. It can match the "in" property. For example if the parameter's `in` property is "body", the automatically added "name" should be "body".

**Screenshots**

![image](https://user-images.githubusercontent.com/7423098/62025550-14988600-b19e-11e9-830b-b4dfe268edc6.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.0.0-beta.8

**Comment by mallachari** [comment]
This was already done here: https://github.com/stoplightio/studio-internal/pull/386
