### ISSUE TITLE
Description doesnt have a label

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#171]
UI tweak, could we label our inputs so its clear that this bunch of text is a description? This is obvious for us and obvious for many OpenAPI superfans, but not immediately clear to beginners or users without context.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/67381/66310267-09837400-e90c-11e9-9cb6-dc2200f2fee2.png">

**Comment by philsturgeon** [comment]
Also the placeholder says "Endpoint description..." (only where there is no text) but we talk about operations everywhere else. We should be consistent with language, so probably call this Operation Description?

**Comment by philsturgeon** [comment]
Most of our text inputs are like this: request body description, etc.

**Comment by lottamus** [comment]
Closing this as now we have labels for description and operation id 🎉 

![image](https://user-images.githubusercontent.com/7423098/72871935-b4e4e880-3cb1-11ea-847f-2d103e650aa6.png)
