### ISSUE TITLE
Add button for "Manage Ruleset"

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#172]
Spectral being baked into Studio is amazingly powerful, and when I demo it to people they get very excited. At the moment it is still rather hidden, and mainly only for power users, as they need to know to create a file in the root called `.spectral.yaml`.

Maybe an "Add Ruleset" or "Add Style Guide" button, which opens a modal and suggests the name `.spectral.yaml` by default. We can disable the edit form and the UI can make it clear "we only support one ruleset at the moment" and so people only have the choice to make `.spectral.yml`, then we can figure out multiple rulesets later?

![image.png](https://images.zenhubusercontent.com/5d1f7c5b8a1fa426d066830f/2acc431a-1bf5-4a9e-9611-ac1361ca02a3)
_Just another option on here._

If we do not go with this approach (maybe we think we will never have multiple ruleset support) we cant really have it on the add menu. In that case, we need to figure out another UI for it.

**Comment by chris-miaskowski** [comment]
Sanity checked on staging web. Looks good. Will create test cases and close later but you can forget about it @P0lip. Good job and a great feature @philsturgeon !
