### ISSUE TITLE
Display API version in APIs sidebar tree

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#174]
When an API has a version, it should be displayed in the sidebar (similar to how model versions are displayed). For example, if I have the API:

![image](https://user-images.githubusercontent.com/4060903/66349951-a69bd800-e91f-11e9-8be9-7afe7d44bd62.png)

Currently it displays as:

![image](https://user-images.githubusercontent.com/4060903/66350001-c59a6a00-e91f-11e9-92e6-b9d754762b40.png)

It would be helpful to display as:

![image](https://user-images.githubusercontent.com/4060903/66349986-bddac580-e91f-11e9-93fc-9461669d1796.png)

So I can have multiple versions of an API in the sidebar.

**Comment by philsturgeon** [comment]
Doing this in docs and yeah Studio needs some love from versioning in general. Let's take care of this through productboard.
