### ISSUE TITLE
UI: Description / Operation ID side by side looks squashed

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#175]
# This is just for the Forms view. Operation ID is not displayed in Docs.

In Form View on an Operation, trying to write `get-available-payment-methods` in the operation ID chops off as its sat next to the description and doesn't have a lot of space.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/67381/66397911-1cb24480-e9dd-11e9-8679-ba3789868fec.png">

Maybe stack them.

**Comment by lottamus** [comment]
Stacking them and including a small label above/below would be helpful 👍

**Comment by chris-miaskowski** [comment]
Awesome! Looks good!

**Comment by chris-miaskowski** [comment]
Ok, that stopped working right now

![image.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/f915230f-52ff-4517-998c-b73276bd56c5)

First case when something that did work stopped work after fixes for other issues.
That may mean we need to start retesting stuff.

@marbemac ^

**Comment by lottamus** [comment]
@chris-miaskowski I think you're looking in the wrong spot. We only show operation ID in the forms view

**Comment by StoplightDeb** [comment]
Looks good on staging

**Comment by chris-miaskowski** [comment]
@lottamus oh yes :facepalm:
