### ISSUE TITLE
Display progress indicator when switching git branches or pulling

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#178]
**User story.**
As a user when I switch branches or manually pulls, I see some loading state that signifies to me that this process might take a few moments and nothing is broken.

**Is your feature request related to a problem?**
Some users with larger git repositories have noticed that it can take a while to switch between branches. This in itself isn't a huge deal, however there is no progress bar or indication that Studio is "working" when switching the branches. This can give new users the impression that the UI is frozen, when it's not.

**Describe the solution you'd like**
Maybe just a nice progress bar across the top of the header or along the metabar? Or could popup a dialog with a progress bar so the user can close out of it?

**Comment by lottamus** [comment]
Related: https://github.com/stoplightio/studio-internal/issues/692

**Comment by lottamus** [comment]
@wmhilton let's use the same loading/processing screen we have when you initially open/clone the project
