### ISSUE TITLE
Bad display of json example in Docs

### ISSUE THREAD

**Issue by MarcLevisse** [stoplightio/studio#181]
The display of the example edited below should not be embedded in "value" json object : 

In the editor : 
![vehiclewithid_example_edit](https://user-images.githubusercontent.com/55258215/66474388-80964500-ea91-11e9-84b9-a8dc25a373ec.png)

Bad display : 
![vehiclewithid_example_display](https://user-images.githubusercontent.com/55258215/66474412-8db33400-ea91-11e9-899f-336489156923.png)

**Comment by MarcLevisse** [comment]
sorry, duplicate with #176

**Comment by marbemac** [comment]
Good catch, closing in favor of #176 (and escalating that one to get this taken care of asap).
