### ISSUE TITLE
Discarding changes doesn't update sidebar

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#184]
**To Reproduce**

1. Create an API
2. Click Commit > Discard changes
3. View sidebar

**Expected behavior**
The newly-created API would be removed.

**Actual behavior**
The newly-created API is still present in the sidebar. Note that this does not just apply to APIs, but models and other artifacts as well.

Reproduced with v1.1.4

**Comment by lottamus** [comment]
Related issue: https://github.com/stoplightio/studio-internal/issues/894

**Comment by StoplightDeb** [comment]
This looks good - files are removed from the file structure if discarded before commit.  

Note - if you create a folder and add files to it, and then discard the files, the folder is still there. 
 filed a followup ticket #1080 in case we want to clean this up?

Closing this one!
