### ISSUE TITLE
Endpoint security data does not update after changing schema's key

### ISSUE THREAD

**Issue by mallachari** [stoplightio/studio#187]
**Describe the bug**

Changes is security schema key are not reflected in operations data.

**To Reproduce**

1. Create security schema. 
2. Add security to endpoint. 
3. Change security schema's key. 
4. Endpoint key will not update.

![Peek 2019-10-11 17-36.gif](https://images.zenhubusercontent.com/5d3eb13f99357a3001f5f485/139b9ebf-0e25-402f-9d1a-5c7e1d3b6fbf)

**Comment by StoplightDeb** [comment]
Endpoint updating to reflect changes in API security schema, closing this!
