### ISSUE TITLE
Doc generation malfunction with some embedded refs items

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#191]
Hi,

If you create objects with a prefix with a dot, the documentation of objects that reference them fails.
For example :

```yaml
  Test.TestObject:
    title: Test.TestObject
    type: object
    properties:
      idobject:
        type: string
      valuesofrefs:
        type: array
        items:
          $ref: '#/definitions/Test.ReferencedObject'
  Test.ReferencedObject:
    title: Test.ReferencedObject
    type: object
    properties:
      idreference:
        type: string
      valuereference:
        type: string
```

Does produce an error in the generated documentation:
![image](https://user-images.githubusercontent.com/20415788/66765088-7322f580-eeab-11e9-9e9f-af6a44369d5f.png)

This is a sample I did to reproduce for the bug report. I got the problem with actual work.

The documentation of functions returning the containing object do work though, the embedded object is OK.

**Comment by lottamus** [comment]
Hey @john-doe-2016 thanks for reporting! I believe this was fixed in a recent release as I can no longer reproduce.

If you're able to reproduce again, can you re-open this issue?

**Comment by john-doe-2016** [comment]
Hey,

Indeed, I just tested and do no more have the problem. And it manage very well objects/refs  embedding since I have an object that contains a collection of another which contains two collections of two other objects, and everything is well presented now.

You're a great team! In three days, one bug and one feature request done (the query field description is alive too)!!!

Many thanks.
Have a nice WE
