### ISSUE TITLE
Maintain references of models

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#192]
As a user, I can rename a model, so that I can get a better ergonomics and still have a valid document.

Other model or endpoints using this model should be modified to maintain the document consistance.

At the moment, one should maintain itself the various model references in the API specification.

_**Update:** 2019-11-14 by @philsturgeon_

1. Renaming models will change the file name but not update $ref's to them.

![Untitled](https://user-images.githubusercontent.com/67381/68853537-1ac15c80-06d2-11ea-8064-65ecefc1e89d.gif)

2. Renaming the model in API tree view will update the Embedded Model name, but not update any refs to that either.

<img width="969" alt="Screen Shot 2019-11-14 at 11 30 46" src="https://user-images.githubusercontent.com/67381/68853669-725fc800-06d2-11ea-956e-a5ba30a3351c.png">

This is all happening in 1.4.2, I'm just updating to 1.5.0 now.

**Comment by philsturgeon** [comment]
Renaming models will update $ref's to that model. Let me know if this is not working for you.

**Comment by john-doe-2016** [comment]
Hi,

It does not work neither for model included by another one, nor for a model returned by a service operation.

I tested in both the web app and the desktop app (after having restarted to get the update), and both by using the rename "right button" option or renaming in the file.

**Comment by john-doe-2016** [comment]
I use embedded models, maybe it explains that it is not working.

**Comment by john-doe-2016** [comment]
Hi @lottamus @philsturgeon ,

Do I have something to do to "reopen" this bug?

Best regards

**Comment by philsturgeon** [comment]
There you go! Somebody will take a look at this. :)

**Comment by john-doe-2016** [comment]
Thank you @philsturgeon

**Comment by philsturgeon** [comment]
@lottamus checked this out and added a video and some notes. This is a bug AFAIK.

**Comment by P0lip** [comment]
@philsturgeon 
> Renaming models will change the file name but not update $ref's to them. This used to happen so this seems like a regression.

@marbemac correct me if I'm wrong we've never supported that. I agree it'd be a nice enhancement.

> Renaming the model in API tree view will update the Embedded Model name, but not update any refs to that either.

Same. We've never supported rewriting refs.

**Comment by philsturgeon** [comment]
I thought I’d done this, and I definitely remember people mentioning it. Drag and drop updated them I think, but drag and drop is pretty inconsistent as to when it works and it seems like renaming is too. Can we consider this a feature request? It’s incredibly important that we don’t break references otherwise... what’s the point?

**Comment by P0lip** [comment]
> Can we consider this a feature request? It’s incredibly important that we don’t break references otherwise.

Absolutely. I totally agree that having such a feature is important. We just haven't implemented it yet.

**Comment by Hipska** [comment]
What's the status on this? Came here as I got a lot of errors by renaming a model in the UI and the refs were not updated. Would love to have that in there too.

**Comment by philsturgeon** [comment]
@Hipska this is very high on a list of issues we'd love to get sorted after the next major release is out. The new release will blow your socks off, but we've gotta put some stuff like this aside for a bit to get there.

**Comment by silesky** [comment]
@philsturgeon does "closed" mean that this has been added? Because, as of today, this does not work -- renaming a model will not update any refs.

**Comment by philsturgeon** [comment]
This has been moved over to our feature roadmap here: https://roadmap.stoplight.io/c/96-automatically-rewrite-references-and-links-on-filename-change

If anyone is still interested in this feature, please show their support over there. This feature tracker is going away.
