### ISSUE TITLE
Removing last file in repo leaves Studio in inconsistent state

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#193]
To reproduce:

- Create an empty repository and clone with Studio
- Create a specification, commit + push
- Delete specification, commit + push
- Notice that commit button is still green

![Screen Shot 2019-10-14 at 1 44 48 PM](https://user-images.githubusercontent.com/4060903/66775280-42ca5f80-ee89-11e9-81d2-cab93bf58aee.png)

Seems related to the discard issues encountered here - https://github.com/stoplightio/studio/issues/184

**Comment by marbemac** [comment]
Was able to reproduce on v1.4.2. @wmhilton this looks like it might be event related, possibly to do with isomorphic-git? In general not a huge priority, I just wonder if there is a more significant issue lurking behind this that might be worth fixing.

**Comment by philsturgeon** [comment]
@wmhilton did this one get sorted out?

**Comment by philsturgeon** [comment]
No status update for a whole year so gonna close it.
