### ISSUE TITLE
Have the parameters description displayed in docs

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#195]
As an API reviewer or user, I want to the the field descriptions while browsing request params and objects

At the moment, they are not available in Docs view, and barely in 'Try it' view. Those description are great help to understand the parameter goal and usage.
![image](https://user-images.githubusercontent.com/20415788/66909718-88179a00-f00d-11e9-9b72-11360e6479dc.png)
![image](https://user-images.githubusercontent.com/20415788/66909751-982f7980-f00d-11e9-8bbe-68f34131b8b6.png)

The description could be displayed under the 'required' information in the doc view, and perhaps in a 'mouse over bubble' in the 'try it view'

**Comment by chris-miaskowski** [comment]
Hey @lottamus, are we ready to pass this issue to QA? If so, can you please update the description with what the final resolution was?

**Comment by lottamus** [comment]
@chris-miaskowski this issue has already been released as part of v1.2.0 Platform & Studio Web. No need to QA again for Studio Desktop but waiting until Wednesday to close this issue.

**Comment by chris-miaskowski** [comment]
Got it @lottamusm, that's great! I'd like to add it to our regression testing suite for posterity anyway. Feel free to send me the testing details here or on our chat.
