### ISSUE TITLE
Author name and email must be specified as an argument or in the .git/config file.

### ISSUE THREAD

**Issue by ra-coder** [stoplightio/studio#200]
Have 

"Author name and email must be specified as an argument or in the .git/config file."

when trying to commit from studio

**Comment by john-doe-2016** [comment]
Hi,

It happens to me sometimes too, when I have been logged in too long or something like that.
Disconnecting and logging again does not solve the problem.

The only workaround I found was :
- save the API description in a file by accessing the 'write' view
- remove the project and clone/open it again
- paste the copied text over the last commit one that has been gotten when recreating the project.

**Comment by ra-coder** [comment]
One more work around: 
1) save progress somewhere else 
2)'Clean site data' in browser console, 
3) relogin

**Comment by philsturgeon** [comment]
Here there! Thanks for the bug report and for suggesting some workarounds, this can give us some hints at figuring out what is going on. 

We actually spotted this bug ourselves the same day you reported it, here are some images we had internally.

![image](https://user-images.githubusercontent.com/67381/67251930-27ef8080-f471-11e9-89ca-4c4e437be9d4.png)

![image](https://user-images.githubusercontent.com/67381/67251963-4786a900-f471-11e9-9680-58ee006f78e6.png)

**Comment by philsturgeon** [comment]
If this is still happening let us know, but I feel like we sorted it out.
