### ISSUE TITLE
Desktop > How does Studio work with HTTP/S proxies?

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#201]
### User Story

As a user that requires routing traffic through a HTTP proxy in order to connect to the Internet, I need to be able to configure Studio desktop such that it communicates with external HTTP services through a proxy, as opposed to connecting directly.

Studio Desktop <---> Proxy <---> Server

### Other Information

I was able to find [this](https://electronjs.org/docs/api/session#sessetproxyconfig-callback) in the Electron docs around configuring proxies, not sure if that's helpful or not though.

Currently it's not clear what the support for HTTP proxies is within Studio desktop. Is the typical `HTTP_PROXY` environment variable supported? It doesn't seem like it from some initial testing, so we need to identify what the correct approach to proxying is. 

Note this isn't so much about adding settings to Studio's interface for configuring a proxy, but more about documenting how someone should be able to configure a proxy should they need to.

**Comment by philsturgeon** [comment]
@rossmcdonald could we get some "As an enterprise user working within a corporate environment, I need Studio Desktop to support Proxy config so I can..." or whatever style user stories? This could mean a few things otherwise, like... maybe this is for the platform version itself? What was requested by who and how :D

**Comment by rossmcdonald** [comment]
@philsturgeon I've updated the description with a user story and a little more info. Also this is specifically for the Studio desktop application. There's a separate issue for the platform as a whole.

**Comment by srbarba** [comment]
Any update on this issue?

**Comment by philsturgeon** [comment]
I've moved this feature request, and all related requests, over to our roadmap. If you're interested in getting this done, please register your interest on the roadmap card: https://roadmap.stoplight.io/c/135-using-studio-desktop-behind-a-proxy

Pop your email address in there when you register interest and you'll get an update on when this is done. 🙌
