### ISSUE TITLE
OAS3 Path Item cannot use $ref despite being valid

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#202]
For example, within an OpenAPIv3 specification:

```json
{
  "paths": {
    "/some/path": {
      "$ref": "./paths/some-path.json"
    },
    ...
  }
}
```

It should display properly in the Forms view as if it was inline to the description file.

**Comment by philsturgeon** [comment]
I had to double check this one, as $ref is only allowed in certain places! 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/67381/67252307-a698ed80-f472-11e9-8c25-69582b8ecd4c.png">

but OAS 3.0.x does explicitly allow $ref for a Path Item Object:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/67381/67252341-bc0e1780-f472-11e9-989f-60a60abe3f87.png">

This is possibly a bug, but it is low severity.

**Comment by martinbean** [comment]
Just ran into this issue myself, as I’ve restructured our **openapi.yaml** and split paths into separate files and including them using `$ref`s like this, as it was getting quite big and also causing conflicts in Git with having multiple developers contributing to the spec.

Is there any chance of bumping the priority of this up? As it is part of the spec and think a pretty common use case.

**Comment by philsturgeon** [comment]
Ok I am going to bump it from low to medium seeing as this is feeling a bit more like a bug than a enhancement.

**Comment by josephgardner** [comment]
Same issue with rendering `securitySchemes`. Want a new issue, or does this cover all missing cases?

```
components:
  securitySchemes:
    $ref: ../common/security.v1.yaml#/securitySchemes
```

![image](https://user-images.githubusercontent.com/1297859/72372983-6cd42d80-36d5-11ea-8a21-9aeb7da2c2b0.png)

**Comment by philsturgeon** [comment]
@josephgardner unfortunately that is not valid OpenAPI. Whilst it seems like you should be able to put a $ref wherever you want, you can't. It can only go in places where OAS says you can place a "Reference Object". Check it out https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-scheme-object

Some tooling _will_ just let you $ref wherever, but that's going to cause problems when you use any other tool which follows the OpenAPI spec and cause confusion, like this one. 

This PR is about making Path Items work, because they _are_ allowed to have a Reference Object.

**Comment by josephgardner** [comment]
@philsturgeon I'm actually referring to the components object; every property can be a reference (including `securitySchemes`)

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object

**Comment by philsturgeon** [comment]
Aha! Ok, thanks for clearing that up for me. Let's make a new issue for this.

**Comment by QuentinPetel** [comment]
Same here, consider the following :  

```yaml
paths:
  /messages:
    $ref: "paths/messages.yaml#/paths/~1messages"

  /messages/{uuid}:
    $ref: "paths/messages.yaml#/paths/~1messages~1{uuid}"
```

and the path/messages.yaml : 
```yaml
  /messages:
    get:
      ...
    post:
      ...
  /messages/{uuid}:
    get:
      ...
    put:
      ...
    delete:
      ...
```

No operations are shown neither under the api path list, neither under the path detail. Furthermore, adding an operation to the path should add the code inside path/messages.yaml not inside the root file.

The only solution working for now is to duplicate all API informations (security, servers, etc...) inside each referenced files. Quite unconvenient  in our case with an api containing 300+ endpoints, split in roughly 20 files.

**Comment by svassaux** [comment]
@philsturgeon it's becoming critical: I have an API with only 50 endpoints and my file makes 12k lines
studio desktop is lagging enormously, the working conditions are becoming bad and make us think about choosing another solution.

**Comment by philsturgeon** [comment]
@svassaux I can see how it looks like things have quietened down on the Desktop front but that's the quiet before a v2.0.

In a few days v1.12 will be here fixing a few more bugs, many of which were on our internal tracker and not showing up on the issues list here. 

I'll check with the team where this one is.

**Comment by philsturgeon** [comment]
@svassaux wait why is your file 12k lines? Not being able to have a $ref for a path item does not mean you cannot use $ref... There's loads of ways to break files up with $ref, this is the only one not currently supported.

**Comment by svassaux** [comment]
@philsturgeon I know. You made me doubt I was using things correctly.
I have 
- 123 routes (combinations of paths and methods)
- those routes use 25 models all linked with $ref(s), I never repeat a model
- and I document a lot, I put all details : query parameters, bodies, responses, examples, qualification and description for every parameter, etc.

I would be able to reduce the total size if I used refs for examples but:
- does not seem to work fine with studio desktop
- it's not the best way to organize. Cutting it by paths is suuuuper logical, that's why APIs table of contents are made by paths

I could have you look at our doc if that might help
It's nice to know you're progressing though

**Comment by philsturgeon** [comment]
Cutting it by paths _is_ super logical, I've done things this way in the past. It's coming, we've got a bug we're fixing higher up the foodchain which will clear the way for solving this, and the team are on top of it. 

@lottamus can we add a bunch of tests around `$ref` for shared examples too? The ones that sit in components. That'd solve both of the issues for @svassaux!

**Comment by pytlesk4** [comment]
It's been a long time coming, but we have a fix for this issue that will be deployed in the next day or two. Here is a preview though.

Notice that there are no errors from Spectral, refs are rendered correctly in Docs, Explorer, Prism works well with them too, and a bunch of other fixes. We can't wait to get this out to you guys!

Here's the [sample repo](https://github.com/pytlesk4/bear-cave) that I am using, it's public, feel free to fork it and load it up in Stoplight.

![2020-06-26 11 03 45](https://user-images.githubusercontent.com/2294309/85877874-704c0480-b79d-11ea-93b9-451ec003eb10.gif)

*Note: I am referencing a path item object in an OAS 2 File, this will work the same for OAS 3 as well*

**Comment by pytlesk4** [comment]
Might have jumped the gun here, we haven't added support in the form editor in Studio for these kinds of refs just yet.

**Comment by svassaux** [comment]
@pytlesk4 when will the form support be available? it's quite necessary ;)
also did you optimize how the parsing is done? stoplight studio desktop is currently using a loooooot of resources

![image](https://user-images.githubusercontent.com/9137903/88679102-65172c00-d0ef-11ea-81c2-c6ce997e8bc3.png)
here when idle...

**Comment by philsturgeon** [comment]
Don’t worry about performance, Studio Desktop v2.0 has done a lot of work in this area and should be much better. 

Let’s call this one done for now because we’ve got plenty of other issues for generally making more components be $ref able in the Form view. #297 for one.
