### ISSUE TITLE
Be able to create a model skeleton by a sample

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#204]
As an API designer, I sometimes have to retro-document existing API, or create new objects from existing ones. So it would be useful to be able to create a model from a pasted sample.

Sometimes, copying and pasting an existing or quickly mocked object may be quicker than using the form view or 'write' view to create one.

**Comment by philsturgeon** [comment]
@john-doe-2016 absolutely, this work is planned, and being tracked under #159.

**Comment by john-doe-2016** [comment]
Hi @philsturgeon ,

Great!
Thank you

Best regards
