### ISSUE TITLE
Generate the whole documentation in a single document/page

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#205]
As a {user_type}, I can do {some_user_action}, so that I can {some_user_value}.
As an API designer, I can generated the whole documentation (PDF or something like that or web page with the full documentation without navigation pane) so that I can send it to some users or publish it on an internal portal.

I sometimes have to send the API specification validators, or publish it for users, and it would be great to be able to generate a document with the whole API, instead of having them access the online documentation and parse it item by item.
It could be a web page with all the items ; one could then be able to save it from the web browser.

**Comment by philsturgeon** [comment]
Good idea, and we agree! This will be partially added with a bundled Export (#126) and done entirely as part of this roadmap item: https://stoplightio.productboard.com/portal/1-stoplight/tabs/a94f0d10-ec61-4adf-ab29-852fb8acb57a/features/2612807/detail/expanded

@lottamus does this one have a GitHub issue? Couldn't find it. ☝️

**Comment by john-doe-2016** [comment]
Great !

**Comment by lottamus** [comment]
> done entirely as part of this roadmap item

@philsturgeon that share mechanism is meant to be more of a "readonly" view of Studio that is built for quick iteration and internal collaboration as opposed to pretty documentation that is shared after the design has been finalized.

Though I do agree we should have a "single" page API docs view similar to what we had on api-docs (https://npr.api-docs.io/2.0/authorization/get-authorization-page) where each endpoint is stacked on top of each other and the sidebar items highlight as you scroll down. This would be pretty simple for us to add into the new system. @john-doe-2016 would something like that work for your use-case?

**Comment by john-doe-2016** [comment]
Hi @lottamus ,

Yes it would, since I just would have to print the page as PDF to get what I need.

By the way, it was one of my suggestions: it seemed to me easier for you to alter your current doc generation to "stack" all the informations that implement a PDF or something like that generation system.

Thank you guys!

**Comment by john-doe-2016** [comment]
I've just clicked on your link, and the document is still partitioned by tags & model, but it would still be an improvement since I could save by parts.
The original idea was the same as in your link, but with a single document/section.

Thanks again for your great work.

**Comment by philsturgeon** [comment]
With v2 nearly out, share on its way, export + bundling done, this has to have been partially solved at least - and if not now then v2 will :D
