### ISSUE TITLE
Docs: anchor links are being generated incorrectly

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#208]
The example below should be linking to https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/03-stoplight-flavored-markdown.md#video but isn't including the current file path.

![image](https://user-images.githubusercontent.com/7423098/67296238-cd284a00-f4ad-11e9-844a-83f6d530de5e.png)

We need to add another condition [here](https://github.com/stoplightio/platform-internal/blob/2316acf0423bc260ffab28caa127a0ed85689c13/packages/frontend/components/Docs/Provider.tsx#L97) that checks if the link is an anchor (starts with a #) then render a regular link:

```html
<a className={className} href={url}>{children}</a>
```

**Comment by philsturgeon** [comment]
Fixed by @paulatulis in v1.6.0.
