### ISSUE TITLE
Require login to use git features

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#21]
**Chore summary**

Studio users are required to login (to Stoplight) and connect their vcs account before they can access any git features.

**Tasks**

- [ ] Remove area to add personal access token
- [ ] Pass user's login token to the API instead of their personal access token. You can assume the API will handle looking up the user's vcs oauth token and pass it along.

**Comment by wmhilton** [comment]
Is this for Desktop and Web or just Desktop?

**Comment by wmhilton** [comment]
How will this affect users who aren't using Github? Will it work with Bitbucket and Gitlab?

**Comment by lottamus** [comment]
> Is this for Desktop and Web or just Desktop?

Both Desktop and Web

> How will this affect users who aren't using Github? Will it work with Bitbucket and Gitlab?

Login via Github, Gitlab, and Bitbucket cloud will be supported by our hosted Platform. Enterprise vcs users will need to use our enterprise Platform installation.
