### ISSUE TITLE
Certain JSON schema-like objects are not recognized

### ISSUE THREAD

**Issue by P0lip** [stoplightio/studio#211]
**Describe the bug**
Studio does its best to recognize JSON Schema models with missing `$schema`.
Unfortunately, it does recognize 'complex' types properly.

**To Reproduce**
1. Given the following JSON Schema-like object
```yaml
type: [object, string]
properties:
  id:
    type: string
```
2. Studio treats it as a regular file.

**Additional context**
Spotted this when working on models importing. 
I revisited the G. code, because I wanted to re-export the schema detection util and noticed the issue.

**Comment by marbemac** [comment]
@P0lip move over to qa pipeline once it's in studio please.

**Comment by StoplightDeb** [comment]
@P0lip - is this testable by just pasting your example into the `write` view when making a model?  What should we be looking for. and is there anything specific that needs to be done for testing this?
Cc: @chris-miaskowski

**Comment by P0lip** [comment]
> @P0lip - is this testable by just pasting your example into the write view when making a model? What should we be looking for. and is there anything specific that needs to be done for testing this?

You can have a existing model somewhere in the project you clone, for instance.
The model must have a "complex" type, i.e.
```yaml
type: [number, string]
```
To reproduce, just create such a file (either in file explorer in your OS, or in the repo, or via Studio) and paste the following content and obviously save or commit & push.
```yaml
type: [object, string]
properties:
  id:
    type: string
```

Then, in Studio, open the file in Studio and see that it's not recognized as json schema model and hence missing in APIs tree and have no icon / form associated.
LMK if that helps!

**Comment by stoplightAutomaton** [comment]
Thanks for the elaboration, this looks good on staging!
