### ISSUE TITLE
Bug in Studio Read view with self referencing objects

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#212]
If I define an object like this:
```yaml
definitions:
  Node:
    type: object
    description: Represent a node of the tree.
    properties:
      nodeId:
        type: number
        description: 'Identifier of the organization, same as in the Organization structure'
      children:
        type: array
        items:
          $ref: '#/definitions/ORIGIN.OrganizationNode'
```
There is an error in the generated documentation in Studio ('Read' view):
![image](https://user-images.githubusercontent.com/20415788/67406156-00560080-f5b6-11e9-8fec-8ba541a529ed.png)

The web site generated docs seems unaffected.

**Comment by philsturgeon** [comment]
Confirmed in v1.10.0.

<img width="1106" alt="Screen Shot 2020-03-04 at 2 56 17 PM" src="https://user-images.githubusercontent.com/67381/75887064-823e1c00-5e29-11ea-9bd9-a1239fcad990.png">

**Comment by philsturgeon** [comment]
This example was pointing to some definition with Node in the name, not actually a self referencing object, but self referencing objects work great. 

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/67381/95346242-e6432a00-08bb-11eb-90d1-29217cc0b5be.png">

**Comment by john-doe-2016** [comment]
Hi,

My sample and problem was actually with a self referencing object, see description ;).
Nevertheless, it does seems to be actually no more present in the latest release.
Thank you
