### ISSUE TITLE
Add ability to open and edit multiple files at once

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#213]
As a designer I want to have multiple files open simultaneously so I'm able to quickly navigate between files being actively edited. Same concept as tabs in Chrome and other browsers.

**Comment by philsturgeon** [comment]
I struggle editing a .spectral.yml and flipping back to the API I am testing the results of that YAML on. It's a bit easier with the new API fitlered tree showing the files above but in big repos with a lot of files it can be a pain in the backside.

**Comment by akrabat** [comment]
I really would like the ability to see two separate API projects in separate windows side by side!

**Comment by philsturgeon** [comment]
Moving this feature request over to the roadmap, thanks all! 

https://roadmap.stoplight.io/c/152-edit-multiple-files-in-tabs
