### ISSUE TITLE
Move Explorer Search Spinner

### ISSUE THREAD

**Issue by aglensmith** [stoplightio/studio#214]
**User story.**
As an Explorer User, I would like to know if search results are still loading without scrolling down to see the loading spinner

**Describe the solution you'd like**
Move the spinner animation to the top of the results instead of the bottom where it currently is; or overlay the spinner over the page. Another option would be to put the spinner inside or near the search input  box. 

**Additional context**
The issue with the spinner at the bottom might only be evident orgs with lots of repositories loaded in explorer and with large search result sets.

**Comment by philsturgeon** [comment]
Loads of UI work has been done for v2 which is on its way, so please give us feedback on the new version when you get to play with it. :)
