### ISSUE TITLE
[Feature] Auto parse json schema

### ISSUE THREAD

**Issue by Lizhooh** [stoplightio/studio#219]
**User story.**
Auto parse json schema

**Is your feature request related to a problem?**
I want to have a `import json` function in response.
When I import a piece of json data, the app can automatically recognize the json model.

E.g: 

import json data:

```js 
{
    "userName": "abc",
    "userAge": 20
}
```

Automatic parsing of data models, out:

```js 
schema:
    type: object
    properties:
        userName:
            type: string
        userAge:
            type: number
```

**Describe the solution you'd like**

**Additional context**

**Comment by philsturgeon** [comment]
Hey @Lizhooh, we have an issue for this feature over here: https://github.com/stoplightio/studio/issues/159 Subscribe for updates!
