### ISSUE TITLE
(OAS2) Form View does not add x-deprecated to document

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#223]
**Describe the bug**

Flipping the Deprecated? toggle on does not modify the description document in any way.

**To Reproduce**

Open an OAS2 document and set a response schema to whatever, add a property and mark it as deprecated through the Forms View.

<img width="976" alt="image" src="https://user-images.githubusercontent.com/67381/67727260-05b5af80-f9e9-11e9-9930-db1820444e38.png">

Switch to Write view and see there is no mention of anything about deprecation.

```
  /listRecurringDetails:
    post:
      summary: Retrieves stored payment details for a shopper.
      description: Foo
      x-groupName: General
      x-sortIndex: 1
      parameters:
        - name: request
          in: body
          schema:
            $ref: '#/definitions/RecurringDetailsRequest'
        - type: string
          in: header
      responses:
        '200':
          description: OK - the request has succeeded.
          schema:
            type:
              - 'null'
              - number
          headers:
            header-0:
              type: string
        '400':
          description: Bad Request - a problem reading or understanding the request.
        '401':
          description: Unauthorized - authentication required.
        '403':
          description: Forbidden - insufficient permissions to process the request.
        '422':
          description: Unprocessable Entity - a request validation error.
        '500':
          description: Internal Server Error - the server could not process the request.
      security:
        - API Key - 1: []
```

**Expected behavior**
There is no `deprecated` keyword in OAS2, that was added in OAS3, but we can use the popular vendor extension `x-deprecated`.

**Comment by mallachari** [comment]
@philsturgeon could you verified that again? I can see that current version already adds deprecated keyword both to oas2 and oas3 schema definitions.

![Screenshot from 2019-12-06 19-16-29.png](https://images.zenhubusercontent.com/5d3eb13f99357a3001f5f485/03eaa1a9-2da8-4ab0-81c4-be46849a2dd9)![Screenshot from 2019-12-06 19-29-04.png](https://images.zenhubusercontent.com/5d3eb13f99357a3001f5f485/19010b09-bdcd-4b4f-b2fb-7f0951cf561f)

I'm assuming that this is what you want here, just using `x-deprecated` in oas2 case, right?

**Comment by philsturgeon** [comment]
Response schema will contain `deprecated` yes, maybe all schemas, but "parameters" do not, including the request body - which is a parameter in OAS2.

<img width="557" alt="Screen Shot 2019-12-06 at 17 04 53" src="https://user-images.githubusercontent.com/67381/70337132-c9c50400-184a-11ea-9c90-b546ddddfffb.png">

<img width="963" alt="Screen Shot 2019-12-06 at 17 04 44" src="https://user-images.githubusercontent.com/67381/70337131-c92c6d80-184a-11ea-8ba4-ea8404025ce7.png">

A second problem related to this: If you check the 2.0 specification, the _only_ place a `deprecated: true/false` is permitted is on the [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object). 

Not in the schema object, not in a parameter object, nowhere other than an operation. A common convention used by many tools is to use `x-deprecated` to support it in other places, like the places OAS3 supports it.

**Comment by mallachari** [comment]
I get the issue with forbidden `deprecated` key in oas2 (checked specification before) so we can try using `x-deprecated` here.

Regarding the current state of how JSE works, all schemas (if set) contain `deprecated` prop (request, response) regardless of being part of `parameters` or not. Here's example with oas2 body:
![Screenshot from 2019-12-07 01-24-07.png](https://images.zenhubusercontent.com/5d3eb13f99357a3001f5f485/f1815c49-d833-45c2-834b-7e969c86ab67)

Other parameters (path, param, query) don't have deprecated option in their validations.

Is there something I am missing?

**Comment by marbemac** [comment]
- OpenAPI v2
  - at the operation level: `deprecated` property
  - schemas anywhere else: `x-deprecated` property. NOTE this might require a new option in JSE to control wether `x-deprecated` or `deprecated` is used? Ideally it's not hardcoded for this specific use case, but a little bit more generic so that we can leverage the option(s) for other properties that might differ depending on context JSE is being used.
- OpenAPI v3
  - at the operation level: `deprecated` property
  - schemas anywhere else: `deprecated` property

Does that help?

**Comment by mallachari** [comment]
Yup, that's clear, we've talked about that with Phil last week. 
There are two issues within this one:
- additional properties don't support multi types - I've already fixed it within https://github.com/stoplightio/studio/issues/237
- using custom JSE props - I've added optional `spec` property for JSE store that is used in transformer to obtain correct schema. So far just `x-deprecated` but we can extend it to other props if needed. PR here https://github.com/stoplightio/json-schema-editor/pull/54. To make it work in studio: `spec` should be passed to JSE store. I'll update it there once this one gets merged.

**Comment by chris-miaskowski** [comment]
Approving. Steps to repro and expectations:

- create oas2 api file
- add a path
- add response body to that path and make it deprecated (via forms)
- add request json body and deprecate it
- go to write view
- expect `x-deprecated` keyword added at schema level
```yaml
paths:
  /path:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            x-deprecated: true
          headers: {}
      operationId: get-ath
      parameters:
        - in: body
          name: body
          schema:
            type: object
            x-deprecated: true
definitions: {}
```

@marbemac @mallachari 

> at the operation level: deprecated property

I don't think we have a way to deprecate an entire operation from UI, right?
Does the above steps sound good?

**Comment by mmiask** [comment]
Created/modified test cases in TR:
https://stoplight.testrail.io/index.php?/cases/view/5307
https://stoplight.testrail.io/index.php?/cases/view/8203
