### ISSUE TITLE
Reopening an API from a Github Repo doesn't reload Models

### ISSUE THREAD

**Issue by edwade** [stoplightio/studio#227]
**Describe the bug**
Created a github repo, created an API and started documenting it, including using models on the API using Stoplight Studio on Ubuntu 19.10. Pushed the changes to Github from the desktop app. Tried to reopen the API from the Github link and all the files are pulled down and the "Paths" section is repopulated however the "Models" section is empty.

**To Reproduce**

1. Create a new API using Stoplight Studio on Ubuntu 19.10, including some models.
2. Push the API files to Github
3. Close the app
4. Reopen the app and reopen the project

**Expected behavior**
Reopening the app and the project should repopulate the "Models" section of the client

**Screenshots**
![File Explorer](https://user-images.githubusercontent.com/53229233/67940810-4cafca80-fbcc-11e9-83bc-076a5d521c64.jpg)
![API Overview](https://user-images.githubusercontent.com/53229233/67940812-4de0f780-fbcc-11e9-8790-d454dc7fd1b3.jpg)

**Environment (remove any that are not applicable):**
 - Studio version: 1.4.0
 - OS: Ubuntu 19.10 (Eoan Ermine)
 - Browser: Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by philsturgeon** [comment]
We've done a whole load of work since October but some of these issues didn't get closed down at the time, sorry about that. Better processes in place now. If this is still causing trouble let us know and we can reopen.
