### ISSUE TITLE
Endpoints with path "/" do not display in API sidebar

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#228]
### To Reproduce

- Create an endpoint with path "/"

### Expected Results

To see a "/" path in API sidebar.

### Actual Results

![image](https://user-images.githubusercontent.com/4060903/67957634-e8890880-fbc3-11e9-9a79-42969a919139.png)

**Comment by philsturgeon** [comment]
Done by @P0lip in v1.6.0!
