### ISSUE TITLE
Studio -> Login: Add ability to login from Studio 

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/studio#23]
User Story

As Modeling Melvin I can log in to the platform from Studio Desktop.

NOTE: this is a similar approach to how we handled login with github in the next desktop app.

In Scope

UI support for logging in with oauth providers (GitHub, GitLab etc)
Acceptance Criteria and Scope

Users can log in from Studio Desktop via a login button in top right
Login button opens up new electron window that displays the login/register platform page (should respect the studio stoplight host setting).
Upon logging in / registering, electron window is closed and session information is passed back for use in main studio window.
If logged in, user details such as id are passed to pendo / any other analytics products that we are leveraging inside of Studio.

**Comment by lottamus** [comment]
Closed by https://github.com/stoplightio/studio-internal/pull/395
