### ISSUE TITLE
Toggle Word Wrap

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#230]
**User story.**
As a user used to working in editors like VS Code, I am used to having word wrap easily switchable. Maybe I turn it on for markdown content, and turn it off for code. Either way it should wrap at a noticeable ruler so i can see why something has jumped to another lane. 

**Is your feature request related to a problem?**
Code is wrapping at a funny point, no ruler shows up, and there is plenty more space on the screen it could have used. 

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/67381/68050144-d3f06180-fce4-11e9-916e-2834314ba70c.png">

**Describe the solution you'd like**

<img width="254" alt="image" src="https://user-images.githubusercontent.com/67381/68050177-e1a5e700-fce4-11e9-8e7c-195f2b9a0f94.png">

**Comment by BigBlueHat** [comment]
Currently Stoplight is rewriting all our wrapped description content from folded block scalar style using `>` into very long single line single-quoted strings.

I've not found a setting in Studio or Spectral to prevent this rewriting, but would love to be able to keep Spectral consistent with our preferred output.

Thanks!

**Comment by philsturgeon** [comment]
Let's discuss this on #299 because the word wrapping being discussed here is a visual effect, butit seems like you're talking about YAML rewriting.

**Comment by philsturgeon** [comment]
Feature requests are being tracked on roadmap.stoplight.io so I'll close this old one down.
