### ISSUE TITLE
$ref drop down does not include all Models

### ISSUE THREAD

**Issue by charlesritchea** [stoplightio/studio#233]
**Describe the bug**
I'm unable to choose one of my models as a $ref 

**To Reproduce**

1. Create a bunch of different models. I had Asset, Job, Project, Step, Subscription, Transaction
1. Create a Job model with a subscription field of type $ref
1. Create a Subscription model
1. Click on Job `subscription: $ref` and try to set `$REF TARGET` to `#/components/schemas/Subscription`

**Expected behavior**
`#/components/schemas/Subscription` will be an option in the drop-down menu

**Screenshots**
![image](https://user-images.githubusercontent.com/1656349/68158618-fa4d1180-ff1d-11e9-9907-035c3ed2b27d.png)

**Environment (remove any that are not applicable):**
 - OS: Ubuntu 19.10
 - Browser: Chrome 78.0.3904.87

**Comment by charlesritchea** [comment]
Notice that a deleted model `Bar` _is_ included in the drop down instead

**Comment by philsturgeon** [comment]
@charlesritchea this has been fixed internally, and deployed so it's part of Studio Web. It'll be available in the next Studio Desktop release, which is usually monthly. Thanks for reporting this and making Stoplight better!
