### ISSUE TITLE
Allow to duplicate a path by a simple right click

### ISSUE THREAD

**Issue by benjdl** [stoplightio/studio#235]
**User story.**
As a user, I can right click on a path and select the "Duplicate" option, so that a popup window opens and let me choose which operation to duplicate (checkbox style: get, post,...) along an input field to save the new path name.

**Is your feature request related to a problem?**
Huge time-saving feature.

**Describe the solution you'd like**
Described in the user story.

Thanks!

**Comment by philsturgeon** [comment]
Moved to productboard, thank you!
