### ISSUE TITLE
Additional properties modal does not support multiple types well

### ISSUE THREAD

**Issue by P0lip** [stoplightio/studio#237]
Found when fixing https://github.com/stoplightio/studio/issues/207

STR:
- create a model
- set more than one primitive type, i.e. number and string
- open additional properties
- try to set some values

**Comment by StoplightDeb** [comment]
Checked on staging, validation/additional properties can now be added if more than one type is selected 👍

**Comment by mmiask** [comment]
Added a new test to TR.
https://stoplight.testrail.io/index.php?/cases/view/8198
