### ISSUE TITLE
Have the parameters constraints in description in reading mode and generated doc

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#240]
As a designer, reviewer or developer, I want to be able to see the query parameters contraints/validation when in reading mode or in the generated documentation.

At the moment, the only solution to see those (default or max value, ...) is to switch to form mode (and click the button) or directly access the source file.
I do feel that it somehow negates the use of the reading pane / documentation to not have everything needed to wholly understand the API specification. By the way, I just had a developer that made a mistake because of it ;).

They could be added under the parameter description, or under the parameter name (like OPTIONAL, REQUIRED, ...).

**Comment by chris-miaskowski** [comment]
Just verified on our pre-release environment and all looks good! Good job @ssspear! 

![preview-validations.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/88f25c18-802f-4638-8621-0ccbce2ff37e)

**Comment by StoplightDeb** [comment]
@chris-miaskowski - this is covered in API Operation Form in TR for Studio. I think we can count those for these cases.

**Comment by john-doe-2016** [comment]
Hi @lottamus and all,

This is a good improvement, thanks!

But, if I may: the problem with this implementation is that those parameters are not seen if we chose to 'print' the web page to distribute or publish the generated documentation. I understand your concern not to take too much place on screen though.

Regards
