### ISSUE TITLE
Unable to create files in project

### ISSUE THREAD

**Issue by marcoferrer** [stoplightio/studio#241]
**Describe the bug**
Unable to create files in project when user home directory contains a `.` character

**To Reproduce**
1. Login to macos as user whos name contains `.`
2. Install stoplight studio
3. Perform any of the following
    * Create new local project
    * Open git project
    * Open existing project from directory within user home
4. Create new file

**Expected behavior**
File is created

**Screenshots**
![image](https://user-images.githubusercontent.com/35935108/68407116-05d44e80-0151-11ea-9cf2-e8606acc42fc.png)

**Environment (remove any that are not applicable):**
 - Studio version:  1.4.2 
 - OS: macOS Mojave 10.14.6

**Comment by P0lip** [comment]
The fix should be included in the next patch release.

**Comment by StoplightDeb** [comment]
Looks good on staging.
