### ISSUE TITLE
TryIt should support switching servers

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#242]
**User story.**
As a Studio and Docs user, I can select from a list servers defined in the openapi document, so that I can send a request to that server.

**Is your feature request related to a problem?**
Currently there is no way to change servers in the TryIt section.

**Describe the solution you'd like**
There should be a dropdown next to the path input that includes all of the servers defined in the openapi document.

**Additional context**

![image](https://user-images.githubusercontent.com/7423098/68407699-a45cb180-0149-11ea-9f35-88bb58b2c62d.png)

**Comment by lottamus** [comment]
Implementation is done and will be included in Studio & Platform v1.5.0 👍

**Comment by StoplightDeb** [comment]
Looks good on desktop & web, closing this! thanks @lottamus (it looks like I'm saying "thanks a lot tamus" which I also feel.
