### ISSUE TITLE
Add better error messaging for failed $ref resolving

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#243]
**User story.**
As a user, I can see $ref resolving errors in the Spectral, so that I can quickly identify and fix them.

**Is your feature request related to a problem?**
If I miss-type or add an incorrect $ref, it is identified in the Spectral panel but doesn't have a very helpful error message.

**Describe the solution you'd like**
Add a better error message that includes the $ref and maybe even the response message / status text.

For example if the $ref failed to resolve because of a 401, the message could say: 

`Received "401 Unauthorized" when resolving $ref "https://example.com"`

**Additional context**
![image](https://user-images.githubusercontent.com/7423098/68419447-d973fe80-015f-11ea-966f-8756e0d608be.png)

**Comment by philsturgeon** [comment]
@P0lip did this get worked on recently? It seems familiar.

**Comment by P0lip** [comment]
@philsturgeon nah, unfortunately we haven't improved it yet.
We'd need to do it in json-ref-readers over here https://github.com/stoplightio/json-ref-readers/blob/master/src/http.ts#L5.

Something like
```ts
if (!response.ok) {
  throw new Error(response.statusText); 
}
```
should be sufficient I believe unless we also want to include the status code

**Comment by philsturgeon** [comment]
If we can explain "could not load file "dkfjfhskdf" due to HTTP 500 Internal Server Error" that would be better. Just saying "Forbidden" or "Not Found" would be a little vague I think.

**Comment by chris-miaskowski** [comment]
Confirmed and updated regression tests.
