### ISSUE TITLE
Creating a new file should use version and format from the file name

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#245]
**Describe the bug**
I am trying to create another version of my user model using the context menu add.

**To Reproduce**

1. Create a project with "user.v1.json" model
2. Right click and add a new "JSON schema (JSON)"
3. Enter the text "user.v2.json"
4. Notice the result is "user-v2-json.v1.json"

**Expected behavior**
I expect the new file creation to respect the version and format that I am passing in and the result to be "user.v2.json".

**Screenshots**
![2019-11-13 09 27 40](https://user-images.githubusercontent.com/7423098/68778150-61428880-05f8-11ea-8d1d-439fbad14990.gif)

**Comment by chris-miaskowski** [comment]
All good!
