### ISSUE TITLE
Cannot type "s" or "f" when making new file

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#247]
Trying to make a new model in studio desktop in the studio-demo repo. I can type most characters fine, but it will not let me type "s" or "f" for some reason.

![Screen Recording 2019-11-14 at 13 35 31](https://user-images.githubusercontent.com/67381/68861928-709f0000-06e4-11ea-937a-c580b5e90f36.gif)

OS X, Studio Desktop v1.5.0.

**Comment by P0lip** [comment]
This must be a platform thing, since it works fine on my end.
IIRC there was an issue reported by @rossmcdonald back in a day where certain key presses were ignored while the screen was being recorded.
https://github.com/stoplightio/studio/issues/87 - sounds like the case you are facing?

**Comment by rossmcdonald** [comment]
Yeah, sounds exactly what happens to me when recording the screen. I have to refresh the screen in order to use those keys. @philsturgeon Does refreshing fix it?

**Comment by philsturgeon** [comment]
Ok, phew. I was trying to record another issue when I came across this, so if screen recording is a known issue we can consider this one sorted.
