### ISSUE TITLE
Remove HTTP Method button is hard to find

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#248]
**User story.**
As a Studio user who is unfamiliar with YAML, I want to remove a method (e.g. POST) from an operation, but the UI does not make it clear how I can do that. I'd rather not resort to editing the YAML.

**Is your feature request related to a problem?**
User reported being unable to remove a method. There used to be a button up top next to the Tags option, but at some point it was removed. The only place this can be done other than editing JSON/YAML is by selecting an operation and right clicking it when its active:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/67381/68958967-12961980-07c5-11ea-82f2-e2553dd44cb8.png">

This is not entirely clear, and if you try right clicking another method than the one which is active, it will not show you the "Delete FOO Operation".

**Describe the solution you'd like**
Right click delete would be a start, but a UI expert would have better ideas.

**Comment by lottamus** [comment]
It used to be in the header but looks like that got removed. You can get to it via the context menu now.

I suggest we use this issue to find a place for the remove button. Either adding it back to the header or as a section at the bottom of the forms

<img width="975" alt="Stoplight_Studio_and_Unclear_how_to_remove_a_method_from_an_operation_·_Issue__248_·_stoplightio_studio" src="https://user-images.githubusercontent.com/7423098/68957972-c4ffb980-0790-11ea-980c-f80365991478.png">
