### ISSUE TITLE
Local root JSON pointers are not resolved correctly

### ISSUE THREAD

**Issue by P0lip** [stoplightio/studio#253]
**Describe the bug**
Any root pointer `#` cannot be resolved, result in an error displayed in the diagnostics panel

**To Reproduce**

1. Clone https://github.com/adidas/api-guidelines
2. Checkout branch [this PR](https://github.com/adidas/api-guidelines/pull/22/) was based on
3. Open `.spectral.yml`

**Expected behavior**
Ref is resolved correctly.

**Comment by philsturgeon** [comment]
@P0lip can you grab the exact example in case api-guidelines changes and we can't reroduce it anymore?

**Comment by P0lip** [comment]
I've extracted the example over here https://github.com/stoplightio/json-ref-resolver/pull/146/ (see tests).
Moreover, added an extra test case I wasn't sure we handled properly.

**Comment by StoplightDeb** [comment]
@P0lip - thank you for clarifying this one, looks good on staging (no issues)
