### ISSUE TITLE
OAS2 - Add a consumes when JSON Request body is added

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/studio#254]
When adding a JSON Request, if there is no consumes defined globally for an OAS2 spec, add one. 

When adding a JSON Response if there is no produces defined globally for an OAS2 spec, add one.

**Expected behavior**

When there is no consumes defined, but a JSON request body is added, Studio should add a new consumes keyword. 

```
"paths": {
    "/foo": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {},
        "operationId": "get-foo",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "properties": {
                "foo": {
                  "type": "string"
                }
              }
            }
          }
        ]
      }
    }
  },
  "consumes": [
    "application/json"
  ]
```

Currently it does not do that. http-spec doesn't care, but it could confuse other tooling outside of Stoplight.

**Comment by marbemac** [comment]
Similar to #255 - seems like both an enhancement and a bug here. We should handle no consumes gracefully in read panel, explorer, try it, etc. Auto managing he consumes property for end user should be handled as a separate enhancement imho.

**Comment by philsturgeon** [comment]
If we've not got to this yet I doubt we will. Let's focus on making OAS3.1 awesome and helping people migrate.
