### ISSUE TITLE
Adding a response to a OAS 2 Operation, should add a produces if not defined

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/studio#255]
**Describe the bug**
When adding a Response to an OAS 2 operation, if produces isn't defined, then add produces with the correct content type to the OAS 2 operation.

**To Reproduce**

1. Create a new OAS 2 document.
2. Create a GET Operation, add a 200 response, with a description and schema
3. View preview, and notice that the description and schema for the 200 response aren't displayed.

**Expected behavior**
I would expect the description and schema to get rendered properly.

**Screenshots**

<img width="1993" alt="image" src="https://user-images.githubusercontent.com/2294309/69590613-a762f900-0fb5-11ea-98ce-331feaf0c483.png">

**Additional context**
~`http-spec` should default to something if a user uploads a bad spec.~ http-spec doesn't care. -- Phil

**Related**
https://github.com/stoplightio/studio/issues/254

**Comment by marbemac** [comment]
Seem to be conflicting issues here. One is more of an enhancement (auto add produces), and one is a clear bug where response description property is not being rendered in the read panel.

Regarding the former, I think trying to auto manage the produces property is more trouble than it’s worth. Can’t add it when response is added - have to wait until response example is added? And then try to detect wethers it’s json or plain text or yaml etc. And then see if the value is present in global produces and if not add to operation. Sounds non trivial and prone to error, for not much benefit imho. What do you think?

**Comment by philsturgeon** [comment]
I think http-spec has better defaults now, right @XVincentX? Is this still an issue? https://github.com/stoplightio/studio/issues/254 is related.

**Comment by XVincentX** [comment]
Http Spec can work without this effectively. In such case Prism will return whatever response is defined. Still it would be good if Studio could add a reasonable default trying to understand the content type of such operation.

**Comment by philsturgeon** [comment]
Ok I think this is done then, the concern is about spec rendering but prism and docs are fine.
