### ISSUE TITLE
See response model in view and documentation

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#256]
As a reviewer or developer, I want to see the model (if any) of the returned response, and/or be able to navigate to it (to see samples for example).

At the moment, only an "anonymous" object is seen in view or documentation and it does not help understanding shared objects or the structure of the sample (through examples for example):
![image](https://user-images.githubusercontent.com/20415788/69722167-b7461e80-1116-11ea-8db0-77ac4134e2e4.png)
Even if it is an reference to a model
![image](https://user-images.githubusercontent.com/20415788/69722192-cc22b200-1116-11ea-9ba5-5c00cb84dd29.png)
And this model has a sample to help apprehend it
![image](https://user-images.githubusercontent.com/20415788/69722372-33406680-1117-11ea-9d7d-89b21cd42ba6.png)

I think the model should be indicated if any, and one should be able to either access the model details through navigation (links), or access it (tab like in edition).

**Comment by philsturgeon** [comment]
You got it, this is being sorted out in our upcoming documentation facelift. https://stoplight.io/open-source/elements/
