### ISSUE TITLE
Removing API does not remove directory from drive

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/studio#26]
**Describe the bug**

When I delete existing API I would expect the related folder to be removed. It's not.

**To Reproduce**

1. Create an API in Studio
2. Go to the `APIs` tab in tree list 
3. Right click on the API created
4. `Delete`
5. Go to the `Files` tab
6. Observe directories

**Expected behavior**

API directory should be deleted

**Actual**

It's not deleted (but its contents are)

**Environment (remove any that are not applicable):**
Studio v1.0.0-beta.8

**Comment by P0lip** [comment]
@chris-miaskowski 
I noticed the same today and fixed it.
