### ISSUE TITLE
Project is created even though cloning fails

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#260]
**Describe the bug**
I put in an incorrect URL to clone a repo which resulted in a 404 but the Studio project was still created. Since I cannot open this project, I am unable to remove it from my recent projects list.

**To Reproduce**

1. Open Studio and try to clone a non-existent repo or one you don't have access to
2. Notice you get a 404 but the project is still created

**Expected behavior**

If a project fails to clone on creation, don't create the project.

**Screenshots**

![2019-11-27 15 30 42](https://user-images.githubusercontent.com/7423098/69760794-0dbd5800-112b-11ea-8a3b-722c99776b70.gif)

**Additional context**

Related to https://github.com/stoplightio/studio-internal/issues/1296 which was fixed by https://github.com/stoplightio/studio-internal/pull/1337

**Comment by marbemac** [comment]
@wmhilton 👆 just the push we needed to clean up the project registry :).

**Comment by lottamus** [comment]
This is no longer an issue in v1.8.0
