### ISSUE TITLE
New security schemes are created with the scheme property capitalized ("Bearer") rather than lowercased ("bearer")

### ISSUE THREAD

**Issue by NikVandewouwer** [stoplightio/studio#261]
when defining a securityScheme through the gui of type http bearer this is generated:
securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      description: "JWT Token received from Token URL"

However with this the Authorization header is not set by for example swagger-ui. Therefore swagger-ui cannot succesfully pass the security of my api's with "try out" (result is always a 401)

If I change the scheme from Bearer to bearer (lower case b) the header is send properly.

I find this out when I tried to validate the following in editor.swagger.io:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      description: "JWT Token received from TME's Token URL"
      bearerFormat: JWT

Because of the additional attribute bearerFormat it gave me this error: 
> Structural error at components.securitySchemes.bearerAuth
should NOT have a `bearerFormat` property without `scheme: bearer` being set
Jump to line 300

It would be nice to define the bearerFormat as well through the gui

**Steps to reproduce**

1. Create a new security scheme with type "http" and scheme "bearer" via the forms view
2. Notice the scheme property has it's value capitalized ("Bearer") rather than lowercased ("bearer"

**Comment by NikVandewouwer** [comment]
on top of that if I change in the code editor of stoplight studio Bearer to bearer the UI default back to the first in the dropdown, being Basic

**Comment by NikVandewouwer** [comment]
@lottamus  when willl this bug be included?

**Comment by lottamus** [comment]
@NikVandewouwer this issue has been fixed and will be included in Studio v1.9.0 which will be released Jan 29th

**Comment by chris-miaskowski** [comment]
Looks good in RC, closing
