### ISSUE TITLE
Studio : put again the possibility to have both Form and Code view while editing

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#263]
As a designer, I can see or edit the OAS code at the same time I edit in 'Form' view.
While editing, one should have both edit mode readily available.

It is sometime more efficient to update in code view, while checking in form view the result. I feel the 'preview' to be less similar to the form/code (normal, it is a view to read) and alternating from 'form' and 'code' view is a little loss of time.
It was more convenient before one of the last updates that removed this feature.

**Comment by benaiahjohn** [comment]
This was a great time saver in the previous versions. It would be great to have this feature back.

**Comment by philsturgeon** [comment]
Hey, this was removed by popular demand from a bunch of users, so we’re sorry to hear you are missing it. 

The concern before was from things being rather confusing, having three different panes meant you often weren’t sure which pane you’d get at first, it wasn’t always clear which pane you were looking at, and selecting a pane that was already open resulted in a confusing swap. 

Here’s the background on all of that #161.

We’d be happy to try and figure out a way to include both form and code views simultaneously so long as it’s done more intuitively. For that, we’ll take suggestions and run some experiments on whatever ideas we come up with, but I’m calling this change a UX improvement not a removed feature. Let’s continue to improve the UX for everyone! 😁

**Comment by john-doe-2016** [comment]
Hi,

For me, it is a great backward step in efficiency: quick corrections in code view, copy / paste operations, ...
I never had any problem with the UX implementation, so I do not know how you could have improved it.
And I do not recall being forced to use the code view by the way. Most of my reviewers and developers did just not used it, and never complained about it getting in the way.

I quickly read the beginning of the 161 issue and I did not see that it was requested to remove the possibility to have both form and code view ;). It was just a minor issue about UX to my point of view.

Regards

**Comment by philsturgeon** [comment]
I hear you @john-doe-2016. How people view UI and UX is wildly varied, and every change or improvement for anything will always have people who prefer it, and people who prefer how it was.  

Let's get to the root of the problem: it sounds like the form view was what you used for real time feedback, and the preview panel is missing information that you need in order to know that the code changes you are making are doing the right thing?

> I feel the 'preview' to be less similar to the form/code (normal, it is a view to read)

What real time feedback are you missing from the preview panel that is in the form panel? If we can solve that, it seems like you wont need to have code + form open at the same time.

**Comment by john-doe-2016** [comment]
Hi @philsturgeon ,

You are missing the point: there are 2 different uses. The first is the design one, the second is the review / implementation one.

For the first, form and code are used, and each have its strong points.
And my point is not an UX one, but the fact that a feature has been removed: being able to interact with both form and code view at the same time, each one being useful for some tasks. And having both form and code view at the same time is convenient to safeguard modifications in code view, in addition of course of see their result in real time.

For the second, reading should be sufficient since it should contain all information. But it is missing things like security, easy access to full comments and variable constraints, put/post samples, real schema of responses, ...
More or less, it is incomplete ; it lacks a complete / export view by the way.
So at the moment I have to give access to the full project to the devs, and they use the form view to implement, which is not the way I was envisioning Spotlight view.

But you are right, if the preview pane was complete, one could verify code pane modifications in real time. But we still would have to toggle to form view for some uses. Which left us to my request: have back the possibility to have both form and code view at the same time ;).

Well it is not by the way the most important thing. Complete and exportable reading view and the ability to "specify by sample" (2 of my other feature requests) does seem more important to me.

Best regards

**Comment by philsturgeon** [comment]
Review and Design don't sound so different to me, in both what you seem to be saying could be boiled down to 1) a lack trust in the form view, because 2) the Preview is not showing you enough information. That's easy to solve. 

To your specific example, read (docs) is getting security in #257. 
Beyond that, I've re-requested the team make default, example, readOnly, writeOnly, etc constrains more clear in the documentation. Thanks for reminding me to chase.

The documentation should always have more information than forms, because whilst we can display everything there is not always a convenient way to make a GUI form for everything. So once we've improved the docs, I think this concern will go away. We'll see! 

Anyhow, I'm not sure what you mean about the giving devs full access stuff. Could you elaborate?

**Comment by john-doe-2016** [comment]
Hi @philsturgeon ,

I have not been clear enough: I do feel too that if the 'doc' view is complete, it is better that the form view.

As for giving devs full access : since there is no "public" documentation, that it is not complete and not 'exportable', I have to give the (full) access to the github yaml file for the devs to have all the information needed to work. And thus there is the (limited) risk that they do make modifications to the specs.

But it is another point / case, which will be solved with a complete and exportable (even through 'save as') view, which is another of my requests ;). My bad.

Regards

**Comment by philsturgeon** [comment]
> I have not been clear enough: I do feel too that if the 'doc' view is complete, it is better that the form view, and that it may be a solution if the alternation between code and form view keeps the edition context (ie where we are).

Yes I understood this to be what you meant. I answered explaining that docs is becoming more complete, we just merged a few PRs this morning to help.

> As for giving devs full access : since there is no "public" documentation, that it is not complete and not 'exportable', I have to give the (full) access to the github yaml file for the devs to have all the information needed to work.

Public Documentation is available right here: https://stoplight.io/docs/

You can click Publish right from Studio Desktop or Web and it'll update the docs. 

Export OpenAPI is available as right click.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/67381/71002062-d6651a00-20de-11ea-8124-bebf138728c2.png">

Share is coming in Q1 2020, it's on the Roadmap over here. https://portal.productboard.com/fljngg9hcw9knfsnwmtyzgva/c/8-share-readonly-view-of-a-studio-project-with-others?utm_medium=social&utm_source=portal_share

Seems like we are all set here! :D

**Comment by john-doe-2016** [comment]
Hi @philsturgeon ,

The documentation is not public, one has to have access to Stoplight and (but it may no more be the case?) the YML/project file through git hub to have access to the documentation :
![image](https://user-images.githubusercontent.com/20415788/71259455-c779a400-2338-11ea-8638-ecadeea30a1a.png)
(if not registered)

But maybe now registering to Stoplight is sufficient, I did not test recently.

So glad to know that public access is on the near term roadmap :). 

As for using the preview + (code or form), I'll adapt.

Regards

**Comment by philsturgeon** [comment]
Docs are public by default once they have been published. Click Publish and you'll be all set.

**Comment by lottamus** [comment]
> Docs are public by default once they have been published. Click Publish and you'll be all set.

By default, your docs will assume the same permissions as your Github repository. For example if your Github repo is private then your docs will be private.

If you want to make them public, there is a dropdown in your project settings page to change the "Visibilty" level.

<img width="1464" alt="Project_Settings___Stoplight" src="https://user-images.githubusercontent.com/7423098/71327049-25d58c80-24c9-11ea-84a4-6c996f5803e8.png">

**Comment by john-doe-2016** [comment]
Hi @lottamus,

Thank you for this information, I did not know.

Nevertheless, is it planned to decouple this? Having docs and a dev repo with the same security does not seem adequate to me.

Happy new year, and best regards

**Comment by philsturgeon** [comment]
@john-doe-2016 The docs are a rendering of the API descriptions found in the repo, but making the docs public does not make the source code public.

**Comment by john-doe-2016** [comment]
@philsturgeon, what I understood is that to have the docs public, the repo has to be public. I did a unsuitable shortcut in my message it seems.

But it does not change the fact that using a repo based security does not seem adequate to me. First, we are not Git pro users, and I did not found how to restrict access to read only to the repo.
But we should be able to give access to the docs (or, other feature request), be able to export the generated documentation.

The sharing feature in the pipe should alleviate this though, if my understanding of a previous post is good.

Happy new year

**Comment by philsturgeon** [comment]
> what I understood is that to have the docs public, the repo has to be public. I did a unsuitable shortcut in my message it seems.

Nope, if you use Stoplight Docs, they are only public, regardless of your GitHub repo membership type, settings, or anything else. 

If you use our enterprise offering Hubs, you get a lot more options, like Private docs, access can be configured by SSO, manual invitations, all sorts. 

There is a lot of advanced functionality Stoplight can offer but it seems like you don't need any of it. Your use case is fine. 

Private repo: great.
Public docs: great.
Hidden source code even though you published docs: You bet!

**Comment by john-doe-2016** [comment]
Hi @philsturgeon ,

Indeed, we are not (yet ? :)) customers of your subscription.

And I guess I am not very explicit in my messages: I can not have the docs public, it would be a fault since they are the property of the company.
So I would need some way to have users registering on your site, and use those for access control.

Well, you gave me the information that it is available in the subscription, so thank you!

Best regards

**Comment by philsturgeon** [comment]
Hubs does this which is part of our Next toolsuite, and Hubs v2 is coming along which helps with ACL for docs.

**Comment by john-doe-2016** [comment]
OK, thank you
