### ISSUE TITLE
Remove Body Not Work Properly

### ISSUE THREAD

**Issue by gianfryBear** [stoplightio/studio#264]
## Describe the bug

When you add a Body to the associate HTTP request and then remove it with "Remove" button in the source code you can find the follow snippet "requestBody: {}" in yaml source code,  which then generate an Error.

## To Reproduce

- Within an OpenAPIv3 specification, add a request body to an operation
- Remove the request body

## Expected Results

- `requestBody` would be absent from the operation

## Actual Results

- `requestBody` is still present, but empty

## Notes

This is problematic because the [OpenAPIv3 `requestBody` attribute](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operation-object) has required attributes that are now not being met. The field should be removed entirely if there is not request body present.

<img width="700" alt="Screen Shot 2020-02-21 at 4 03 20 PM" src="https://user-images.githubusercontent.com/4060903/75075644-f096ec00-54c3-11ea-8245-b030c9bd28d7.png">

<img width="700" alt="Screen Shot 2020-02-21 at 4 03 47 PM" src="https://user-images.githubusercontent.com/4060903/75075653-f42a7300-54c3-11ea-85ba-41718105cb1a.png">

**Comment by philsturgeon** [comment]
Great news! This has been sorted out and will be ready in v1.12 which is coming any day now.
