### ISSUE TITLE
Operation ID generation can be invalid when path parameter is used

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#265]
Brackets surrounding path parameters get included in the generated operation IDs. For example, `GET /assets/{assetID}` generates `get-assets-{assetID}`, which then triggers the Spectral warning:

```
operationId may only use characters that are valid when used in a URL.
```

After reviewing the OpenAPI specification directly, I'm not actually sure if this is a requirement, however it is annoying to have these warnings generated by Studio itself. 

Studio should either:

- Adhere to the Spectral rule, and only generated OIDs that are valid when used in a URL, or
- Remove the Spectral rule, as I can't find anywhere where this requirement is specified

**Comment by StoplightDeb** [comment]
@P0lip - I see the description here mentions
```
Studio should either:

Adhere to the Spectral rule, and only generated OIDs that are valid when used in a URL, or
Remove the Spectral rule, as I can't find anywhere where this requirement is specified
```

I see the word _either_ - can you shed some light on which of these actions is expected in Studio?  Thank you kindly!

Cc: @chris-miaskowski

**Comment by P0lip** [comment]
@StoplightDeb I went with being compliant with the Spectral rule, so the following statement is valid

> Adhere to the Spectral rule, and only generated OIDs that are valid when used in a URL, or

**Comment by StoplightDeb** [comment]
@P0lip - `post-pets-petId-` trailing hyphen ok?

**Comment by P0lip** [comment]
@StoplightDeb should be fine unless you want me to trim it. :sweat_smile: 
Not sure, if that looks confusing to you, it will certainly be confusing to others too, so we in fact may want to get rid of it.
@rossmcdonald whatcha think?

**Comment by StoplightDeb** [comment]
@P0lip it looks weird to my eyes 😆 like there should be another word after the hyphen

**Comment by rossmcdonald** [comment]
Let's just trim it.

**Comment by StoplightDeb** [comment]
@P0lip - Also noticed that if you add the parameter to the `GET`, it doesn't change the operationID.  If you then add a `POST`, `PUT`, `PATCH` etc, those operation IDs will show correctly.  I think whatever operation you start with will NOT have the operation ID automatically created, but subsequent ops will. I only noticed this because the `GET` is the first op created.

**Comment by P0lip** [comment]
@StoplightDeb good find, you might be right. I need to check how the default operation gets created. Looking.

**Comment by chris-miaskowski** [comment]
I have double checked and it looks good. I'm so happy you've decided to trim that dangling hyphen. It was weeeird :) 

Anyways, signing off!

**Comment by chris-miaskowski** [comment]
Added into TR: https://stoplight.testrail.io/index.php?/cases/view/6096
