### ISSUE TITLE
Validation against schemas for model and response examples

### ISSUE THREAD

**Issue by nuba** [stoplightio/studio#269]
**User story.**

As a api designer, I can build model schemas, and response schemas referencing those models. While writing response examples, I'd like to be notified when they're not aligned with the schemas.

**Is your feature request related to a problem?**

Yes, the problem of having to keep schemas and examples in sync manually. 

Easy with small and simple apis, but can become a nightmare as the api grows in size and complexity. It introduces friction to the api release process, as examples become a ball and chain. People will just drop them, if they can, except for the most trivial responses.

**Describe the solution you'd like**

I'd like to see example errors right there next to the linting errors. 

What I'd really love to see is a content-type-aware textarea, offering me autocomplete for the properties based on the schema. Like what I have in Visual Studio Code or JetBrains IDEA.

Related:
* https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings
* https://www.jetbrains.com/help/idea/json.html#ws_json_schema_add_custom

**Context**

I consider the examples part of the spec. They are specially important when discussing it with people that think better with concrete cases than with abstractions. So model and response examples have to stay in sync with the spec. Additionally, developers can use the api spec to launch a mock server, and suddenly find themselves dealing with malformed responses.

**Comment by philsturgeon** [comment]
When working on an OpenAPI document, "Media Type Examples" and "Schema Examples" will be validated against the schema they're built against. This was actually done a while ago! :D
