### ISSUE TITLE
Toolbar covering most of the screen on Stoplight Studio Desktop / docs not displaying

### ISSUE THREAD

**Issue by NEJEtherington** [stoplightio/studio#270]
The toolbar at the bottom of the page is set such that it is impossible to view or use Studio.  Does not appear to be possible to reduce the size.  The docs pages displays no information whatsoever.

**To Reproduce**

1. Visit [Stoplight docs page](https://stoplight.io/p/docs) 
2. Click 'Studio' (see screenshot 1 - clicking on Spectral or Prism gives the same result, as does trying to view the docs in any other manner)
3. Visit [Studio](https://stoplight.io/p/studio) (see Screenshot 2)
4. Select studio-demo (see Screenshot 3 - the view is the same whatever project is selected)

**Expected behavior**
* Should be able to adjust the height of the bottom toolbar
* Default toolbar height should not be obscuring anything

**Screenshots**
Screenshot 1:
![Screenshot_2019-12-12 stoplightio studio Stoplight](https://user-images.githubusercontent.com/46679103/70726318-d25b8580-1cf5-11ea-8c5e-57ecda750cd6.png)

Screenshot 2:
![Screenshot_2019-12-12 Studio Stoplight](https://user-images.githubusercontent.com/46679103/70725542-793f2200-1cf4-11ea-9172-7edfd7437a03.png)
Screenshot 3:
![Screenshot_2019-12-12 stoplightio studio-demo Studio Stoplight](https://user-images.githubusercontent.com/46679103/70726660-59106280-1cf6-11ea-9815-fcc3dc2ead28.png)

**Environment:**
 - Studio version: v1.6.16
 - OS: Ubuntu 19.10
 - Browser: Firefox 71.0

**Comment by rossmcdonald** [comment]
Studio Web does not support Firefox at the moment. This will be fixed with the v1.7.0 release going out this week, though.

**Comment by lottamus** [comment]
@NEJEtherington are you still seeing this issue?

**Comment by NEJEtherington** [comment]
@lottamus no, everything looks to be displaying correctly now. Thanks!
