### ISSUE TITLE
Unable to link from API to Markdown article

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#271]
As a docs writer, I should be able to link from an API reference to a Markdown article.

## To Reproduce

Create a link to a Markdown article in a API description. For example, in an endpoint description, add the following Markdown:

```
> Read more about this functionality [here](../docs/test.md).
```

Where `../docs/test.md` is a valid path to a Markdown article.

## Expected Results

Regardless of whether I am viewing published docs or the preview in Studio, when clicking on the `here` link referenced above, I should be brought to the referenced Markdown article.

## Actual Results

In Studio, nothing happens. In published docs, the URL brings you to an invalid path.

**Comment by lottamus** [comment]
@rossmcdonald are you sure that relative file path is correct? I am not seeing any issue navigating via markdown links

![2019-12-23 09 46 44](https://user-images.githubusercontent.com/7423098/71366989-38070780-2569-11ea-9548-c2c80816d03f.gif)

**Comment by chris-miaskowski** [comment]
Closing, will be tested in regression suite
