### ISSUE TITLE
Request Maker should support Bearer security scheme

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#272]
Related to https://github.com/stoplightio/studio/issues/108, we don't support all OpenAPIv3 auth methods. For example OpenAPIv3's "[Bearer](https://swagger.io/docs/specification/authentication/bearer-authentication/)" security scheme, which I would expect to be included as an `Authorization` header is not present.

We should review all of the available security scheme formats and make sure that the Request Maker supports them.

**Comment by immortalpl** [comment]
I also miss "Bearer". In postman sometimes I have to manually modify more than 50 methods to add security support.

**Comment by chris-miaskowski** [comment]
Hey @lottamus it's marked as 1.8.0 but I've checked on staging and it doesn't seem to be implemented. Was this implemented? If not, please reschedule to 1.9.0.

**Comment by lottamus** [comment]
@chris-miaskowski oops yep it's supposed to be 1.9. I'll double check to make sure there aren't any more like that

**Comment by chris-miaskowski** [comment]
Looks good in 1.9 RC
Added test C8256
