### ISSUE TITLE
Can't open other projects in a separate application instances. Empty window appear.

### ISSUE THREAD

**Issue by immortalpl** [stoplightio/studio#274]
It's not possible to open more application instances to work on a few projects in parallel, for example to compare something. Every next instance is an empty window.

**To Reproduce**

1. Try to open application more one than once.

**Expected behavior**
Few instances with possibility to open different project for each window.

**Actual behavior**
Empty window appear for next instances

**Environment (remove any that are not applicable):**
 - Studio version: [1.6.2]
 - OS: [e.g. Windows 10 Pro]
 - Browser: [e.g. Chrome 78.0.3902.92]

**Comment by philsturgeon** [comment]
I think we could merge this with #213.
