### ISSUE TITLE
Default to bundle strategy when dereferencing

### ISSUE THREAD

**Issue by marbemac** [stoplightio/studio#275]
**User story.**

As a studio user, I can do export the bundled document, so that I can use it in other tools.

**Is your feature request related to a problem?**

Right now we fully dereference the OpenAPI / JSON Schema model when exporting. Bundling will lead to MUCH smaller export sizes, and generally preferred in most cases. In addition, some customers are having trouble exporting from Platform when their design library is being used, since their design library models make use of inner definitions - bundling would solve this problem.

**Describe the solution you'd like**

- add bundle support to https://github.com/stoplightio/json-ref-resolver
- use bundle by default in most situations (graphite, export, etc)

**Additional context**

https://github.com/APIDevTools/json-schema-ref-parser has a good bundling implementation. Unfortunately we can't use that library because it would involve a large amount of work to switch our ecosystem over, and it is many orders of magnitude less performant. We can still learn from the approach implemented there though!

Re how bundling works, check out the following example (uses `json-schema-ref-parser`) to see. `yarn` and then `yarn start` to output bundled result, which you can compare to the original fixtures.

[json-ref-resolver-bundle-example.zip](https://github.com/stoplightio/studio/files/3965709/json-ref-resolver-bundle-example.zip)

**Comment by rossmcdonald** [comment]
Resolved with v1.10.0, which now offers a bundled export option.

**Comment by brentonhouse** [comment]
@rossmcdonald  - I am using Version 1.10.2 (1.10.2.17323) and both `Export OpenAPI` and `Export OpenAPI (bundled)` export the same content for me.   Neither of them include the `$ref` properties but instead embed the actual content from the reference.

**Comment by rossmcdonald** [comment]
Hi @brentonhouse, would it be possible to share a specification that reproduces the issue? 

Ideally with bundling the references would be inserted at the root of the API object and referenced locally. There could be something specific to the API or the references in your spec that is putting them in-line, though.

**Comment by philsturgeon** [comment]
Yeah please share an example of this, I’ve tested this manually and got the right results myself.

**Comment by brentonhouse** [comment]
What is best way to share this project with you?

**Comment by philsturgeon** [comment]
Often the best way to share a bug is to create the smallest reproducable example, but if that's tricky or time consuming you can just zip the whole thing over to phil@stoplight.io and I promise not to sell all your data. 😇

**Comment by brentonhouse** [comment]
I’m fine doing that but just can’t figure out where studio stores the files to zip up

**Comment by philsturgeon** [comment]
If you're using Studio Desktop, you could have used Open Existing Folder and it'll just be exactly where the folder was on your harddrive, but if you cloned the repo or started one from scratch you can find the directory here: https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/01-working-with-projects.md#from-scratch
