### ISSUE TITLE
An error was encountered while publishing this project, please try again.

### ISSUE THREAD

**Issue by login-world** [stoplightio/studio#278]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by hashting** [comment]
Yes, this was fixed yesterday, and is broken again.
https://github.com/stoplightio/studio/issues/280

**Comment by lottamus** [comment]
@login-world @hashting we're investigating this now. Are you able to give us any more information? Which environment (Studio Web or Desktop) does the error happen in? Does it occur for all projects or a certain one? What's the name of your project?

**Comment by pytlesk4** [comment]
> Yes, this was fixed yesterday, and is broken again.
> #280

@hashting and @login-world can you provide a little bit more information? I am having no issues with publishing at the moment, and think you guys might be running into a different issue than the one that is linked/re opened.

Can you zip up your project and paste it here? Or let me know what the network tab is saying?

**Comment by hashting** [comment]
Using web; it was working yesterday; I worked on it whole day, and suddenly it was broken; I even tried to revert to previous commits because I thought it was something with the source, but no luck.
project: hashting/third-party-integration

don't see anything special in the network tab.

![image](https://user-images.githubusercontent.com/58006362/71267421-c6ea0900-234a-11ea-814f-030bb3dcd913.png)

**Comment by hashting** [comment]
> Using web; it was working yesterday; I worked on it whole day, and suddenly it was broken; I even tried to revert to previous commits because I thought it was something with the source, but no luck.
> project: hashting/third-party-integration
> 
> don't see anything special in the network tab.
> 
> ![image](https://user-images.githubusercontent.com/58006362/71267421-c6ea0900-234a-11ea-814f-030bb3dcd913.png)

FYI Preview itself is working fine!

**Comment by pytlesk4** [comment]
@hashting do you see anything for `/nodes.upload`? I would be interested to see the request body for that.

**Comment by hashting** [comment]
Nope
These are the only entries I see when pushing the Publish button

![image](https://user-images.githubusercontent.com/58006362/71274400-6b247d80-2354-11ea-8408-886e6846b68d.png)

**Comment by hashting** [comment]
It's a private repo; if you provide email then I can zip the project

**Comment by pytlesk4** [comment]
@hashting `tom@stoplight.io`

**Comment by pytlesk4** [comment]
@hashting let me know when you email, just want to make sure it doesn't get put into my junk folder.

**Comment by hashting** [comment]
@pytlesk4 check mailbox.

**Comment by pytlesk4** [comment]
@hashting thanks, that was immensly helpful. Got a fix, and should get a release out shortly.

**Comment by lottamus** [comment]
@login-world @hashting we've just released Studio v1.7.2 which contains a fix for this error. Thank you for reporting!
