### ISSUE TITLE
Sort models and operations in lexical alphabetical order

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/studio#279]
Follow up on https://github.com/stoplightio/studio/issues/266

**Problem with existing solution**

Models and operations starting with capital letters will be displayed first and words starting with lower case letters will be ordered separately. For example: 
Ba, Bb, ba, AA, aA 
will be sorted as
AA, Ba, Bb, aA, ba

**Solution I would like**

I would like models and operations to be sorted by letters regardless of their capitalization.

E.g.

Ba, Bb, ba, AA, aA, ab, AB
to be sorted as:
aA
AA
ab
AB
ba
Ba
Bb 

**Actual solution**

![](https://user-images.githubusercontent.com/33187986/71602321-75493780-2b1d-11ea-8c0f-529dee5534ad.png)

**Comment by hashting** [comment]
Why can't we have custom sorting; especially on the operations I think it would make sense. Now I have to add 1. 2. 3. just for ordering reasons.

**Comment by chris-miaskowski** [comment]
Howdy @ssspear and @lottamus I can see a PR to elements but was this integrated into platform? The release says 1.9.0 and I want to double check on-prem.

**Comment by chris-miaskowski** [comment]
Hey @ssspear I've tested on Version 1.9.0-build.9803 (532343f) and the sorting doesn't work for embedded models. However, it does for standalone. See the screenshot:

![image.png](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/3c26b42b-999d-4f82-81d1-6b95c455d7f6)

I suggest we postpone this to next release. I haven't checked on `master` btw.

Moving back to In Progress.

**Comment by chris-miaskowski** [comment]
@lottamus FYI I removed the 1.9.0 release version from it.

**Comment by philsturgeon** [comment]
Actually trying to get operations sorted in the order they're defined in. Regardless ToC is getting overhauled so let's avoid multiple issues on the topic.
