### ISSUE TITLE
Cloning fails to parse the ssh URL

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/studio#28]
**Describe the bug**

Studio thrown an error when I tried to clone a repo using SSH URL

**To Reproduce**

1. Go to Studio landing page
2. Try to create a repo by clonining `git@github.com:stoplightio/prism.git`
3. Click clone
4. Observe

**Expected behavior**

Repo cloned

**Actual**

Throws error. 

![image](https://user-images.githubusercontent.com/29548931/62304099-9da10d00-b47d-11e9-888e-e5ec82701a89.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/29548931/62303872-36835880-b47d-11e9-8c76-d299c81f622d.png)

**Environment (remove any that are not applicable):**
Studio beta 8

**Comment by wmhilton** [comment]
Ugh.... why do people still try to retrieve files by logging in as a Unix user via an emulation of a teletype machine.

We can either:
- make it clear that only HTTP(S) URLs are supported
- try to be clever and normalize other URL protocols to HTTP(S) form

Got any preference? (I kinda prefer the first option... it's less complicated and less risky.)

**Comment by gido** [comment]
OH. I'm using the Stoplight Studio MacOS App and I wasn't aware that only HTTP(S) URLs are supported on an already cloned project (with ssh+git).

So, I'm in favor of the first option too (by disabling the "commit" button and explain why for example).
