### ISSUE TITLE
An error was encountered while publishing this project, please try again.

### ISSUE THREAD

**Issue by emperorjm** [stoplightio/studio#280]
I am seeing a totally different API document to that of the one that I created and was viewable earlier this week. When I click to edit the API doc it shows the correct documentation pages but when I try to Publish the document I get the following error:

**An error was encountered while publishing this project, please try again.**

There seem to have been an update yesterday (December 18th) that might have caused this bug to come about.

**Environment:**
 - Studio version: Version 1.7.0 (7c9af9b) Built on Wed, 18 Dec 2019 20:28:09 GMT
 - OS: Mac OS 10.15.2
 - Browser: Chrome 79.0.3945.79

**Comment by hashting** [comment]
Same here!

**Comment by michaelklopf** [comment]
Hi, we just discovered the same error, the published documentation is gone, with the Overview page showing a document with the url `dummy-api/adira.v1.json`.

@rossmcdonald

**Comment by lottamus** [comment]
@emperorjm @hashting @michaelklopf we ran into an issue yesterday when deploying a new feature which allows publishing multiple branches/groups from the same git repository. We've just pushed up a fix for that publishing error. Can you try again to verify it's working for you all now?

**Comment by hashting** [comment]
Working again! Thanks.

**Comment by michaelklopf** [comment]
Yeah, worked, but only after deleting the whole project and cloning it again.
