### ISSUE TITLE
Able to have a Sample for QueryParameters

### ISSUE THREAD

**Issue by hashting** [stoplightio/studio#281]
**User story.**
As a documenter, I can create a sample for GET and QueryParameters, so that I can explain the user the sample.

When using POST, PUT etc I can create a sample body. But for GET operations with Query Parameters, there is no way to create a sample Request with QueryParameters.

**Comment by philsturgeon** [comment]
Looks like we fixed this one, sorry for not noticing the issue. 

<img width="569" alt="image" src="https://user-images.githubusercontent.com/67381/81119941-abf7ea00-8f23-11ea-9f2e-a731344c552f.png">
