### ISSUE TITLE
Login State Out-Of-Sync Preventing Logging In

### ISSUE THREAD

**Issue by straley** [stoplightio/studio#282]
**Describe the bug**

Somehow the login state of the Ubuntu Studio application became out-of-sync with the internal browser state.  When I try to login, a list of products is shown instead with an already logged in account.

**To Reproduce**

Unable to reproduce.  However, I'm on Ubuntu running Chrome 79.0.3945.79.  I keep two sets of tabs open, one for strictly business-related content and one for research.  They are linked to two different chrome accounts.  I suspect it's related to the order in which these chrome account sessions are interacted with.

**Expected behavior**

If I attempt to login but the browser already is in a logged in state, simply update the client application to match the browser state.  Or, better yet, sync the client with the browser to show the same logged in state.

**Screenshots**

![Screenshot from 2019-12-20 14-09-21](https://user-images.githubusercontent.com/795062/71289874-e0cc2180-2333-11ea-93a7-a08dec44d79f.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.7.1
 - OS: Linux pop-os 5.3.0-7625-generic 27-1576337002-19.10-bc3488b-Ubuntu SMP Sat Dec 14 18:31:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
 - Browser: Chrome 79.0.3945.79

**Additional context**

I have a video of the interaction as well

**Comment by straley** [comment]
If you want me to try a few different scenarios in order to try and reproduce this (since I have the culprit configuration), please at-me and we could set up a screen share.

**Comment by wmhilton** [comment]
@straley can you try updating to 1.7.3 and let me know if we fixed the issue?

**Comment by philsturgeon** [comment]
It’s been two weeks and we’ve got another release out so I’ll close this. If the problem hasn’t been fixed please let us know.

**Comment by straley** [comment]
I haven't been able to recreate the problem.
