### ISSUE TITLE
Inconsistencies path endpoint UI

### ISSUE THREAD

**Issue by straley** [stoplightio/studio#283]
**Describe the bug**

When creating a GET endpoint the UI display of "Your GET endpoint" can show different values, which can both differ from the Mock URL displayed in the Routes panel.  This is particularly evident if another OS process running on port 3000 forces the mock URL to utilize 3100.

**To Reproduce**
1. Start a service on port 3000
2. Create a new project
3. Create a new GET endpoint
4. Notice the differences
5. Click on the HOST:PORT button under the left "Your Get Endpoint"
6. Change your port number
7. Select the GET endpoint under Paths in the left navigation
8. Notice that the endpoint did not change
9. Close out of Stoplight and report
10. Navigate to the endpoint
11. Notice that it has now changed

**Expected behavior**
Each URL displayed for the endpoint should be consistent.  

In some cases, the default for the host is `127.0.0.1` and in others, it is `localhost`.  While this is almost always true, consistency in utilization would be helpful.

When the mock URL is forced to port 3100, the default API Server (which currently is `http://localhost:3000`), should also be on port 3100.

When the HOST:PORT button is clicked and the value is modified on the API Reference Form, the new value should be respected on the API endpoint detail panel

**Screenshots**
![Screenshot from 2019-12-20 16-38-48](https://user-images.githubusercontent.com/795062/71297006-4970c980-2347-11ea-9e32-d6024289ec9d.png)
_Notice that the port is defaulting to 3000 even though the mock server in this case is on 3100._

![Screenshot from 2019-12-20 16-52-54](https://user-images.githubusercontent.com/795062/71297599-bbe2a900-2349-11ea-8e50-4dc3649d7220.png)
_The URL at this point matches what we created._

![Screenshot from 2019-12-20 16-53-42](https://user-images.githubusercontent.com/795062/71297611-cf8e0f80-2349-11ea-9abc-9cca134b1197.png)
_We change it to 3100._

![Screenshot from 2019-12-20 16-54-22](https://user-images.githubusercontent.com/795062/71297635-e2a0df80-2349-11ea-8f00-eaee28b87911.png)
_The endpoint on the detail panel still shows the old port._

![Screenshot from 2019-12-20 16-55-54](https://user-images.githubusercontent.com/795062/71297675-11b75100-234a-11ea-9e5a-83805e9d44eb.png)
_Even while the code view shows the new port._

![Screenshot from 2019-12-17 18-07-53](https://user-images.githubusercontent.com/795062/71297708-34e20080-234a-11ea-8179-6b8de98568a2.png)
_In some cases, all the endpoints can show different ports or hosts._

**Environment (remove any that are not applicable):**
- Studio version: 1.7.1
 - OS: Linux pop-os 5.3.0-7625-generic 27-1576337002-19.10-bc3488b-Ubuntu SMP Sat Dec 14 18:31:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
- Browser: Chrome 79.0.3945.79

**Comment by chris-miaskowski** [comment]
Looks good in the 1.9-rc!
