### ISSUE TITLE
Model schema enum display is incorrect if value is 0

### ISSUE THREAD

**Issue by wl00215041** [stoplightio/studio#284]
**Describe the bug**

Add number 0 to enum, but not show in enum list.

**To Reproduce**

1. Model -> Schema -> any Attribute -> Additional properties -> enum
2. input 0 and Enter
3. 0 not show in enum list, but I can saw it at YAML

**Expected behavior**
0 of enum should show in enum list

**Screenshots**
![2020-01-02 17-56-58 的螢幕擷圖](https://user-images.githubusercontent.com/8559751/71662146-741d4200-2d8b-11ea-83f8-9621eff0cb27.png)
![2020-01-02 17-56-42 的螢幕擷圖](https://user-images.githubusercontent.com/8559751/71662151-78495f80-2d8b-11ea-9bfc-97eacec2f185.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.7.2
 - OS: Elementary OS
 - Browser: Chrome 79.0.3945.88

**Comment by StoplightDeb** [comment]
Looks good 👍
