### ISSUE TITLE
Hang on push

### ISSUE THREAD

**Issue by cjreitman** [stoplightio/studio#285]
**Describe the bug**
Stoplight appears to hang when pushing a commit.  Stoplight then registers that the push occurred, but the commit does not appear in Github (clicking the commit link in the lower left hand corner of Stoplight takes you to the Github 404 page)

**To Reproduce**

1. Make changes to document
2. Click the commit button
3. The circular 'working' graphic appears, and the latest commit in the lower left hand corner of Stoplight appears to be updated.
4. The 'Pushed' notification doesn't appear, and Stoplight hangs here indefinitely.
5. This bug is intermittent, and does not appear reliably.
6. The only solution appears to be to reload the project.

**Expected behavior**
I would expect the commit button to push to Github consistently. 

**Environment (remove any that are not applicable):**
 - Studio version: Enterprise version
 - OS: MacOS Mojave version 10.16.6
 - Browser: Chrome latest version

**Comment by philsturgeon** [comment]
We fixed a whole pile of performance issues with larger repos, tricky circular stuff, etc. If you're still getting this in v1.10.0 let us know and we'll look into it!

**Comment by edalford11** [comment]
This hash happened to me for the second time in the past week. The issue is definitely still present
