### ISSUE TITLE
500 server error trying to read documentation

### ISSUE THREAD

**Issue by daviddfm** [stoplightio/studio#288]
Published via design my API successfully but link returns 500 when not logged in.

https://stoplight.io/p/docs/gh/daviddfm/apis?group=master&utm_campaign=publish_dialog&utm_source=studio

**Comment by lottamus** [comment]
@daviddfm I'm seeing your docs loading correctly now. Can you verify if this is still an issue on your end? Also, have you made any changes or publishes recently that might have resolved this?

**Comment by daviddfm** [comment]
It’s now working. I don’t know what change made it work. Feels like it was some cookie or state issue with my account 

david
