### ISSUE TITLE
Read/Preview ignores "example" on model properties

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#290]
When properties in the schema object contain an `example` property we complete ignore it in Preview.

## To Reproduce

Use the specification:

```yaml
openapi: 3.0.0
info:
  title: Example
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Object:
      title: Object
      type: object
      properties:
        id:
          type: string
      required:
        - id
      example:
        id: "123"
```

## Expected Results

~The provided example would appear in an example tab~ examples tab is for response examples not property examples.

## Actual Results

No examples are displayed. Also this strange pop-over appears if you mouse over the object validations:

<img width="1080" alt="Screen Shot 2020-03-04 at 3 14 52 PM" src="https://user-images.githubusercontent.com/67381/75888123-2a081980-5e2b-11ea-8dfb-49068acf40e9.png">

Recent work had been done on elements to make default, example, and way more keywords show up, but maybe elements has not been updated in Studio?

Related to https://github.com/stoplightio/studio/issues/134

**Comment by philsturgeon** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/67381/81119842-7f43d280-8f23-11ea-902e-7dd01b2166ad.png">

Fixed in Studio v1.11.
