### ISSUE TITLE
[Web/Mac desktop] In Preview mode, API Overview page is no longer clickable once one of the endpoints have been clicked

### ISSUE THREAD

**Issue by AgrimPrasad** [stoplightio/studio#291]
**Describe the bug**
In Preview mode, API Overview page is no longer clickable once one of the endpoints have been clicked. Reproducible in both web version and Mac desktop version.

**To Reproduce**

1. Given any default OpenAPI document loaded in a sample project (e.g. Swagger Petstore)
1. Click on the Publish -> Show Preview button
1. On clicking any API Overview page, the page loads fine.
1. However, if a specific API endpoint is clicked and the user tries to load the Overview page again, it doesn't load anymore. See attached screen recording.

**Expected behavior**
API overview page should also be loaded.

**Screenshots**
Screen recording attached. 

![stoplight-studio-overview](https://user-images.githubusercontent.com/6386887/72130349-3be1b900-33b4-11ea-87bb-42c7cc28c3a5.gif)

**Environment (remove any that are not applicable):**
 - Studio version: 1.8.0
 - OS: Web/Mac OS X Catalina 10.15.2
 - Browser: Chrome 79

**Additional context**
We are trying out Stoplight Studio for the first time to evaluate whether we should buy a license for our company, and while we like the interface, this seems like a serious showstopper bug if this preview behaviour is the same as what happens when the entire document is published to the web.

**Comment by lottamus** [comment]
> if this preview behaviour is the same as what happens when the entire document is published to the web.

Hey @AgrimPrasad thanks for reporting this issue! I can confirm this bug is limited to just the Studio Preview feature. It does not happen for the published project. You can see an example of a published project here: https://stoplight.io/p/docs/gh/stoplightio/studio-demo/reference/petstore/openapi.v1.yaml

Though I'll make sure we get this Preview bug fixed for Studio v1.9.0

**Comment by StoplightDeb** [comment]
Looks good in 1.9.0, closing this one.
