### ISSUE TITLE
Incredibly low-urgency UI improvement: deleting method de-selects path

### ISSUE THREAD

**Issue by jamierumbelow** [stoplightio/studio#293]
**Describe the bug**

Given a path with more than one HTTP method, when a method is deleted, Studio jumps back to the 'API overview' page in a way I find irritating.

**Expected behavior**

This is a taste thing, but it would perhaps feel more natural if it would keep the path selected, and change to the nearest method to the left.

**Comment by mallachari** [comment]
Looks like it is already solved. When deleted it stays with currently selected operation.

![Peek 2020-04-29 11-56.gif](https://images.zenhubusercontent.com/5d3eb13f99357a3001f5f485/db072add-276e-4a30-98af-e9ffeffc17ff)

**Comment by jamierumbelow** [comment]
Excellent!
