### ISSUE TITLE
Type should not take array of values

### ISSUE THREAD

**Issue by krishnajangid** [stoplightio/studio#295]
In below give example From UI form we can add multiple types like type can be string or number
```
requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type:
                    - string
                    - number
```
But actually Swagger Spec does not allow multiple types for the same field.

## How to reproduce:
```
openapi: 3.0.0
info:
  title: demm
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gfgdg:
                  type:
                    - string
                    - number
      description: adfdf
components:
  schemas: {}
```
The above code is valid in stoplight's studio. But it throws an error on https://editor.swagger.io/

**Comment by johandalabacka** [comment]
On https://swagger.io/docs/specification/data-models/data-types/ under mixed types this is how you should do it:

**Mixed Types**
type takes a single value. type as a list is not valid in OpenAPI (even though it is valid in JSON Schema):
# Incorrect
```yaml
type:
  - string
  - integer
```
Mixed types can be described using oneOf and anyOf, which specify a list of alternate types:
# Correct
```yaml
oneOf:
  - type: string
  - type: integer
```

**Comment by krishnajangid** [comment]
Thanks. Makes sense. Can Stoplight support this ?

**Comment by philsturgeon** [comment]
Yeah we're going to get this one sorted out. One of the many bits of confusion that https://github.com/OAI/OpenAPI-Specification/pull/1977 will solve for OpenAPI v3.1, but in the meantime we have an issue to hack around it. https://github.com/stoplightio/studio/issues/295
