### ISSUE TITLE
Import rewrites YAML multi-line content

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#299]
Currently Stoplight is rewriting all our wrapped description content from folded block scalar style using `>` into very long single line single-quoted strings.

I've not found a setting in Studio or Spectral to prevent this rewriting, but would love to be able to keep Spectral consistent with our preferred output.

Thanks!

_Originally posted by @BigBlueHat in https://github.com/stoplightio/studio/issues/230#issuecomment-574694434_

**Comment by philsturgeon** [comment]
Could you provide a little more information on what is wrapping where and when? Are you mixing Form and Code usage, just code? Does it happen on save or some other trigger?

<img width="527" alt="image" src="https://user-images.githubusercontent.com/67381/72464087-8e641080-37cc-11ea-9f9e-5ba2e8101c74.png">

I can create > multilines just fine. Please can you elaborate on the steps taken to reproduce this situation so we can help you further.

**Comment by BigBlueHat** [comment]
@philsturgeon I've mostly noticed it when importing. All the descriptions get rewritten to single quotes single lines...at least if they don't have hard returns in them.

When editing in the Form area, anything that gets a hard return will end up in `description: |-` with multiple lines, but "hard wrapped" multi-line content with no hard returns using `description: >` will get rewritten to `description: '...'` instead.

Essentially, we're aiming at a "classic" 80 character edge and would for hand editing (in or out of Studio) and Form editing in Studio to all be cross-compatible.

But maybe I just want the 🌔

**Comment by philsturgeon** [comment]
Thanks for the extra detail. Somebody should swing by to take a look at this when they're available.

**Comment by simonjpartridge** [comment]
This is a problem for me too. It makes merging description changes in git very hard since the entire description now lives on one line in the source. This means any change in the description will conflict with any other change with no easy way to merge those conflicts

**Comment by philsturgeon** [comment]
I've put this on a special list for fast-fixing. 😅

**Comment by marbemac** [comment]
@BigBlueHat @simonjpartridge when you have a moment could you share a example yaml document that triggers the issue when it is imported? Thanks!

**Comment by simonjpartridge** [comment]
[test.yaml.zip](https://github.com/stoplightio/studio/files/4324007/test.yaml.zip)
Here you go. It seems to be something to do with having titles in the description. 
If you open this file and then edit the description in the form view. When the file saves the description will all be put on one line.

**Comment by philsturgeon** [comment]
Yeah with that file, Doing "Import" and then clicking "View" gives me this:

```
openapi: 3.0.2
info:
  title: "Our API'"
  version: '0.6'
  description: "This is Our  API ### We have a title \n"
```

Doesn't matter if its `describe: |` or `describe: >` it's still rewriting the stuff into a single line `""` string.

**Comment by philsturgeon** [comment]
It would be ideal to solve this issue by respecting whatever is there, but an alternative suggestion has come up over here: https://github.com/stoplightio/studio/issues/447

**Comment by P0lip** [comment]
We've just added editor.lineWidth option to Stoplight config, so you can adjust the value to your liking and it's going to be respected. :slightly_smiling_face: 
The change will be available in Desktop v2.

**Comment by philsturgeon** [comment]
Excellent. I've added a note to the [stoplight config docs](https://meta.stoplight.io/docs/platform/2.-workspaces/c.config.md#editor) and folks will be able to enjoy once Studio Desktop v2 is out!
