### ISSUE TITLE
Editing path parameters in forms is avaliable in Stoplight Next, but not Studio

### ISSUE THREAD

**Issue by pazaan** [stoplightio/studio#3]
**User story.**
As a Forms User, I can design and document URL parameters in the forms view, so that I don't have to type YML (or know the parameters spec).

**Is your feature request related to a problem?**

**Describe the solution you'd like**
Support for URL parameters in the Forms View.

**Additional context**
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/96943/61069948-cde22680-a450-11e9-9f75-b5d3b3cd5a44.png">

**Comment by chris-miaskowski** [comment]
Hmm, curious if anyone realized that this feature is broken on `next` :P

**Comment by emrahtoy** [comment]
This is still the case, is there any progress on this issue @chris-miaskowski ?

**Comment by chris-miaskowski** [comment]
Hey @emrahtoy, yup! We've merged the feature to our `development` branch and it will be coming out soon! :)
