### ISSUE TITLE
Fields in yaml model are sometimes in the wrong order in the form view and docs

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#305]
I updated the name of an embedded submodel in a model, in code view.
In the yaml, we have :
![image](https://user-images.githubusercontent.com/20415788/72741069-30a63e80-3ba7-11ea-80b7-de185ff283a6.png)
And in the generated doc, it is now the last attribute:
![image](https://user-images.githubusercontent.com/20415788/72741162-5c292900-3ba7-11ea-9f58-90510503745e.png)
This is true in the model view, and in the view of the object in the response of an API/verb.

But in some cases, it has no effect, I have updated some attributes without this effect.

NOTE: I did not looked at the form view since I have the problem of the forced string conversion (see bug #302).

The order of the fields does not incurs problem in the technical communication, but it is often a point of ergonomics when read by users. Moreover, the order in the object description is no more the one in the examples nor in the API's returned objects.

EDIT : I did test with the form view, and as in the docs, this submodel is at the end of the object too: 
![image](https://user-images.githubusercontent.com/20415788/72748106-a49c1300-3bb6-11ea-8b0e-ec03b247c894.png)
So this one is wrong too.

**Comment by john-doe-2016** [comment]
In fact, it seems that attributes are now sorted by alphabetical order, which does not seem adequate to me, I think they should be sorted like editors wants it, ie semantically/functionnaly.

Regards

**Comment by philsturgeon** [comment]
Hey @john-doe-2016, I completely agree and we'll be looking at ordering as an overall concept in v2.x. Some folks like alpha ordering but we need to have the option to sort things manually and/or turn off alpha ordering too.

**Comment by philsturgeon** [comment]
Let's follow the progress for this issue in https://github.com/stoplightio/studio/issues/147.

**Comment by philsturgeon** [comment]
This has been fixed in v1.12! :D

**Comment by john-doe-2016** [comment]
Yes, I just saw.
Thx to the team !
