### ISSUE TITLE
Publish impossible

### ISSUE THREAD

**Issue by bastienu** [stoplightio/studio#307]
When I click on "Publish" this message is displayed :
"An error was encountered while publishing this project, please try again."

I have no issues detected in my yaml.

Can you solve this problem ?

Thanks.

**Comment by rossmcdonald** [comment]
@bastienu Does this error happen consistently? If so, can you open your browser's developer tools and look at the Network tab or Console to see if there is more information listed?

**Comment by bastienu** [comment]
Hi. Here is the console error.

![Capture d’écran 2020-01-24 à 09 56 37](https://user-images.githubusercontent.com/1685778/73056641-def40180-3e8f-11ea-8d15-2ac180c4d1c7.png)

I don't have anything else :-(

**Comment by bastienu** [comment]
Hey, this is because the account I was connected with was not the owner but only a collaborator of the repository... Maybe you could display a message, or authorize collaborators to publish ?

**Comment by lottamus** [comment]
@bastienu we've updated the error message to display more information if the authentication fails. We've also updated the permission check to allow publishing as long as you have "push" access to the repo. Can you try publishing again to confirm it's working for you?
