### ISSUE TITLE
Example references are not working in form mode

### ISSUE THREAD

**Issue by r1ckr** [stoplightio/studio#308]
**Describe the bug**
When creating examples to reuse in the same file or another file, it is not shown in the studio.

**To Reproduce**
Create an example under components:
```
components:
  examples:
    example-post-request-1:
      value:
        name: "John"
        lastname: "Doe"
```

Now add the reference in the operation:
```
    post:
      description: Create Example
      operationId: createExample
      tags:
        - examples
      parameters:
        - $ref: '#/components/parameters/example_header'
      requestBody:
        description: The example object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/example'
            examples:
              example-1:
                $ref: '#/components/examples/example-post-request-1'
```

You can see `example-1` in the form section, but you cannot see the value or the reference to it.

In the docs it shows OK though.

**Expected behavior**
I am expecting to see the actual value or reference in the form view, the same as with any other reference.

**Screenshots**
Here is what you see in the form section:
<img width="947" alt="Screenshot 2020-01-22 at 11 43 58" src="https://user-images.githubusercontent.com/1575507/72891657-9d871900-3d0c-11ea-81e1-f702587a113a.png">

**Environment:**
 - Studio version: 1.8.1.10501
 - OS: macOS 10.15.2
 - Browser: n/a

**Comment by michaelklopf** [comment]
The possibility to reuse test examples among all endpoints and the schemes would be great. This would also open up the possibility to use the examples in test cases and having one source of truth in form of the API documentation.

**Comment by checkin247** [comment]
@r1ckr @michaelklopf 
this seems to work for me with studio 1.10.2

![image](https://user-images.githubusercontent.com/12472764/76688564-3ad83c80-662e-11ea-9178-28434a2700ed.png)

**Comment by checkin247** [comment]
@r1ckr 
Reviewing that, I made this work by moving the example reference one level up.

yours:

```
examples:
   example-1:
      $ref: '#/components/examples/example-post-request-1'
```

working:

```
examples:
    $ref: '#/components/examples/example-post-request-1'
```

However, your version seems to be correct according to the [documentation from sagger](https://swagger.io/docs/specification/adding-examples) under"Reusing Examples".

After all, this issue seems to be related to #359

**Comment by r1ckr** [comment]
for me doesn't work @checkin247 , even moving it one level up doesn't show it in the form.

**Comment by checkin247** [comment]
@r1ckr You're right.
I understood the response is empty.
I can confirm that in form mode, the reference ($ref) is not displayed in example.
![image](https://user-images.githubusercontent.com/12472764/77052421-18974380-69cd-11ea-9ebf-b977f8ba9b1f.png)
So it isn't fixed.

**Comment by philsturgeon** [comment]
Recently we got Shared Responses and Shared Parameters, I believed Shared Examples might be on the cards.

@lottamus did we make any decisions? :D

**Comment by P0lip** [comment]
We should make sure to close https://github.com/stoplightio/studio/issues/435
