### ISSUE TITLE
Bug when trying to publish

### ISSUE THREAD

**Issue by SaintRain** [stoplightio/studio#309]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by rossmcdonald** [comment]
Please provide more information on the issue you're seeing.
