### ISSUE TITLE
Add option to export file as a different format (JSON/YAML)

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#312]
**User story.**

As a user, I can export a YAML file as JSON, so that I can write using the language I prefer and export the file in the format I need.

**Is your feature request related to a problem?**

I prefer to write YAML and YAML files are easier to view in a git diff. But a lot of external tools require JSON format.

**Describe the solution you'd like**

Rename the existing "Export OpenAPI" and "Export Model" context menus to be "Export to":
- "Export to -> Clipboard"
- "Export to -> New JSON file"
- "Export to -> New YAML file"

**Additional Context**

<img width="450" alt="notes___Studio___Stoplight" src="https://user-images.githubusercontent.com/7423098/72928029-ddee9300-3d1c-11ea-9d8c-95e19ba7d4aa.png">

**Comment by philsturgeon** [comment]
This was done a while back.
