### ISSUE TITLE
Clicking Docs for a Project without a connected git repo renders a 500 error 

### ISSUE THREAD

**Issue by rowa97** [stoplightio/studio#313]
**Describe the bug**
Clicking the Docs header for a project without a connected git repo renders a 500 error. 

**To Reproduce**

1. Create a project without a git repo 
2. Click the Docs header button 

**Expected behavior**
Preview the projects docs. 

**Screenshots**
![docs-error](https://user-images.githubusercontent.com/29557510/72934948-1f396f80-3d2a-11ea-904b-fcc3c0b0758c.gif)

**Comment by chris-miaskowski** [comment]
Looks good in 1.9 RC, closing!
