### ISSUE TITLE
Stoplight doesn't "detect" API files if numeric keys are used

### ISSUE THREAD

**Issue by BigBlueHat** [stoplightio/studio#315]
**Describe the bug**
If an OpenAPI document uses unquoted numbers for HTTP status codes, that API document will not be detected by Stoplight. Adding single quotes around the codes fixes the issue. Magically.

**To Reproduce**

1. "Open an existing folder" with one or more API docs in it
2. Stoplight will detect any of them that are properly using failsafe YAML (i.e. quote their status codes).
3. Stoplight will not detect any that aren't.

**Expected behavior**
I'd still like them to open, and show errors via Spectral or have them auto-quoted (though that would be more surprising...in a bad way).

**Comment by P0lip** [comment]
@BigBlueHat 
We should be [reporting](https://github.com/stoplightio/yaml/blob/master/src/parseWithPointers.ts#L329) those kind of errors.
![image](https://user-images.githubusercontent.com/9273484/73245915-f4469400-41df-11ea-84e2-e844e92928e6.png).

Could you hand me over a small YAML document that is lacking errors?

**Comment by BigBlueHat** [comment]
This is the Swagger v2 Petstore example doc converted (via http://editor.swagger.io/ UX) into OpenAPI 3.x. Their converter doesn't quote the HTTP Status Codes (nor does it throw errors about them missing...), so it's a great source for these broken YAML docs. 😢 

[petstore-converted.v1.txt](https://github.com/stoplightio/studio/files/4161561/petstore-converted.v1.txt)

**Comment by BigBlueHat** [comment]
If you import that file (or paste it's contents into "Code"), then errors are shown correctly. However, if you add the file to an existing project (and reload it) or create a new project from a folder containing it, then Studio doesn't recognize it as an API because it considers the YAML invalid (even though the YAML's just fine...it's just not "failsafe").

**Comment by P0lip** [comment]
> then Studio doesn't recognize it as an API because it considers the YAML invalid (even though the YAML's just fine...it's just not "failsafe").

Hmmm, that's an interesting observation.
Could you share a small piece of that file so that I can reproduce it?
Thank you in advance

**Comment by BigBlueHat** [comment]
You can use the [petstore one I linked above](https://github.com/stoplightio/studio/files/4161561/petstore-converted.v1.txt).

**Comment by philsturgeon** [comment]
@P0lip any luck diagnosing this one?

**Comment by P0lip** [comment]
@BigBlueHat @philsturgeon yeah, I could reproduce it. It's an issue we should fix.
My apologies for delayed response - had 2-3 similar issues in other repos and simply lost track of them at some point.

**Comment by philsturgeon** [comment]
@BigBlueHat this was fixed in an upstream dependency and should make its way into the next minor release of Studio Desktop. Keep an eye out for updates!
