### ISSUE TITLE
Changing a path does not update the mock server path

### ISSUE THREAD

**Issue by KatamariJr** [stoplightio/studio#316]
**Describe the bug**
Changing a path does not update the mock server path, the mock server route stays at the previous path.

**To Reproduce**
1. Given this OpenAPI document 
```
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
  license:
    name: MIT
servers:
  - {}
paths:
  /test:
    parameters: []
    get:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes: {}
```

2. Enable the Mock Server by clicking the 'Mock Server' button.
3. Change the path from '/test' to '/different'

**Expected behavior**
The mock server path should update to be at '.../different', but it still receives requests at '.../test'.

**Screenshots**
![image](https://user-images.githubusercontent.com/4542759/73106736-1e3f4400-3eca-11ea-96a1-a95f00ac5e4c.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.8.2 (Desktop)
 - OS: Windows 10

**Comment by lottamus** [comment]
@KatamariJr thanks for reporting! This issue has been fixed in Studio [v1.10.0](https://github.com/stoplightio/studio/releases/tag/v1.10.0).
