### ISSUE TITLE
My API is removed 

### ISSUE THREAD

**Issue by milad7ha** [stoplightio/studio#317]
I had account on stoplightio whit email ....@tinextco.com
I can recover my email.
1. forget password? click here 
2. enter email
3. email dose not send

also I have another account milad6...@gmail.com
I receive could recover my account but my API which I designed it, disappeared and I saw nothing.

All my project where on that

**Comment by rossmcdonald** [comment]
@milad7ha Can you open send an email to support@stoplight.io with your account information? We can take a look to see what might have happened.
