### ISSUE TITLE
Support linking to and editing of `externalDocs.url`

### ISSUE THREAD

**Issue by BigBlueHat** [stoplightio/studio#318]
**User story.**
Sadly not all our API docs are in API docs. :wink: Consequently, we use OAS's `externalDocs.url` option to link to internal wikis, etc. Sadly, we can't see them in Stoplight (other than in the Code view).

**Is your feature request related to a problem?**
It's harder than it should be to move between Stoplight and existing documentation referenced via `externalDocs.url`. 

**Describe the solution you'd like**
Add `externalDocs.url` linking to and editing of in the Preview and Form areas.

```
info:
  title: API
externalDocs:
  url: https://...
```

This combo can also appear in several places the API document, and it'd be handy to see/edit throughout.

Cheers!
🎩

**Comment by philsturgeon** [comment]
The new https://stoplight.io/open-source/elements/ will support linking to externalDocs at the top level in an "Additional Links" box. As we're closing this issue repo I'll mark this as done, please sign up for updates about Elements!
