### ISSUE TITLE
When creating an example for a number type property the example is created as a string instead of a number

### ISSUE THREAD

**Issue by adamreisnz** [stoplightio/studio#319]
**Describe the bug**
When creating an example for a number type property the example is created as a string instead of a number.

**To Reproduce**
Create a new property, select number type, edit additional properties, enter example number `5`

**Expected behavior**
For the example data to be in the correct number format, not string, producing valid YAML.

**Screenshots**
![image](https://user-images.githubusercontent.com/490562/73211336-efb6b700-41b0-11ea-8d78-9b7e55fc4c56.png)

![image](https://user-images.githubusercontent.com/490562/73211370-f9401f00-41b0-11ea-8536-c69fc3319931.png)

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.8.2 (1.8.2.10903)
 - OS: Mac

**Comment by johandalabacka** [comment]
Also reported in issue #292
