### ISSUE TITLE
Publish to a custom domain

### ISSUE THREAD

**Issue by adamreisnz** [stoplightio/studio#320]
**User story.**
As a company, I want to host the generated API docs on our own domain with our own branding, so that our API consumers feel like they are looking at our own product.

**Describe the solution you'd like**
- Able to have auto generated API docs publishable to our own domain
- Able to have custom branding of API docs
- Able to have some additional customisation options like fonts, colouring etc.

**Additional context**
This is possible with Swagger, but the API docs from stoplight look much better.

**Comment by lottamus** [comment]
Hey @adamreisnz, 

Custom domains, theming and branding are all in our [planned roadmap](https://stoplight.io/p/roadmap)! 

I'm interested to know if there are any specific parts of the page you are looking to customize other than the logo and buttons, links, text, and background colors? Thanks!

**Comment by adamreisnz** [comment]
Excellent, thank you, and nice to see you are using productboard.

Other than what you mentioned, yes perhaps the menu style, tables etc. It would be great if we could somehow overlay some custom CSS on top of what you've built so we can tweak just about anything we'd like really.

But I'll be happy if we can just adjust the basics initially, like logo, links, text etc.

Thanks!

**Comment by philsturgeon** [comment]
Done! Head over to [stoplight.io/welcome](https://stoplight.io/welcome) to claim a new workspace, then you can set up custom domains for that workspace. 

<img width="1110" alt="Screen Shot 2020-06-26 at 12 28 38 PM" src="https://user-images.githubusercontent.com/67381/85859322-473b6c00-b7bd-11ea-9b20-cf2b98d0517b.png">

Custom domains for a project are coming soon, but this should be a start. 👯 

More theming will be here shortly, its currently being tested, so head over there to get things started and ready for it.

**Comment by adamreisnz** [comment]
Great, now it should be just a matter of allowing us to redirect our subdomain via DNS to the new custom domain at stoplight 🎉

**Comment by adamreisnz** [comment]
Curious question: why font awesome for icons and not the more elaborate and free [Google Material icons](https://material.io/resources/icons/)?
