### ISSUE TITLE
Setting security for whole API / override it with no security on individual paths

### ISSUE THREAD

**Issue by johandalabacka** [stoplightio/studio#322]
It isn't possible to apply a security schema for the whole API

```yaml
openapi: 3.0.0
info:
  title: calc
  version: '1.0'
  description: Just a simple calculator api to be used to demo node-express and OAS
  contact:
    name: Johan Dahl
    email: johan.dahl@noreply.com
servers:
  - url: 'http://localhost:3000'
  - url: 'http://api.lth.lu.se/node-express-template'
security:
  - jwt: [] <-- this isn't possible in the Form of studio
```

and I can't override this by setting an empty security for an individual path

```yaml
'/sumdb/{term1}/{term2}':
    get:
      summary: Get sum of two numbers (db)
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SumResult'
          description: The sum
      operationId: get-sumdb-term1-term2
      description: Get sum of two numbers
      tags:
        - calculator
      security: [] <-- this is not possible in the form of studio
```

however if an empty security exists is it displayed as:

>Security
Overriding global security, setting this operation to NO security.

But I cannot set it like this in the Form

**Comment by marbemac** [comment]
@johnrazmus I suggest the following here:

The operation form already supports setting one or more security schemes:

<img width="682" alt="Screen Shot 2020-02-04 at 1 02 35 AM" src="https://user-images.githubusercontent.com/847542/73721708-78ba7a80-46ea-11ea-91c9-b1c4cb0f473e.png">

- [ ] Let's add a "No Security" option that is simply sets it to an empty array value, as described by @johandalabacka in original post and in the OpenAPI specification: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object. This is also applicable to OpenAPI v2.

We only support defining security schemes at the global level right now:

<img width="1598" alt="Screen Shot 2020-02-04 at 1 00 44 AM" src="https://user-images.githubusercontent.com/847542/73721996-2037ad00-46eb-11ea-8944-7494bbdfc953.png">

- [ ] For OpenAPI v3 and v2, let's add a section for "Global Security" that leverages the same component from the operation editor to allow the user to set the root/global `security` property (spec is same as operation, so can hopefully re-use a decent chunk of the operation security component).

**Comment by johandalabacka** [comment]
I see that in the latest version of Stoplight Studio (Version 1.11.0 (1.11.0.22031) you have implemented this:

![image](https://user-images.githubusercontent.com/9607173/79808838-49252100-836f-11ea-813e-90e796f25672.png)

However. If I set Disable Security for operation must I first set a security and then remove to completely remove the setting for one operation. It  would be nice to have means to remove No security directly

**Comment by wmhilton** [comment]
Ah, good point @johandalabacka! For an upcoming release we'll add the ability to _toggle_ the no security override.

**Comment by philsturgeon** [comment]
This has made it into v1.12.0. Upgrade now!

**Comment by johandalabacka** [comment]
Good work :)
