### ISSUE TITLE
When trying to login, the popup opens then closes right away.  Unable to login.

### ISSUE THREAD

**Issue by OpenTech2Me** [stoplightio/studio#323]
**Describe the bug**
When trying to login, the popup opens then closes right away.  Unable to login.  Using Windows 10

**Comment by marbemac** [comment]
Hi @OpenTech2Me, could you share a bit more information?

- Studio Web or Studio Desktop? 
- Which version of Studio?
- If you open the developer tools (`View -> Toggle Developer Tools`), do any errors show in the `console` tab when trying to login?
- Have you customized the value of the `Stoplight Enterprise API Url` value in the `settings` screen (accessible via little cog icon in bottom left)?
- Did login work in a prior version of Studio for you - if so, which version?
