### ISSUE TITLE
Readme preview shows only "object Object"

### ISSUE THREAD

**Issue by Primajin** [stoplightio/studio#327]
**Describe the bug**
When pressing the preview button on the Readme.md it just shows "object Object" instead of a rendering of the Markdown.

**To Reproduce**

1. Given a Readme.md in a freshly checked out repo via [myCompany].stoplight.io/studio
2. Click this button 📖 Preview
3. See just object Object

**Expected behavior**
A html/formatted rendering of the markdown.

**Screenshots**
![Screenshot 2020-02-05 at 16 28 01](https://user-images.githubusercontent.com/1742115/73855598-95fb6000-4834-11ea-81bc-6132696f8f1f.png)

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.9.0-build.11421 (d619ef0)
 - OS: OSX 10.15.3 (19D76)
 - Browser:
    -  Chrome Version 82.0.4049.0 (Official Build) canary (64-bit)
    -  Chrome Version 80.0.3987.87 (Official Build) (64-bit)
    -  Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
There is no error reported in the console

**Comment by lottamus** [comment]
Hey @Primajin ,

Thanks for reporting! We just released [v1.9.1](https://github.com/stoplightio/studio/releases/tag/v1.9.1) which includes a fix for this issue. Just restart your Studio Desktop or refresh your browser window and you'll be up to date.

Let us know if you run into any more issues!
