### ISSUE TITLE
`.github` folder showing in output documentation

### ISSUE THREAD

**Issue by BigBlueHat** [stoplightio/studio#328]
**Describe the bug**
For example: https://stoplight.io/p/docs/gh/stoplightio/studio/.github/ISSUE_TEMPLATE/bug_report.md

**Expected behavior**
Pretty sure most (probably all) `.` prefixed files should be kept out of documentation output.

**Comment by lottamus** [comment]
Hey @BigBlueHat are you still seeing this issue? It should be resolved once you re-publish your docs. By default, only things within the "/docs" and "/reference" directories should be included in your published docs.

We will soon be releasing a project configuration file which allows you to include/exclude certain files/directories from your published docs.

**Comment by BigBlueHat** [comment]
Yep! Looks like it's fixed. Thanks! And great to hear about the include/exclude feature!
