### ISSUE TITLE
Can't (easily) create an array of arrays

### ISSUE THREAD

**Issue by Primajin** [stoplightio/studio#331]
**Describe the bug**
I can't (easily) create an array of arrays - I need to "trick" the interface by using an intermediate object.

**To Reproduce**

1. Create a new operation, let's say GET
2. Click `noType` in Schema in order to change it to `array`
3. Another array can not be chosen as a subtype

**Expected behavior**
Allow to nest another array.

**Screenshot**
![Screen Recording 2020-02-11 at 15 31 55 (1)](https://user-images.githubusercontent.com/1742115/74246378-b4ee6c00-4ce4-11ea-87e4-bbb2bb0c1904.gif)

**Environment (remove any that are not applicable):**
 - Studio version: Stoplight Studio v1.9.0 Version 1.9.0-build.11816 (2cf72a1)

**Comment by P0lip** [comment]
This should be fixed in the next version, 1.12.

**Comment by philsturgeon** [comment]
This has made it into v1.12.0. Upgrade now!
