### ISSUE TITLE
'base path' is set but not reflected in 'Code Generation'

### ISSUE THREAD

**Issue by atshakil** [stoplightio/studio#335]
**Describe the bug**

"base path" doesn't appear in the `Endpoint Preview > Try It > Code Generation`,  even when "base path" is set from "API Overview".

**To Reproduce**

1. For any OpenAPI document, go to "API Overview (Form view)", and set "base api" (e.g. `/v1`)
2. From any end point (e.g. `/feeds`), go to `Preview > Try It > Code Generation`
3. See the generated code doesn't include "base api" (e.g. `http://example.com/feeds`)

**Expected behavior**

The generated code should include "base api" (e.g. `http://example.com/v1/feeds`)

**Environment:**
 - Studio version: Web
 - OS: MacOS 10.15.3
 - Browser: Chrome 80.0.3987.106

**Comment by lottamus** [comment]
@atshakil thanks for reporting! This issue has been fixed and released in Studio v1.10.0.
