### ISSUE TITLE
Publish Docs forcing me to login again & again

### ISSUE THREAD

**Issue by naidu0921** [stoplightio/studio#336]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button 'publish docs'
3. See error

Unable to access project for .... . Please try reconnecting your Gitlab account then try again.
If the problem persists, Report a Bug.

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by rossmcdonald** [comment]
@naidu0921 I've opened a ticket for you in our support portal. I'm going to go ahead and close this issue.
