### ISSUE TITLE
OAIv3 adding and removing a request body leaves empty `requestBody` object on operation

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#338]
## To Reproduce

- Within an OpenAPIv3 specification, add a request body to an operation
- Remove the request body

## Expected Results

- `requestBody` would be absent from the operation

## Actual Results

- `requestBody` is still present, but empty

## Notes

This is problematic because the [OpenAPIv3 `requestBody` attribute](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operation-object) has required attributes that are now not being met. The field should be removed entirely if there is not request body present.

<img width="700" alt="Screen Shot 2020-02-21 at 4 03 20 PM" src="https://user-images.githubusercontent.com/4060903/75075644-f096ec00-54c3-11ea-8245-b030c9bd28d7.png">

<img width="700" alt="Screen Shot 2020-02-21 at 4 03 47 PM" src="https://user-images.githubusercontent.com/4060903/75075653-f42a7300-54c3-11ea-85ba-41718105cb1a.png">

**Comment by philsturgeon** [comment]
Is this the same as https://github.com/stoplightio/studio/issues/264

**Comment by rossmcdonald** [comment]
@philsturgeon It is. I'll consolidate there.

**Comment by rossmcdonald** [comment]
Closing in favor of #264
