### ISSUE TITLE
Add support for OpenAPIv3 shared components in graphical designer

### ISSUE THREAD

**Issue by lottamus** [stoplightio/studio#34]
@rossmcdonald commented on [Tue Aug 06 2019](https://github.com/stoplightio/studio-internal/issues/486)

**User story.**
As a an API developer, I can re-use responses, requests, etc under the OpenAPIv3 `components` key within Studio without having to drop down into the code view.

**Is your feature request related to a problem?**
Currently if a user imports a specification that uses shared components (ie, for a response object), the "Forms" view functions as if there are no defined responses (see screenshot).

**Describe the solution you'd like**
A Forms view for shared component objects, like responses.

**Additional context**

![Screen Shot 2019-08-06 at 12 21 44 PM](https://user-images.githubusercontent.com/4060903/62561666-474d1900-b845-11e9-92af-2059e5224930.png)

![Screen Shot 2019-08-06 at 12 21 30 PM](https://user-images.githubusercontent.com/4060903/62561689-4d42fa00-b845-11e9-8af8-1dbd79a9cf36.png)

**Comment by philsturgeon** [comment]
This has some crossover with #4, maybe this supersedes that one.

**Comment by chris-miaskowski** [comment]
Good spot @philsturgeon - the solution I proposed in https://github.com/stoplightio/studio/issues/4 tries to prepare the UI for a generic case. The one doesn't block the other but we need to agree on UI.

**Comment by philsturgeon** [comment]
Let's track this work in https://github.com/stoplightio/studio/issues/4
