### ISSUE TITLE
Can't log in when trying to publish a doc

### ISSUE THREAD

**Issue by cynsupercat** [stoplightio/studio#340]
### Workaround

For anyone running into this issue, please try:

- Create a new Github repository, or find an existing repository, for storing your data
- Clone the repository in Studio using the "Open Git Project" option from the new project screen
- Publish from the connected project

---

**Describe the bug**
When attempting to publish a doc, it tells me that this project needs to be connected to a git repository. 

There is no way for me to do that. No option to connect to a git repo exists, the learn more link returns 404, and attempting to log in simply throws me back into the studio landing page in the pop up window.

**To Reproduce**
1. Create a new project (import from file)
2. Click on `Publish`
3. Click on learn more. It redirects you to https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/02-publishing.md?utm_campaign=publish_dialog&utm_source=studio which is a 404 on my end.
4. Click on log in button. You get to go back to the landing page. Yay.
![image](https://user-images.githubusercontent.com/39891200/75308963-d41ff880-58a3-11ea-88a7-6766ec2852f2.png)

**FYI I'm already logged in all through these steps. Not sure why  there's a log in button when I'm already logged in.**

![image](https://user-images.githubusercontent.com/39891200/75309081-10ebef80-58a4-11ea-97d4-1aaa8eec1d40.png)

**Expected behavior**
* Learn more should take me to a working page
* Log in shouldn't be there when I'm already logged in
* How to link a project to a git repo should be explained clearly. There are no options in the settings page to do that.

**Environment (remove any that are not applicable):**
 - Browser: Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by philsturgeon** [comment]
This has been put on the dev teams radar, and this issue will be updated when it's sorted out. I've had this once or twice and it's some sort of funny issue with cookies or something. They'll figure it out. :D

**Comment by vinczente** [comment]
I have same issue?

**Comment by alanreid** [comment]
I was experiencing the same issue with a private repository. Even though the user had admin access, I couldn't make it work. Making the repo public fixed it for me. 

Now I'm getting a 404 error instead of the published page, but I imagine that's an unrelated issue

**Comment by ijarinz** [comment]
> I was experiencing the same issue with a private repository. Even though the user had admin access, I couldn't make it work. Making the repo public fixed it for me.
> 
> Now I'm getting a 404 error instead of the published page, but I imagine that's an unrelated issue

I have the EXACT same issue. Had to turn repo public and published page displaying 404 instead :(

**Comment by chulucninh09** [comment]
Seemed like the problem happened to me too. Is this a problem with github or the problem of Spotlight itself? Instead of waiting, do we have any other workaround?

**Comment by vinczente** [comment]
@chulucninh09: when creating a new project start with the github url and then all should work

**Comment by philsturgeon** [comment]
Right, [v2 is out](https://stoplight.io/welcome)! 

The git integration is a lot nicer.

![git connect](https://user-images.githubusercontent.com/67381/85857878-f296f180-b7ba-11ea-8410-82a9e3442494.gif)

When you've got your project set up head over to Project Settings and enable the Webhooks.

<img width="1069" alt="Screen Shot 2020-06-26 at 2 40 57 PM" src="https://user-images.githubusercontent.com/67381/85857978-1b1eeb80-b7bb-11ea-9237-fcc2a49561c4.png">

You'll never need to click that publish button again, just merge PRs as you normally would.
