### ISSUE TITLE
Attempting to clone private Github org shows 404

### ISSUE THREAD

**Issue by jayshao** [stoplightio/studio#343]
**Describe the bug**
Problem creating project from private repo in Github organization

**To Reproduce**

1. Login with Github credentials
2. Enter private repo in my Github org
3. Studio starts creating the project (see it in project list) but errors with 404

**Expected behavior**
Project created based on files in Giithub repo

**Screenshots**
![Screen Shot 2020-03-02 at 3 14 59 PM](https://user-images.githubusercontent.com/205495/75713886-b0402680-5c98-11ea-8f73-efc206b562d7.png)

**Comment by rossmcdonald** [comment]
Hi @jayshao, I think this might be an OAuth issue. Can you verify that you authorized the Studio OAuth application for the organization the repo is in? If you find the app here:

https://github.com/settings/applications

And then visit the settings, it should show you which organizations it's authorized for.

**Comment by rossmcdonald** [comment]
For anyone who runs into this issue, we have an article that outlines the possible solutions [here](https://support.stoplight.io/hc/en-us/articles/360036914232-Unable-to-clone-Github-repositories).
