### ISSUE TITLE
Form mode edits rewrite the whole document rather than the section its intended 

### ISSUE THREAD

**Issue by r1ckr** [stoplightio/studio#346]
**Describe the bug**
When you are working in **code mode** and add some comments to the definition (which are extremely useful while development) Stoplight studio wipes them out the next time you modify something in the **form mode**.

**To Reproduce**
1. Write a comment (## My comment) in **code mode**
2. Add a new section or edit something in **form mode**
3. Go back to the **code mode** and your comment is gone

**Expected behavior**
I expect Stoplight Studio in form mode to rewrite only the section I am editing.

**Environment (remove any that are not applicable):**
 - Studio version: 1.9.2 (1.9.2.12599)
 - OS: [e.g. MacOS 10.15.3]

**Comment by philsturgeon** [comment]
Closing in favour of #480
