### ISSUE TITLE
Error "i.translateParameterObject is not a function"

### ISSUE THREAD

**Issue by nunom-santos** [stoplightio/studio#351]
The error "**i.translateParameterObject is not a function**" keeps appear for each time I change the file to visualize. 
The error started appearing today after 09:00 GMT, even after reverting the files to a previous version.
Yesterday, until my leave at 19:00 GMT the error did not show..

I reproduced the error on a new project by doing the following:
1. create an API named a.yaml;
2. created a path parameter named "a";
3. created a path parameter names "a";
4. created a model named "ab";

When I select the API file after unselecting, the error popups up as many time as I select the file after unselecting it.

**Screenshots**
![error_stoplight](https://user-images.githubusercontent.com/61286709/76308606-0d546180-62c3-11ea-8aaf-9abe47d06820.png)

 - Studio version: Web version
 - OS: Windows 10
 - Browser: Chrome 80.0.3987.116

**Comment by nunom-santos** [comment]
Sorry, I misspelled the procedure to reproduce the error.
Ignore step 3.

**Comment by gasugesu** [comment]
i have same problem in mac os catalina

**Comment by simundev** [comment]
I've got similar: `n.translateToPathParameter is not a function`

**Comment by ianbeck** [comment]
Same issue; the editor will be fine for a few minutes, and then a bunch of these errors will come down the pipe. A few more minutes of productivity, and then more errors. Really frustrating.

**Screenshots**
<img width="438" alt="Screen Shot 2020-03-10 at 11 20 30 AM" src="https://user-images.githubusercontent.com/51132374/76345794-2e1bb780-62c1-11ea-9f10-ac2680d83e45.png">

**Environment:**
 - Studio version: 1.10.1 (1.10.1.17062)
 - OS: macOS 10.15.2

**Comment by lottamus** [comment]
@nunom-santos @gasugesu @simundev @ianbeck thanks for reporting! A fix for this issue has been released in Studio Web and Studio Desktop [v1.10.2](https://github.com/stoplightio/studio/releases/tag/v1.10.2). 

Please let us know if you run into any more issues.
