### ISSUE TITLE
[v1.10.2] Error "i.translateParameterObject is not a function"

### ISSUE THREAD

**Issue by gasugesu** [stoplightio/studio#353]
Hello
I have installed latest version app from https://github.com/stoplightio/studio/releases/tag/v1.10.2. but having same issue #351. 
It seems this problem is not fixed.

**Comment by gasugesu** [comment]
OK, I found it.
The latest link [Mac Download] in this page(https://github.com/stoplightio/studio/releases/tag/v1.10.2) is NOT linked to the latest binary.
Please change the old link(v1.10.1) to the latest.
Thank you.

**Comment by rossmcdonald** [comment]
@gasugesu The link has been updated. Thanks for letting us know.
