### ISSUE TITLE
Generate Example from Schema

### ISSUE THREAD

**Issue by erik-hansen** [stoplightio/studio#355]
**User story.**
As an API designer, I can automatically generate, complete, or fix an example request/response body from the schema, so that I can begin with data compliant to the model schema.

**Is your feature request related to a problem?**
Stoplight Next allows me to click a "Generate From Schema" button to fill in example data compliant with the schema.  In Stoplight Studio, I must manually create the example without any validation that the example matches my schema.  This could lead to great confusion for my consumers when I provide example data that doesn't actually match the documented schema.

**Describe the solution you'd like**
Add the "Generate From Schema" button functionality from Stoplight Next into Stoplight Studio. Additionally, if I already have an example, I would like a way to validate my example against the schema to ensure it's complaint.

**Comment by philsturgeon** [comment]
Thanks for suggesting this! We've got it on the roadmap in productboard but it's good to see more interest in it here. 

There's two things in here:

1. We have spectral rules for validating various types of example, but they're disabled in Studio due to performance issues. @P0lip with all the performance gains recently, is now perhaps the time to bring those rules back? 

2. @erik-hansen do you actually _need_ to create these examples? Is there a specific tool in your tool chain that requires them? If properties have examples, defaults, enums, etc then a response example will be generated from the schema without you needing to take this extra step. It's one of the things I like the most about OpenAPI vs the older defunct description formats.

**Comment by erik-hansen** [comment]
Thanks @philsturgeon - Yes, example request and response bodies are helpful for demonstrating related values such as when my response object contains an array of pets, I want to provide an example response that has the most common pet types, with their relevant characteristics listed.  I don't believe that is something you can achieve through the property examples.

Also, you mention that the example will be generated from the schema.  Are you referring to a Prism mock response?  The docs generated by Studio do not have an example generated in the way you describe.

**Comment by philsturgeon** [comment]
@erik-hansen could you give me a minimal OpenAPI example with an operation that has a schema and example? I'd like to visualise what you're up to so I can see if there's a workaround whilst we wait for the button.

**Comment by marbemac** [comment]
We have all the functionality required to get this done without much effort.

I suggest a button on right side of example editor, between name and remove:

<img width="716" alt="Screen Shot 2020-07-07 at 11 18 26 PM" src="https://user-images.githubusercontent.com/847542/86876019-70a3a400-c0a9-11ea-9968-e1142ce27529.png">

Here is previous implementation re schema generation - should leverage similar options (also make sure schema being passed in to generate has remote $refs dereferenced): https://github.com/stoplightio/platform/blob/938f3d0df5ab505e2ea0fa43625dca44d2fdccb3/platform/src/utils/schemas/json-schema-faker.js.

**Comment by philsturgeon** [comment]
There was a discussion on Slack that when adding an example it would be rather nice if it _automatically_ generated the example from schema. 

Tweaking the JSON it gives you is going to be a lot easier than creating it all from scratch and looking to check property names, etc. Let's just automatically generate examples from schema and people can do what they wish. If they don't like it, or are copying in something else its not going to take any time at all to delete it.

**Comment by marbemac** [comment]
> There was a discussion on Slack that when adding an example it would be rather nice if it automatically generated the example from schema.

Meaning when click "+ Example" we add example and do equivalent of clicking the "Generate from schema" button for them? Or something else?

**Comment by philsturgeon** [comment]
Yep! The example will always be a variation of the schema (after all spectral will complain if it doesn’t match the schema) so just automatically populating the example box and saving them clicking an extra button 99% of the time is a nice user experience.

**Comment by marcelltoth** [comment]
I agree with @philsturgeon that this would be the best user experience. Tweaking with something existing is 99% easier than writing from scratch, especially if 50%+ of the content is fixed (the property names).

If you still don't want it, it takes a `CTRL-A + DEL` to clear it, like 200ms.

**Comment by philsturgeon** [comment]
@XVincentX to make the example that is created be as similar as possible to the JSON that Prism returns (assuming JSON), this would be openapi-sampler right?

**Comment by XVincentX** [comment]
OpenAPI Sampler for static examples, Json Schema Faker for dynamic ones
