### ISSUE TITLE
Broken link in Studio docs

### ISSUE THREAD

**Issue by dgrstl** [stoplightio/studio#358]
Reported by user:

> After I login and create a model or API and hit the Publish button, it tells me that “This project needs to be connected to a git repository before it can be published” with a link to “Learn More” and a Log In button.
The “Learn More” link takes you to https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/02-publishing.md?utm_campaign=publish_dialog&utm_source=studio which gives you a 404.

![foo](https://user-images.githubusercontent.com/2438381/76657169-32ed9f00-653f-11ea-8764-242ea97f43f5.gif)

**Comment by philsturgeon** [comment]
Fixed, it'll get deploy soon. Thanks for reporting this!
