### ISSUE TITLE
StopLight dont create a project 

### ISSUE THREAD

**Issue by brauliofabrizio** [stoplightio/studio#360]
Error creating project: Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: Failed to get 'documents' path Underlying stack: Error: Failed to get 'documents' path at electron/js2c/browser_init.js:6700:67 at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6565:27) at IpcMainImpl.emit (events.js:210:5) at IpcMainImpl.EventEmitter.emit (domain.js:476:20) at WebContents.<anonymous> (electron/js2c/browser_init.js:3861:23) at WebContents.emit (events.js:210:5) at WebContents.EventEmitter.emit (domain.js:476:20) at WebContents.emitter.emit (C:\Users\c16918\AppData\Local\Programs\stoplight-studio\resources\app.asar\node_modules\@sentry\electron\dist\main\integrations\electron.js:55:20) at WebContents.emitter.emit (C:\Users\c16918\AppData\Local\Programs\stoplight-studio\resources\app.asar\node_modules\@stoplight\reporter\node_modules\@sentry\electron\dist\main\integrations\electron.js:55:20) at WebContents.topLevelDomainCallback (domain.js:131:23)

**Comment by philsturgeon** [comment]
Sorry this is just a stack trace. If you're still experiencing the problem could you fill out the bug report template and give us a little more information?
