### ISSUE TITLE
Unhandled Exception: "Node with id [object Object] does not exist in the b tree"

### ISSUE THREAD

**Issue by jglassenberg** [stoplightio/studio#361]
**Describe the bug**
I encountered this issue "Node with id [object Object] does not exist in the b tree" when trying to create a new model from the context menu. Oddly it didn't happen when using the create button.

**To Reproduce**

1. Open a project with several models and APIS
2. In the models folder, right click -> new model

**Expected behavior**
A new model is created. But instead I get this seemingly server-side error.

**Screenshots**
https://drive.google.com/file/d/1DB6Dpd4Z2rJOFALSA5UKtgWXSCnX5Btd/view?usp=sharing

**Environment (remove any that are not applicable):**
 - Studio version: web
 - OS: latest mac
 - Browser: chrome 80.0.3987.132

**Additional context**

**Comment by P0lip** [comment]
This will be fixed in the next release.

**Comment by P0lip** [comment]
The fix is out
