### ISSUE TITLE
"Error activating project" when loading existing project

### ISSUE THREAD

**Issue by hotmeteor** [stoplightio/studio#362]
**Describe the bug**
When attempting to open up an existing project an "Error activating project" error is thrown, with instructions to check the dev tools. Dev tools revealed the following errors:

![Screen Shot 2020-03-18 at 7 35 59 AM](https://user-images.githubusercontent.com/378585/76961331-312f2d00-68eb-11ea-953d-ddb17bd6c63b.png)

**To Reproduce**

1. Save a project that is connected to Github
2. Close the Stoplight app
3. Reopen Stoplight app

**Expected behavior**
I expect to be able to reopen the project and keep working on it.

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.2 (1.10.2.17323)
 - OS: Mac 10.14.6

**Additional context**
The 404 error returns information from Github:
```json
{
  "message": "If you would like to help us test the Additional information about branches and PRs during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.",
  "documentation_url": "https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit"
}
```

**Comment by lottamus** [comment]
@hotmeteor thanks for reporting! How often is this happening for you? Does it happen for every project? Do you have a particular project we use to reproduce? Thanks!

**Comment by hotmeteor** [comment]
It happened with my first project which is a private repo. Can't really share the repo with you, sorry. Happy to share any other logs or errors though if you have somewhere I should be looking.

**Comment by lottamus** [comment]
Hey @hotmeteor, we've just pushed a potential fix to [Studio Web](https://stoplight.io/p/studio). Can you give it a try and verify it fixes the issue for you? Thanks! https://stoplight.io/p/studio

**Comment by hotmeteor** [comment]
@lottamus Sorry for the delay, Chris. I actually restarted the project because I was blocked, so I'm unable to verify at this point. Thanks for chasing it down though.
