### ISSUE TITLE
Documentation for extended types not properly generated

### ISSUE THREAD

**Issue by chavdarb** [stoplightio/studio#363]
**Describe the bug**
Parent fields missing from extended types in the generated documentation. This works in the preview tab.

**To Reproduce**

1. Given this OpenAPI document
[busunessevents.v1.yaml.zip](https://github.com/stoplightio/studio/files/4353124/busunessevents.v1.yaml.zip)

2. Click this button 'Publish'
3. See the generated documentation for extended types e.d. Identify.

**Expected behavior**
It is expected, that fields from parent type are shown in child type, in similar way to the preview pane.

**Screenshots**
Screenshot for preview pane.
![image](https://user-images.githubusercontent.com/4180780/77041787-3495e780-69c3-11ea-989a-44db1a4de210.png)
Screenshot of the published documentation.
![image](https://user-images.githubusercontent.com/4180780/77041825-44adc700-69c3-11ea-8de3-a866e670884c.png)

**Environment (remove any that are not applicable):**
 - Studio version: 
Stoplight Platform v1.10.0
Version 1.10.0-build.16127 (5b73368)
Built on Tue, Mar 3, 2020, 3:45:33 AM GMT+2
![image](https://user-images.githubusercontent.com/4180780/77042031-aa01b800-69c3-11ea-8717-2e9da5bd7224.png)

 - OS: Windows 10
 - Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

**Comment by philsturgeon** [comment]
If there's a discrepancy between the published docs and Studio Desktop's "Preview" pane its likely because your Studio Desktop is out of date. The latest is v1.10.3 so could you give it an update and see if that solves the problem?
