### ISSUE TITLE
Pull failed with: Merges with conflicts are not supported yet.

### ISSUE THREAD

**Issue by rikterbeek** [stoplightio/studio#366]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**
I provide manually changes into the stoplight studio but want to revert to the current master. If I press "Pull latest from git repo" it provides the error "Pull failed with: Merges with conflicts are not supported yet." sometimes it works to go to the GIT code copy the code into the editor and press the button again but this solution now does not work. How can you ignore your local changes and go to the latest version available on GIT.

**To Reproduce**

1. Open stoplight studio
2. Make local changes in stoplight studio
3. Make changes in the git repo or another user make changes in stoplight studio
4. Click the Pull latest from git repo

**Expected behavior**
Ask if you want to replace your local changes with external code. If yes overwrites local changes
Or at least able to force to git version to resolve the issue.

**Environment (remove any that are not applicable):**
 - Studio version: V1.10
 - OS: MacOs
 - Browser: Chrome

**Comment by philsturgeon** [comment]
Thanks for reporting. For now this is expected. The happy paths are covered nicely with [our built in git support](https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/04-common-git-tasks.md), but certain more advanced tasks (revert, rebase, merge), etc you're going to want to switch to a dedicated git client. Do whatever you gotta do with your favourite terminal then Ctrl/CMD + R to get Studio back up to date.

Improvements to git come with every new release, as the chap who is doing amazing work on isomorphic-git also works here. The better isomorphic-git gets, the better Stoplight gets at handling certain tasks, and [IG v1.0.0 was just released](https://isomorphic-git.org/blog/2020/02/25/version-1-0-0). 🥳

**Comment by brandonjmckay** [comment]
How can you handle this in the web studio version for now?
Once there's a merge conflict, how can you get the web version to be reverted?
