### ISSUE TITLE
Parameter style and explode are not supported in rendered docs

### ISSUE THREAD

**Issue by Hipska** [stoplightio/studio#367]
I'm using an advanced [parameter](https://swagger.io/specification/#parameterObject) design and came to the conclusion that Stoplight is not respecting the `explode` field.

Simplified version of my spec:

```yaml
components:
    schemas:
        FunctionalCI:
            title: Functional CI
            type: object
            properties:
              name:
                type: string
                description: Name
              description:
                type: string
                description: Description
              org_id:
                type: integer
                description: Organization
              organization_name:
                type: string
                description: Organization name      
        Server:
            title: Server
            allOf:
              - $ref: '#/components/schemas/FunctionalCI'
              - type: object
                properties:
                  nb_u:
                    type: integer
                    description: Rack units
                  cpu:
                    type: string
                    description: CPU
                  ram:
                    type: string
                    description: RAM
                  disk:
                    type: string
                    description: Disks
    parameters:
        Server:
          name: server
          schema:
            $ref: '#/components/schemas/Server'
          explode: true
          in: query
          description: Server
          style: deepObject
```

In the forms mode I then select this as query parameter for the path method:
![image](https://user-images.githubusercontent.com/228588/77523511-22fe8500-6e86-11ea-9364-a8a2cfb70930.png)

Which results in the following doc:
![image](https://user-images.githubusercontent.com/228588/77523529-2abe2980-6e86-11ea-9387-b541e6988de2.png)

In this case I would expect the docs to show following parameters:
* `server[name]` _string_ **Name**
* `server[description]` _string_ **Description**
* …

I also tried different `style` and `explode` values, but they all don't have any effect. So it seems that parameter of type `object` does not seems to be supported?

**Comment by philsturgeon** [comment]
I can confirm that explode is not currently used by the docs tool. We've got support for about 80% of keywords in docs, with most of the remaining 20% being keywords I didn't even know existed until I came up with a way to track them. We'll get this as close to 100% as we can.

@lottamus putting this on your radar.

**Comment by philsturgeon** [comment]
This got sorted out, expect to see improvements in v1.12 coming out any day, and more improvements coming in v2.0. 🎉
