### ISSUE TITLE
.stoplight.json exclude ignored

### ISSUE THREAD

**Issue by r1ckr** [stoplightio/studio#368]
**Description:**
Stoplight is ignoring the **exclude** inside **.stoplight.json**, I am following this documentation:
https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Basics/03-stoplight-config.md

**To Reproduce**
Created a .stoplight.json file at the root of the project with the following:
```
{
  "formats": {
    "openapi": {
      "rootDir": "reference",
      "include": ["**"],
    },
    "markdown": {
      "rootDir": "docs",
      "include": ["**"]
    },
    "image": {
      "rootDir": "assets/images",
      "include": ["**"]
    },
    "json_schema": {
      "rootDir": "models",
      "include": ["**"]
    }
  },
  "exclude": ["internal"]
}
```

Create a directory called `internal` and drop an openapi in there, open the project with stoplight and see how that folder is shown when editing and preview publishing

**Expected behavior**
I am expecting not to see that directory in stoplight, or at least not to show it in the publish preview.

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 1.10.2.17323]
 - OS: [e.g. macOS 10.15.3]

**Comment by P0lip** [comment]
@r1ckr 
Hey!
You are missing the leading slash in `exclude`.
Please try the following `"exclude": ["/internal"]`
LMK whether it does the trick for you.

**Comment by philsturgeon** [comment]
@P0lip this could well be a little confusing. To many people, myself included, `/` means root on the harddrive. I have never seen a leading slash used in paths for any other reason than root filepath. So if this project was '~/src/myapi/` and there was `~/src/myapi/internal` I would expect `/internal` to be a reference to literally `/internal` not `/Users/phil/myapi/internal`...

**Comment by r1ckr** [comment]
@P0lip, The trailing slash worked. 

I just want to clarify that beside of what @philsturgeon says, which is completely right. I pasted the link to the official documentation indicating relative paths without the trailing slashes.

One more thing, the rest of the configuration doesn't seem to need the trailing slashes. 

I've created this PR to update the documentation: https://github.com/stoplightio/studio/pull/371

**Comment by P0lip** [comment]
> To many people, myself included, / means root on the harddrive.

Yeah, I agree. In our case, it points to the root of current project, but this in fact may seem confusing.

> So if this project was ~/src/myapi/ and there was ~/src/myapi/internal I would expect "exclude": ["/internal"] 

In general, we don't allow playing around with files outside of project directory, so this is not a concern here, but I agree.

**Comment by philsturgeon** [comment]
We don't allow playing with files outside of the root sure, but the confusion still stands. It's uncommon to _need_ to do this. See .gitignore.

**Comment by P0lip** [comment]
Yeah, I totally agree with you.

**Comment by P0lip** [comment]
Hey, just wanted to let you know that I've already got the fix merged.
It's unlikely that the change will make its way in 1.11 since I missed the merge window, but it should be released in one of the next versions.
I'll let you know once it's out.

**Comment by P0lip** [comment]
This will be out in v1.12, expected to be released soon.
