### ISSUE TITLE
Stoplight studio does not sync with external changes

### ISSUE THREAD

**Issue by svassaux** [stoplightio/studio#369]
**Describe the bug**
No correct sync with git status

**To Reproduce**

When I make changes
I commit externally with my terminal because I don't want to push changes
I make other changes with stoplight
Commit again and then push to the repo
If I reload stoplight pulls the last commits, ok (I have to do it manually, changes are not detected automatically)
But when I click on the commit buttons, everything I have changed is still marked as changed despite I have pushed and my git changelog is empty

**Expected behavior**

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.2
 - OS: windows 10

**Comment by philsturgeon** [comment]
Duplicate of #210.
