### ISSUE TITLE
No support for $ref under a pathname

### ISSUE THREAD

**Issue by svassaux** [stoplightio/studio#370]
**Describe the bug**
When including a $ref under a pathname, stoplight does not take it into consideration

**To Reproduce**

The following results in a blank form

1.	> paths:
2.	  /users:
3.	    $ref: '../resources/users.yaml'
4.	  /users/{userId}:
5.	    $ref: '../resources/users-by-id.yaml'
https://swagger.io/docs/specification/using-ref/

**Expected behavior**
Respect of the open api v3 spec for ref under a pathname

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.2
 - OS: windows 10

**Comment by philsturgeon** [comment]
Thanks for reporting this @svassaux, we're already tracking this under #202.
