### ISSUE TITLE
Unable to use Stoplight Studio Behind Corporate Proxy. 

### ISSUE THREAD

**Issue by gorishagh** [stoplightio/studio#372]
Unable to create a project when behind corporate proxy. Is there any way to set proxy info?
Version 1.10.2 (1.10.2.17323)
OS: Mac

Best,
Goris.

**Comment by rossmcdonald** [comment]
We are aware of this limitation, and have an issue open with #201 for addressing and documenting how users should work with Studio behind a proxy. Please follow that issue for future updates in this area.
