### ISSUE TITLE
x-faker gets deleted when adding additional properties to a field

### ISSUE THREAD

**Issue by Michael-Dawkins** [stoplightio/studio#375]
**Describe the bug**
We use stoplight studio to write an API where we use PRISM's nice mocking features where we can generate more realistic data with the x-faker properties, to instruct faker.js data generation.
Though As soon as we keep on working on a property, by adding an additional property to it, we loose our custom "x-faker" attribute.

**To Reproduce**
In an open API document:
1. Set x-faker: random.number (or other) on a property, in code
1. switch to form view
1. Add any additional property to the field, like a format
1. switch to code
1. The x-faker attribute is lost

**Expected behavior**
I expect the x-faker attribute not to be delete.
Or, better, to be able to set it in the form view. But that is more of a feature request.

**Screenshots**
![bug-x-faker](https://user-images.githubusercontent.com/1378983/78381084-21933200-75d5-11ea-807d-5c297a42c7d9.gif)

**Environment**
 - Studio version: 1.10.2
 - OS: MacOs 10.15.3

**Comment by philsturgeon** [comment]
This has made it into v1.12.0. Upgrade now!
