### ISSUE TITLE
Removing numeric validations leaves empty string

### ISSUE THREAD

**Issue by emorale112** [stoplightio/studio#376]
**Describe the bug**
Deleting minLength/maxLength/minimum/maximum/multipleOf within Params does not delete the entry but leaves it as an empty string. This occurs for path, query, and header param validations.

**To Reproduce**

1. Add minLength/maxLength/minimum/maximum/multipleOf
2. View code - Value is set
3. Delete the value
4. View code - an empty string is left

**Expected behavior**
delete the entry from code

**Screenshots**
![2020-04-01_16-07-09 (1)](https://user-images.githubusercontent.com/23023200/78396952-e5040e00-75b5-11ea-8766-f4382d6794ec.gif)

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0

**Comment by marbemac** [comment]
Fixed
