### ISSUE TITLE
Tags created in Forms view not added to top-level tags attribute

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#377]
## To Reproduce

- Create API
- Create endpoint
- Add tag to an endpoint

## Expected Results

Tag is applied to operation AND added to top-level tags attribute.

## Actual Results

Tag is applied to operation, but is not added to top-level tags attribute.

## Misc

While the specification states that this is not a requirement (which would make the spec invalid), there is also a default Spectral rule that flags this as a warning: `OpenAPI object should have non-empty 'tags' array.` which makes me think that Studio should Do The Right Thing here and also add it to the top-level tags attribute.

**Comment by wmhilton** [comment]
Closed in https://github.com/stoplightio/platform-internal/pull/1975

**Comment by wmhilton** [comment]
Er... didn't mean to close this until 1.12 is released.

**Comment by lottamus** [comment]
@rossmcdonald a fix for this issue has been included in Studio Desktop [v1.12](https://github.com/stoplightio/studio/releases/tag/v1.12.0) 🎉
