### ISSUE TITLE
Wrap long enum list

### ISSUE THREAD

**Issue by emorale112** [stoplightio/studio#379]
**Chore summary**
Prevent characters to run off-screen - wrap

**Tasks**
- [ ]items.enum with many values needs to wrap to a new line

**Additional context**
![2020-04-03_16-52-01](https://user-images.githubusercontent.com/23023200/78408010-b2651000-75cb-11ea-84d0-63f92f363b7c.png)

**Comment by philsturgeon** [comment]
This is being taken care of in with elements. https://stoplight.io/open-source/elements/
