### ISSUE TITLE
Route /nodes.hash does not exist when publishing 

### ISSUE THREAD

**Issue by alanwill** [stoplightio/studio#382]
**Describe the bug**
Using Studio Version 1.11.0 (1.11.0.22031) and when publishing, getting `Route /nodes.hash does not exist` error. Also suddenly unable to commit as well to GitHub with a `HTTP Error: 404` error received.

**To Reproduce**

1. Given this OpenAPI document 
2. Click this button Commit or Publish
3. 404 error when clicking on Push to Commit and `Route /nodes.hash does not exist` when attempting to Publish. Both worked perfectly before.

**Expected behavior**
Publish succeed and return URL of published view and for commit to push successful with no error.

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.11.0 (1.11.0.22031)
 - OS: macOS 10.15.4
 - Browser: Version 81.0.4044.92

**Comment by JonDotsoy** [comment]
**Environment**

- Studio version: Version 1.11.0 (1.11.0.22031)
- OS: macOS 10.15.3 (19D76)
- Browser: Stoplight Studio APP

![image](https://user-images.githubusercontent.com/3086539/78743955-343b9d00-792e-11ea-9ccf-e727d67cfd70.png)

**Comment by MinaAndLuoXia** [comment]
Me too,+1

**Comment by waliente** [comment]
Me too, +1

**Comment by KeiichiHonma** [comment]
Me too, +1

**Comment by vancata-80** [comment]
Me too, +1

**Comment by lutchobandeira** [comment]
Me too, +1

**Comment by Jean-Regis** [comment]
+1

**Comment by danillos** [comment]
Me too, +1

**Comment by Maks-Jago** [comment]
I have the same problem. +1 from me

<img width="307" alt="Снимок экрана 2020-04-08 в 19 46 40" src="https://user-images.githubusercontent.com/1841811/78810899-b29d4b00-79d1-11ea-910a-dfbaa7422f6a.png">

**Comment by rossmcdonald** [comment]
Thanks everyone. We just a pushed a fix for this issue, so let us know if anyone continues to see errors.

**Comment by alanwill** [comment]
Thanks @rossmcdonald that did fix publishing but Git push still doesn't work. I getting the following error still:

![image](https://user-images.githubusercontent.com/1929792/78846432-a1980e00-79c0-11ea-9076-6a226ba01280.png)

Is this related?

**Comment by rossmcdonald** [comment]
@alanwill I believe that's unrelated to this issue. I think you may be running into [what's described here](https://support.stoplight.io/hc/en-us/articles/360036914232-Unable-to-clone-Github-repositories), but not 100% sure. 

Feel free to send an email to support@stoplight.io if you continue seeing issues and we can take a closer look.

**Comment by alanwill** [comment]
@rossmcdonald thanks for that hint. I ended up having to re-auth with github and that worked.
