### ISSUE TITLE
Move "discard changes" away from the commit button.

### ISSUE THREAD

**Issue by sgebb** [stoplightio/studio#385]
It's way too easy to accidentally revert all your changes, it also doesn't give you any "are you sure?" warning, and it's hard to tell what you actually reverted.

**Comment by philsturgeon** [comment]
We've deployed the new Stoplight Platform which bundles a newer version of Studio Web. 

Check it out: https://stoplight.io/welcome

<img width="601" alt="image" src="https://user-images.githubusercontent.com/67381/85858232-92547f80-b7bb-11ea-9445-81cfb3750e34.png">

If you were using Studio Desktop then the same UI will be coming your way shortly in v2.0.
