### ISSUE TITLE
Repeated alert for unspported transport protocoll

### ISSUE THREAD

**Issue by checkin247** [stoplightio/studio#387]
**Describe the bug**
I am getting the following dialog about every minute. I do not want to use https, its getting very anoying to close that message every minute
![image](https://user-images.githubusercontent.com/12472764/78890927-d199ec80-7a66-11ea-9b98-0fc23f2d2b2f.png)

**To Reproduce**
Manage a project with git and ssh protocol

**Expected behavior**
Allow to not translate the git protocol and stop sending those alerts

**Environment (remove any that are not applicable):**
 - Studio version: [1.11.0]
 - OS: [Windows 10]
 - Browser: [electron 8.0.0]

**Comment by checkin247** [comment]
Feature can be turned off entirely by disabling "auto pull" in settings.
![image](https://user-images.githubusercontent.com/12472764/79227463-35a22380-7e60-11ea-970a-855e4b2ee9c7.png)

I still believe you @philsturgeon  may want to look into this.

**Comment by philsturgeon** [comment]
This has made it into v1.12.0. Upgrade now!

**Comment by checkin247** [comment]
@philsturgeon 
It will continue prompting you for unsupported transport protocoll in version v1.12.0 .
