### ISSUE TITLE
Studio Type Arrays - Valid by Default

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#388]
**User story.**
As a Studio user who prefers to use Forms, and is not super familiar with OpenAPI v2/v3, JSON Schema, or the subtle but meaningful differences between them, I want to use the Forms view to generate OpenAPI descriptions for my API, so I can then use those descriptions in a variety of OpenAPI tooling. Having valid OAS is important to these tools, and I assume whatever Stoplight does it always going to be spec-compliant OAS, unless it asks me specifically if I'd like to do something else.

**Describe the solution you'd like**

The editor allows multiple types to be defined in a list for a field in a schema. I can select any number of types, and Forms will places them all into a single `type` field:

```yaml
type:
  - string
  - 'null'
  - number
```

This is perfectly valid JSON Schema, but it's invalid OpenAPI v2, or OpenAPI v3.0. It IS valid 3.1... 

Neither OAS2/OAS3.0 has a "null" type, and neither OAS2/OAS3.0 has “type arrays" (having multiple types). Our tooling (specifically JSON Schema Editor) uses “null” and type arrays, so we’re technically letting users create invalid descriptions without letting them know, or getting confirmation that they want to do that.

## Background

We currently allow this because some tools, like ReDoc, allow this and we have customers who take advantage of it. We also used to support it in all of our tooling in Next and have continued the practice, but with Studio letting people plug and play various tools more readily, being spec compliant by default is far more important than it was in the past. This is the last remaining place where we bend the rules to a point of breaking them. 

We want to continue to support those customers who use this, but we don't want to confuse newer users who expect the default to be spec-compliant.

## Nullable

Neither OAS2 or OAS3.0 allow `"type: 'null'"` or  `"type: ['null']"`, so if the null type is selected in JSE then we should output the following:

```yaml
# oas2
type: string
x-nullable: true  # the x- means this is an extension

# oas3.0
type: string
nullable: true

# what we do now (JSON Schema) 
type:
  - string
  - 'null'

# oas3.1 (same as what we do now, as nullable was removed)
type:
  - string
  - 'null'
```

😅🤪🤔🤯🤨😞 right? Nobody is excited but the point is the divergence has been solved in 3.1, yay, but until then we have to handle these variations. 

Studio needs to be aware of if its editing an OAS2 or OAS3.0 file, then use the appropriate keywords. We did this for OAS3 `deprecated` vs OAS2 `x-deprecated` recently #223, so it seems like we can add a hack to do something similar. 

It will almost certainly be a hack, and this hack will have limitations. The way studio detects OAS2/OAS3/"JSON Schema" is currently somewhat flawed. If there is `swagger: 2.0` then its OAS2, if `openapi: 3.0.x` then its OAS3, otherwise if it looks like it might be a JSON Schema (type: foo was found) then we'll go with that. This is a bit of a simplification, but its roughly the case. 

This means, even after this change, JSE will not be able to help anyone who is using $ref to external files for their models, because we have no way of knowing if the $reffed model is "JSON Schema Proper" or "OpenAPI Schema Object". Looking out for $schema will help here moving forwards, but there wont be any $schema showing up for any models $ref'ed by OAS2 or OAS3 because that breaks then. Ugh.

This is being attacked systematically across all of our tooling post-v2, with "multiple dialect support". This issue is about giving us a quick win on the nullable situation ASAP.

## Multiple Types

JSON Schema allows multiple types, but OAS2 and OAS3.0 do not. 

To support multiple types in OpenAPI v3.0 you need to wrap them in a oneOf.

```yaml
oneOf:
  - type: string
  - type: number
  - nullable: true
```

OpenAPI v2 does not support oneOf, so this workaround is not possible.

Let's add a Project Setting: 

- [ ] Allow type arrays in OpenAPI v2.0/v3.0 (?) 

This means any $reffed models will always get type arrays. Any models that appear inside an OAS2/3.0/3.1 will support type arrays when they're allowed, OAS3.0 will oneOf if this is off, and OAS2 will only allow one type to be selected when off (selecting a second will just change it to that type instead of selecting multiple). 

I would suggest we leave this setting off by default, and communicate the change in our release notes. Studio and Spectral issue warnings about type arrays anyway. If we are warning people not to do it, making Forms not do it seems like a sane default.

**Additional context**

This solution would take care of #132 without us needing to add support for nullable more formally, which is great as nullable is deprecated in OAS3.1 and will go away in OAS4.

This has been reported as an issue several times in various places:

- #295
- #190

Let's make sure we let @kag0 @kovah @krishnajangid @johandalabacka and @rossmcdonald about this when it's fixed.

**Comment by marbemac** [comment]
The nullable bit is totally doable.

---

Don't forget about OpenAPI 3.1! So close :)

---

I am a bit concerned on the automatic `types` -> `oneOf` thing. It's more complicated than one might think, and there are a meaningful number of cases to consider to end up at a reasonable UX. More cases means more surface area for bugs and confusing things occurring if we attempt too much magic on behalf of end user.

Here are just two of a bunch of ux weirdness we'd have to figure out:

1. What does the JSE render if the openapi model already types as an array prop? What happens when they make a change to the type in this case, do we try to somehow preserve this preference for type arrays, which is tricky? Or do we automatically turn it into oneOf.
2. If user chooses two types, and we magically turn it into a oneOf under the hood, the editor would somewhat jarringly change from those two selected types to a oneOf. IMHO this could be rather confusing. E.g. in the image below if I select "number", and under the hood we translate that to a oneOf, unless we put in logic to try to handle this situation it would immediately make `oneOf` active in the editor, and deselect the types.

<img width="352" alt="Screen Shot 2020-04-09 at 7 31 39 PM" src="https://user-images.githubusercontent.com/847542/78951724-bd6ee300-7a98-11ea-8488-02483647e8b5.png">

Note that this issue was made worse because Spectral reported a nonsensical error for type arrays - "property should have required proptery $ref". So confusing. This PR improves the situation so at least things are more clear - https://github.com/stoplightio/spectral/pull/1071. New message is more like "the `type` property must be a string instead of an array".

---

A far simpler alternative that introduces less change for bugs or weird UX is to display a warning note below the types in the JSE when selecting multiple types in the context of OAS2 or OAS3.0 to let the user know if they need strict compliance they should use `oneOf`. At least until we have full multi-dialect support or, even better, openapi 3.1 is out and in use.

**Comment by philsturgeon** [comment]
> The nullable bit is totally doable.

🥳

> Don't forget about OpenAPI 3.1! So close :)

Sadly we're really not even at v3.1.0-RC0 yet, despite it being released "any day now" since October 2019. Long story behind that for elsewhere. Then, we either need to offer a Stoplight replacement for every tool in users toolchain, or every other vendor our users integrate with need to be on 3.1.0, and that's gonna take months. 

We can't rely on 3.1.0 to solve this problem, we can only rely on v3.1.0 to one day help us delete whatever hacks we make now to get our users there. We might rely on these short term solutions for a year or more.

> 1. What does the JSE render if the openapi model already types as an array prop? What happens when they make a change to the type in this case, do we try to somehow preserve this preference for type arrays, which is tricky? Or do we automatically turn it into oneOf.

How about this. 

_JSE will understand anything on read, but write always write things "correctly"._

If you've not enabled the type array option, and you've got type arrays, then updating the form is gonna make things rewrite as a oneOf, because Studio Forms is spec compliant by default. 

If you dont want to get your type arrays rewritten as oneOfs, you're clearly technically aware enough to google about or look for our project setting. You can revert it and enable type arrays.

Either way, those users getting oneOfs will, by default, get something which works everywhere, it's just not preferable. They have a preference option they can enable. 

> 2. If user chooses two types, and we magically turn it into a oneOf under the hood, the editor would somewhat jarringly change from those two selected types to a oneOf. IMHO this could be rather confusing. E.g. in the image below if I select "number", and under the hood we translate that to a oneOf, unless we put in logic to try to handle this situation it would immediately make oneOf active in the editor, and deselect the types.

See 1 🥳 

I don't know if this is confusing. I think this is awesome.

**Comment by philsturgeon** [comment]
> A far simpler alternative that introduces less change for bugs or weird UX is to display a warning note below the types in the JSE when selecting multiple types in the context of OAS2 or OAS3.0 to let the user know if they need strict compliance they should use oneOf

We will need to have a similar UI for OAS2 regardless, because OAS2 does not have oneOf. 

If we want to do the same thing for OAS3 initially, then follow it up with another PR a few weeks later which adds auto-oneOf as described in my last comment, this will stop people having to figure out how oneOf works (which is quite tricky for the sorts of user personas who are using Forms)

I'd be happy with doing it all at once or doing it piecemeal to spread the load, and make some users happier sooner and some even happier later.

**Comment by dpashkevich** [comment]
I came here from #132. We're trying to incorporate a tool ([Committee](https://github.com/interagent/committee)) in our development process that would validate our API implementation against the OAS3 schema file, and Stoplight not properly handling nullable definitions is a showstopper. 

A viable workaround would be to manually add `nullable: true` to nullable schema properties in the code editor but... when you use the Form editor it erases all unrecognized fields 😭 

Any update on this?

**Comment by philsturgeon** [comment]
@dpashkevich you might actually be uniquely positioned to navigate this awkward OAS Schema <!=> JSON Schema discrepancy as Comittee is happy to take OAS Schema or JSON Schema. 

If you are trying to produce 100% legit JSON Schema, you don't want `nullable: true`, you want a type array with "null" as one of the types, which is what Studio currently does (although this issue is pointing out that Studio should not).

If you are trying to produce 100% legit OpenAPI Schema Objects, you do want `nullable: true`, which is #132.

We'll be out of this mess with a few small workarounds and eventually fully out now that [OAS 3.1 has resolved its divergence from JSON Schema](https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09/), but there's gonna be some niggles to navigate on our way there.

**Comment by dpashkevich** [comment]
Thanks for a quick response!

This may be one of the workarounds for us to try. We currently author our API specification in OAS 3.0 format using Stoplight and prefer it this way, so we'd have to find a tool that converts OAS 3.0 (with the technically invalid type array that Stoplight Studio produces) to JSON Schema just for the tests.

As I mentioned I'd be happy to write `nullable: true` in our OAS file, if only Stoplight Studio would stop erasing it every time you switch from the code editor to the form editor.

**Comment by philsturgeon** [comment]
@dpashkevich most of us are stuck with working in one particular format and converting to another. I maintain these two tools for this reason, with the end goal being putting them in the bin and having one format that can be used everywhere.

https://github.com/openapi-contrib/openapi-schema-to-json-schema/
https://github.com/openapi-contrib/json-schema-to-openapi-schema

**Comment by marbemac** [comment]
Hi @dpashkevich - we're having trouble reproducing, what's the flow you're going through that's erasing the nullable? Also, which version of Studio? Thanks!

![2020-06-24 18 55 23](https://user-images.githubusercontent.com/847542/85635662-079d4480-b644-11ea-95f1-92ba11def8f7.gif)

**Comment by marbemac** [comment]
Ok nevermind, @mallachari was able to reproduce! Have to update the additional properties - we're on it.

**Comment by dpashkevich** [comment]
@marbemac thanks! Yeah it looks like editing anything in the "Additional properties" dialog in the UI will erase the keyword, but thankfully other edits don't erase it.

**Comment by ahx** [comment]
@dpashkevich You might want to try using [openapi_first](https://github.com/ahx/openapi_first), which is an alternative to committee. It does [not support nullable](https://github.com/ahx/openapi_first/issues/32), but it supports type arrays via a [standard JSON Schema library](https://rubygems.org/gems/json_schemer). Here's a quick [comparison between this and committee](https://gist.github.com/ahx/1538c31f0652f459861713b5259e366a). `</shamelessplug>`

**Comment by mallachari** [comment]
@dpashkevich I've created an issue for that so you could follow it there https://github.com/stoplightio/studio/issues/467

**Comment by philsturgeon** [comment]
Update: nullable is now REMOVED from OAS 3.1, not just deprecated.

**Comment by philsturgeon** [comment]
The plan is now to work on OpenAPI v3.1 independently, which is much closer to release now. For any future feature requests we'll be using https://roadmap.stoplight.io/ and if you've got any trouble please talk to support@stoplight.io.
