### ISSUE TITLE
Integer type in schema does not show value constraints in preview

### ISSUE THREAD

**Issue by joonashak** [stoplightio/studio#390]
**Describe the bug**
The preview pane does not show the minimum and maximum value constraints for a field of type `integer` in schema definition.

**To Reproduce**

1. Create a new endpoint (I used the POST method but that's probably not relevant).
2. Add an `application/json` request body.
3. Add a field of type `integer` to the payload object.
4. Add any minimum or maximum constraint in Additional Properties > Number Validations.

**Expected behavior**
Expected to see the value constraints when hovering over the field's properties in the Preview pane.

**Screenshots**

![Screenshot 2020-04-11 at 9 43 25](https://user-images.githubusercontent.com/18666321/79037372-f57d3f80-7bd8-11ea-9d11-93b7f64fa909.png)
How both fields are configured.

![Screenshot 2020-04-11 at 9 43 35](https://user-images.githubusercontent.com/18666321/79037380-0a59d300-7bd9-11ea-9061-84105481f4fb.png)
The `number` type field shows expected behavior while the `integer` type exhibits no tooltip on hover.

![Screenshot 2020-04-11 at 9 46 06](https://user-images.githubusercontent.com/18666321/79037407-47be6080-7bd9-11ea-83ce-da0b2c5c04d0.png)
Both fields appear to be correctly configured in the mark-up.

**Environment:**
 - Studio version: 1.11.0
 - OS: macOS 10.15.3

**Comment by philsturgeon** [comment]
Pretty sure we took care of this one already. @lottamus can you confirm?

**Comment by P0lip** [comment]
@philsturgeon I can confirm it, as I've already fixed the issue recently. :sweat_smile: 
It's still not published however, so you'll need to wait a bit - hopefully it make its way in one of the next releases.
Will let you know once it's out.

**Comment by P0lip** [comment]
This will be out in v1.12, expected to be released soon.
