### ISSUE TITLE
Shared response header displays `in: "header"` badge

### ISSUE THREAD

**Issue by MikiLoz92** [stoplightio/studio#391]
**Describe the bug**
When linking a response header to a predefined parameter header, the UI displays `in: "header"` as a badge, even though it is quite obviously a header.

**To Reproduce**
1. Make a shared header and put it in the `parameters` section of an API `components` (see image).
2. Link that header on a **Response Header**.

**Expected behavior**
Such badge should not be displayed (?)

**Screenshots**
![image](https://user-images.githubusercontent.com/786375/79074873-c05f1300-7ce6-11ea-9c22-bba1af0602fc.png)
![image](https://user-images.githubusercontent.com/786375/79074775-28f9c000-7ce6-11ea-9c41-89c267c8c1b5.png)

**Environment**
 - Studio version: 1.11.0

**Comment by philsturgeon** [comment]
This will be gone in the new elements release. If anyone wants a sneak preview then shout! phil@stoplight.io
