### ISSUE TITLE
allOf ref's are not properly displayed on the published docs

### ISSUE THREAD

**Issue by MikiLoz92** [stoplightio/studio#392]
**Describe the bug**
When composing a model of two other models' fields via `allOf`, in the preview of the Studio everything is displayed correctly. However, in the published docs, it is not (see screenshots).

**To Reproduce**

1. Create a model that references other 2 models via `allOf`.
2. Publish the docs, the rendering of that model is not correct.

**Expected behavior**
The published docs should match the preview in Studio (see images).

**Screenshots**
The Studio editor (everything fine here, publishing preview is fine too):
![image](https://user-images.githubusercontent.com/786375/79160189-49eb0f80-7dd1-11ea-98dd-24b827e797ed.png)
The published docs (not the preview, actually published):
![image](https://user-images.githubusercontent.com/786375/79160396-9fbfb780-7dd1-11ea-84a4-a46cbd3654d1.png)

**Environment**
 - Studio version: 1.11.0

**Comment by philsturgeon** [comment]
Hey @MikiLoz92. I'll close this one down as its rather old and we've done a lot of fixing on allOf and oneOf in docs and studio. There's one more to go #180, and we're also entirely revamping the docs with https://stoplight.io/open-source/elements/ so this is probably not needed anymore.
