### ISSUE TITLE
"Clone failed with: HTTP Error: 404" when "include tutorial files" is checked

### ISSUE THREAD

**Issue by jplotky** [stoplightio/studio#394]
**Describe the bug**
Freshly installed Stoplight Studio Version 1.11.0-build.22031 (040aeb3) on 64-bit Windows 10.  First time trying the software.  Entered a name in New Local Project, checked the "Include tutorial files?" box, and clicked Create.  The "Processing" bar showed for just a second, then red box in lower-right corner with error message in title.
Created account with email address, logged in, tried again, same result.
Installed Stoplight on different Windows PC, same result.
Tried fresh download of stoplight-studio-linux-x86_64.AppImage on Ubuntu 19.10 in a virtual machine, and got the same result.
Also tried the Appimage on a native Centos 7 system on a different network, and got the same result.

**To Reproduce**
1. Install Studio version above on Windows 10.
2. Open Studio
3. In New Local Project form, type "test" for Name.
4. Click checkbox to Include tutorial files?
5. Click Create button in New Local Project form.
3. See error

**Expected behavior**
New project created that includes tutorial file.  This is what happens when trying the same steps on web version.

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0-build.22031 (040aeb3)
 - OS: Windows 10 Pro v1909 build 18363.752

**Other information**
The same error is shown when trying to create a project with "Open Git Project" from the demo URL https://github.com/stoplightio/studio-demo

**Comment by rossmcdonald** [comment]
@jplotky These are cloned from Github directly, so it could be something in between you and Github that is causing issues. Are you able to navigate to the repos directly? For example, does going to https://github.com/stoplightio/studio-demo work? Are you behind a corporate firewall or proxy that may explain the 404s?

**Comment by jplotky** [comment]
Thanks.  I'm able to clone that repo without a problem using git.

I then made a new project from the clone using Add Existing Folder.  Studio recognizes it as a git repo and local commands like switching branches work fine.  But when I click on the "Pull latest from git repo" button I get a red error box saying "Pull failed with: HTTP Error: 404".  The URL for the origin remote is `https://github.com/stoplightio/studio-demo`

I see a logs directory in the Studio appdata folder, but it is empty.  I couldn't find any information on how to enable logging.  If I start Studio from a cmd window it prints some deprecation warnings but nothing about the 404 error.

**Comment by Pazns** [comment]
While using a fresh AppImage running on Fedora 30,
When trying to boot a new project including tutorial files,
I got the same issue and the exact same error message.

I opened the Developer tools of the electron app and looked at the Network tab, only to find that when creating a new project including tutorial files, the app tried to GET this url : 
`https://stoplight.io/api/github.com/stoplightio/studio-templates/info/refs?service=git-upload-pack`

which indeed answers as a 404.
