### ISSUE TITLE
[v1] Prism generating an error, not validating pattern

### ISSUE THREAD

**Issue by emorale112** [stoplightio/studio#395]
**Describe the bug**
In prod, Path parameter is not being properly validated 

**To Reproduce**

1. Using the following spec:
```
openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userID}':
    parameters:
      - schema:
          type: string
          pattern: '^[0-9]{3}$'
        name: userID
        in: path
        required: true
    get:
      summary: Retrieve a user
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
      operationId: get-users-userID
components:
  schemas: {} 
```
2. Enable mocking under "TryIt Tab"
3. Navigate to Path Tab
4. Enter `123` as the value for userID

**Expected behavior**
Validation should occur since the parameter follows the declared pattern.

**Screenshots**
![2020-04-14_16-00-40](https://user-images.githubusercontent.com/23023200/79355876-ddbcf880-7f03-11ea-95aa-4f762dd96c2b.png)

**Environment (remove any that are not applicable):**
Prod v1.11.0 - Not present running locally

**Comment by XVincentX** [comment]
@ssspear Can you take a look at this?

**Comment by ssspear** [comment]
After conversing with @emorale112, we are not able to re-create this issue anymore. Closing as it is likely resolved.
