### ISSUE TITLE
Mock Server ignores examples

### ISSUE THREAD

**Issue by iansan5653** [stoplightio/studio#396]
**Describe the bug**
The mock server completely ignores examples and just returns whatever it wants to. It would be much better if it just returned the example data, or at least if there was an option to do that.

**To Reproduce**

1. Create a response with a property and give it an example value, ie:
```json
"firstName": {
  "type": "string",
  "description": "The first or given name of the person",
  "example": "Jane"
}
```
2. Start the mock server
3. The mocked field will respond with something like "culpa minim incididunt reprehenderit dolor". 

**Expected behavior**
I expected the response to be "Jane".

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Windows 10
 - Browser: Node 12.13.0

**Comment by philsturgeon** [comment]
Sounds like you’re running it in dynamic mode not static mode. Which mock server are you using and where. Studio Desktop has local mock server or hosted mock server. Studio Web only has hosted mock.

**Comment by iansan5653** [comment]
I'm using the local mock server on Studio Desktop. How can I change it into static mode?

**Comment by philsturgeon** [comment]
Ahh I see. When using the "Try it Now" panel you can pick the mode here:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/67381/80648097-78bae400-8a67-11ea-8f78-43e7bd777699.png">

When talking to the server directly it's a little more hands on, and can be done with a `Prefer: dynamic=false` header. 

```
$ http http://127.0.0.1:3100 "Prefer: dynamic=false"
```

Really we should let folks pick the mode in the Mock Server panel, as enabling things by default is not always going to make folks happy, even when its a popular feature like this one.

@lottamus could you work this idea into the mocking changes we just chatted about on Zoom?

**Comment by philsturgeon** [comment]
@iansan5653 I've turned this feature improvement its own issue #440. Thank you!
