### ISSUE TITLE
Stoplight Studio crashes at Login

### ISSUE THREAD

**Issue by drewjoh** [stoplightio/studio#397]
**Describe the bug**

Stoplight Studio crashes after cloning a repo, and when trying to login.

**To Reproduce**

1. After cloning a private Github repository with an existing Stoplight Studio project in it, Stoplight Studio crashes.

2. After reopening the app, clicking "Login" brings up a smaller window (presumably the login window), then crashes the app.

**Expected behavior**

Expect to be able to login.

**Screenshots**

Console log output when this happens:

<img width="1675" alt="Screen Shot 2020-04-19 at 8 36 32 AM" src="https://user-images.githubusercontent.com/66233/79689334-b7f06600-8219-11ea-9b40-48b4157c7dfd.png">

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.11.0 (1.11.0.22031)
 - OS: MacOS 10.15.4
 - Browser: Stoplight Studio Downloaded App

**Additional context**

I've just recently started evaluating Stoplight Studio (started 13 days ago).  Stoplight was working ok in the beginning.  I had created an API, pushed it to Github, and published it to Documentation.  This crashing started earlier this week... I just dropped it and figured I'd pick it up later.

Sat down to try again today with no luck.  I deleted the app, deleted the app folder in /Application Support and tried again, still with no luck.

**Comment by philsturgeon** [comment]
@drewjoh sorry Drew, this one fell through the cracks. So many bugs have been fixed and v2.0 is about to come out which no longer requires login for private stuff. Check out Studio Web now baked into Stoplight Platform if Studio Desktop has made it this long with that bug going otherwise unnoticed & unfixed.
