### ISSUE TITLE
Unable to create project with "Include tutorial files" enabled

### ISSUE THREAD

**Issue by robbiehanson** [stoplightio/studio#399]
**Describe the bug**
I was following along with the [documentation](https://stoplight.io/p/docs/gh/stoplightio/studio/docs/Documentation/01-getting-started.md?srn=gh/stoplightio/studio/docs/Documentation/01-getting-started.md), and attempted to create a project with "Include tutorial files?" enabled. However, I'm unable to do this, as it gives me an error every time:

"Clone failed with: HTTP Error: 404"

**To Reproduce**

1. Attempt to create a new project (desktop version)
2. Enable the "Include tutorial files?" option
3. See error

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0.22031)
 - OS: macOS 10.15.4
 - Browser: N/A (using "desktop" app)

**Comment by rossmcdonald** [comment]
Thanks for reporting @robbiehanson! This issue has already been filed under #394. Please follow that issue for updates.
