### ISSUE TITLE
Stop prompting me about "Unsupported Transport Protocol"

### ISSUE THREAD

**Issue by jpyrichjc** [stoplightio/studio#401]
**Describe the bug**
I am getting repeated popups about an "Unsupported Transport Protocol". Stoplight Studio does not support SSH URLs, only HTTPS URLs. This is fine, because I am not using Stoplight Studio to commit to my repo. But the popup keeps appearing, interrupting my work. It's very annoying.

If I do click "Translate URL", it complains that it could not access the Git Repository because this is a private repo. It then asks me to connect my Github account, which I do not want to do. I should be able to disable this behavior, not work around it by granting access.

**To Reproduce**

1. Open a folder for an existing project with Stoplight Studio that uses a SSH URL for Git.
2. Wait a few minutes
3. Get a popup
4. Disable popup
5. Wait a few more minutes
6. Get popup again
7. Lose mind

**Expected behavior**
I should be able to disable Stoplight Studio from wanting to integrate so tightly with my project. Or, at the least, I should be able to tell it to not care about the SSH URL for a given project.

**Screenshots**
![image](https://user-images.githubusercontent.com/58486853/80249509-32145680-862f-11ea-9d82-a81adb010e38.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Ubuntu 19.10
 - Electron: 8.0.0
 - Browser: 80.0.3987.86
 - Node: 12.13.0
 - v8: 8.0.426.16-electron.0

**Comment by checkin247** [comment]
@jpyrichjc then turn it off as described in this issue #387

**Comment by jpyrichjc** [comment]
Oh goodness. Thank you. Not sure how I missed that. I'll close this one since it duplicates that one.
