### ISSUE TITLE
Problems with web component embedding

### ISSUE THREAD

**Issue by bkonia** [stoplightio/studio#402]
I tried embedding my docs into my site using your web component embedding method. Everything works fine, except when you mouse over the property descriptions, the tooltips don't render correctly. The tooltip text either doesn't display at all, or it displays in the wrong location, overlapping other text. Also, it displays a weird looking black triangle in the location where the tooltip would normally appear. ![tooltips](https://user-images.githubusercontent.com/2266423/80280987-f385a700-86d5-11ea-83cb-b3ee77287db7.png)

At first, I thought this was a CSS or JS conflict, but I tried embedding it on a totally clean page, with no other CSS or JS and it had the same problem. I also notice the same issue occurs on your [demo site](https://stoplight-web-components.docs.stoplight.io/studio). If you go to the Pet model and mouse over the Status property, you'll see the tooltip is broken.

Another problem is that when you click on any of the internal links, it changes the URL in the address bar. The URL that it changes to is non-routable, so if the user reloads the page or tries to navigate directly to the URL, it will throw a 404 error.

Embedding with an iFrame works around these issues, but then you're stuck with the Stoplight header bar. It would be nice if you could call the docs URL with a query string parameter like `?header=off` that would suppress the display of the header, for use in iFrames.

**Comment by rossmcdonald** [comment]
@bkonia Sorry for the delay! We actually pushed out a fix late last week that should resolve this issue. Let us know if you keep seeing this issue.
