### ISSUE TITLE
Only able to view one page while in publish preview (Windows 10, v1.11.0)

### ISSUE THREAD

**Issue by TylerNielsen** [stoplightio/studio#403]
**Describe the bug**
When I go to publish documentation from Stoplight studio with Windows 10 and version 1.11.0 and toggle the "Show Preview" slider, the navigation renders and the page that I was viewing before clicking "publish" displays, but I cannot switch between any other documents in the preview. I'm stuck on the one page that was originally displayed.

**To Reproduce**
1. On the version of Stoplight Studio specified in environment below, open any git project containing OAS files.
2.  Click the publish button.
3. Toggle the "Show Preview" slider.

**Expected behavior**
I expect that that all the published documents will render with navigation, and I'm able to click between all documents.

**Screenshots**
![image](https://user-images.githubusercontent.com/11844662/80871515-4c22ea00-8c6a-11ea-8fcc-974497a01e44.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Windows 10
 - Browser: Chrome 80.0.3987.86
 - Node: 12.13.0
- V8: 8.0.426.16-electron.0

**Comment by philsturgeon** [comment]
Publish preview is gone now, the recommended workflow is pushing to a branch and browsing the docs using the version picker showing “unpublished branches”. It’s a more realistic preview, and will eventually be linked to from pull requests to close the gap on finding it.
