### ISSUE TITLE
Int64 value is rounded up by request maker

### ISSUE THREAD

**Issue by kannkyo** [stoplightio/studio#404]
**Describe the bug**

The int64 value is rounded up by the request maker.

I want to write this json in Body tab in the request maker.

```json
{
  "id": 1,
  "petId": -9223372036854775808,
  "quantity": -2147483648,
  "shipDate": "2020-05-03T09:11:40Z",
  "status": "placed",
  "complete": true
}
```

But `petId` in original request is rounded up. (`-9223372036854775808` -> `-9223372036854776000` ) And I get `400 bad requests` because of out of range.

```json
{
  "method": "post",
  "url": "http://127.0.0.1:3100/store/order",
  "headers": {
    "Content-Type": "application/json"
  },
  "body": {
    "id": 1,
    "petId": -9223372036854776000,
    "quantity": -2147483648,
    "shipDate": "2020-05-03T09:11:40Z",
    "status": "placed",
    "complete": true
  }
}
```

**To Reproduce**

1. Import https://petstore.swagger.io/v2/swagger.json
2. Show request maker and post to `http://127.0.0.1:3100/store/order`
    ![post](https://user-images.githubusercontent.com/15080890/80910560-334e2d80-8d6b-11ea-8a33-04dfafc5ab26.png)
3. Get `400 bad requests`.
    ![error](https://user-images.githubusercontent.com/15080890/80910563-3517f100-8d6b-11ea-8ffe-d4d5edce54ea.png)

Response Headers : sl-violations
```json
[
  {
    "location": [
      "request",
      "body",
      "petId"
    ],
    "severity": "Error",
    "code": "format",
    "message": "should match format \"int64\""
  }
]
```

**Expected behavior**

Use pedId=-9223372036854775808, and get `200 ok` response from prism.

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Ubuntu 18.04

**Comment by philsturgeon** [comment]
Thanks for reporting this one @kannkyo, we're expecting it to be resolved by the next major version of Elements, which will be making its way into Studio shortly after. This issue tracker is being closed down soon so I'll let you go now, but you can subscribe for early access to our awesome new docs tool with new and improved "Try It" over here if you're interested: https://stoplight.io/open-source/elements/

**Comment by kannkyo** [comment]
Thank you for tell me, @philsturgeon  . I'll try to use "Elements" !
