### ISSUE TITLE
Usable vertical scroolbars

### ISSUE THREAD

**Issue by martinberlin** [stoplightio/studio#405]
**Chore summary**
Please add usable vertical scroolbars

**Tasks**
- [ ] Add normal width scrollbars (and not the 4/5 pixels exisiting ones)

**Additional context**

I'm talking about how the AppImage software works in Linux. It shows very unusable vertical scrollbars that are hard to manouver. A scrollbar should have a minimum usable width just as the scrollbar that is seen here on github when we add an Issue
![unusable-scroolbars png](https://user-images.githubusercontent.com/2692928/80982581-d0709b00-8e2b-11ea-8ce7-6b895faeab4f.jpg)

**Comment by lottamus** [comment]
We've just released Studio Desktop [v1.12](https://github.com/stoplightio/studio/releases/tag/v1.12.0) which includes a fix for this issue. Please feel free to re-open if you're still seeing the issue after upgrading.

**Comment by martinberlin** [comment]
Thanks I will check tomorrow how it looks like
