### ISSUE TITLE
Rename "Validations" and "Additional Properties" to "Other Properties"

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#411]
Studio inconsistently refers to things as Validations (when they might contain things other than validations) and "Additional Properties" (which is awkward because a keyword exists called `additionalProperties` and it's not this).

<img width="502" alt="image" src="https://user-images.githubusercontent.com/67381/81216434-cb018500-8fd2-11ea-9c6f-b6ce6e353cdd.png">

The tooltip that says "Validations" opens the "Additional Properties" modal.

<img width="502" alt="Screen Shot 2020-05-06 at 19 48 32" src="https://user-images.githubusercontent.com/67381/81216474-d9e83780-8fd2-11ea-9eab-a71cfbce8dcf.png">

Let's rename the tooltip and modal name to "Other Properties", as in... all the other things you can do which we decided we're going to be in the main UI and got slid into this modal. :D

**Comment by mallachari** [comment]
@philsturgeon how about type validations sections? Should we use `String Properties`, `Subtype Number Properties` instead of `String Validations` and `Subtype Number Validations`? They too may contains properties that are not validations.

**Comment by philsturgeon** [comment]
Yeah let's just make it String Properties etc for now.

**Comment by mallachari** [comment]
Added with https://github.com/stoplightio/platform-internal/pull/1490

**Comment by philsturgeon** [comment]
Thank you!
