### ISSUE TITLE
Potential saving race-condition with large OpenAPI documentation files

### ISSUE THREAD

**Issue by maennel** [stoplightio/studio#413]
**Describe the bug**
Stoplight Studio overwrites manual changes in large OpenAPI documentations  (>5k lines with references to further OpenAPI files holding schemas and parameters).

This is possibly related to #409.

**To Reproduce**
- Have a large OpenAPI documentation.
- Have Auto-Save enabled.
- Do 5-6 small changes in a row (for example replace a part in some paths, i.e. `/users/{userId}/portemonnaie` --> `/users/{userId}/wallet`, etc.). Keep pressing CTRL+S between each change.

Suddenly, Stoplight Studio would overwrite single or multiple changes with either the previous value or a mix of the previous value and the change. Sometimes it would also jump to the first line of the document while typing. 

I am able to reproduce this behaviour in the code editor.

My conclusion so far is that auto-saving interferes with manual saving (CTRL+S) and there is some problem with the text buffer or the management of it (but I'm no expert in this kind of things).

**Expected behavior**
Do not overwrite what's in the code editor.

Other (possibly related) observations during the procedure to reproduce the behaviour:
- When doing changes in the code view, processing of the OpenAPI file takes a noticeable amount of time. CPU is also going up and typing feels sluggish, as characters appear with a delay.
- While doing these small changes, I can observe a small spinner on the bottom right.
- I get that small pop-up on the bottom right "Taking a while? Submit Report" really often. 
- In the background, logs are POSTed to https://stoplight.io/api/logs

I got used to manually do small commits in a terminal besides Stoplight Studio, but I think this cannot be the workaround for everyone.

Doing this, I also noticed that changing branches in a terminal would not update contents in Stoplight Studio. Instead, Studio would auto-save changes overwriting what's on disk. But this might be unrelated.

Studio version: 1.11.0
OS: Ubuntu 20.04
Browser: AppImage version/Chrome 81.

Please let me know if you need more information.

**Comment by philsturgeon** [comment]
@maennel thanks for reporting this. We're always making performance improvements as various edge cases are found to trigger other problems. Giant files like this will often cause problems, even when another 5k line file might work just fine. Could you share it with me so we can try it out? phil@stoplight.io. I won't leak any secrets :) 

Mind if I ask why the file is 5k lines? $ref is there to avoid situations like this, so I wonder if a workaround would be leveraging the excellence that is a DRY $ref-based project structure. https://stoplight.io/blog/keeping-openapi-dry-and-portable/

**Comment by philsturgeon** [comment]
We've been playing around with GitHub's giant OpenAPI files as a benchmark and made loads of performance wins, so I'll close this one down.

**Comment by Blacklands** [comment]
It's good that there are performance improvements now, apparently, but has the actual underlying problem been identified and addressed?
If there's really a race condition that sometimes results in contents being overwritten with previous values, then it may still happen, just (even) more rarely now.

**Comment by philsturgeon** [comment]
Hard to know! Maybe you can let us know how Studio Desktop v2 works out for you when it’s released, or Studio Web now. We asked for an example file to play with and we didn’t get it, so there’s not much more to do in this issue unless you can confirm there’s still a problem, and if so share the openapi.
