### ISSUE TITLE
[URGENT] Docs fails to find ALL references on OpenAPI models

### ISSUE THREAD

**Issue by MikiLoz92** [stoplightio/studio#416]
**Describe the bug**
A set of APIs that were being displayed correctly up until now (no commits have been made since) have decided to stop working recently. When accessing any model on the Docs, references cannot seem to be parsed and the model displays a myriad of errors (see screenshot).

**To Reproduce**

1. Create a model that references other models
2. Publish to Docs
3. Go to that model in Docs

**Expected behavior**
Should inline references successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/786375/81602305-3dec7080-93c4-11ea-9dba-80015c914ad5.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Mac
 - Browser: Opera

**Additional context**
The models exist and were being inlined fine just until recently, and since no commits have been made in this repo ever since, I came to the conclusion that it's not a problem with our project.

**Comment by rossmcdonald** [comment]
@MikiLoz92 Can you send us an email at support@stoplight.io? We'll need to take a closer look to see what might be going wrong here.

**Comment by MikiLoz92** [comment]
Hello,

Sending this email in reference of the GitHub issue below.

Regards,
Miguel.
