### ISSUE TITLE
Support XML examples for schemas

### ISSUE THREAD

**Issue by stephenlprice** [stoplightio/studio#419]
**Describe the bug**
As an API designer I am happy to define my schemas using JSON, however these endpoints are also capable of producing and consuming XML. Therefore I would like my docs to provide XML examples to make my docs consumers aware of this option.

**To Reproduce**
1. Given any test API document, add a new endpoint and then add new request and response bodies accepting application/xml or another xml based format.
2. Add a new example and paste in the sample XML found here.
3. Studio will error with: Invalid JSON: Unexpected token < in JSON at position 0
4. Example will not be rendered in docs.

**Expected behavior**
Support XML examples in the form editor and docs (note does not mean support writing XML schemas or parsing them as JSON).

**Screenshots**
<img width="727" alt="Screen Shot 2020-05-13 at 12 38 15 AM" src="https://user-images.githubusercontent.com/58522233/81849484-32ac5880-951c-11ea-9f95-41abddeb19a1.png">

**Environment (remove any that are not applicable):**
 - Studio version: v1.11
 - OS: MacOS Catalina
 - Browser: [e.g. Chrome 81]

**Comment by worksofliam** [comment]
Hi. This shouldn't be closed. I am also looking to start documenting my XML APIs using Stoplight... but support is lacking it seems.

![image](https://user-images.githubusercontent.com/3708366/105530453-ce9a8080-5cb5-11eb-9c25-8fd85fbfd52d.png)

**Comment by sp00m** [comment]
I can't manage to get XML examples working either, is there any working example I could follow?
