### ISSUE TITLE
Org repo gets published but is published under account handle instead 

### ISSUE THREAD

**Issue by amrdraz** [stoplightio/studio#420]
**Describe the bug**
When publishing a repo that is under an org it is published on stoplight studio under the account user name and not the org user name, as a result when I hit the Docs button I get the screen telling me to publish.

**To Reproduce**

I'm not sure if this applies in general but my specific case was

1. create a repo under your user account
2. add it to stoplight studio
3. import files and commit them to repo
4. publish
5. transfer repo to organisation account
6. remove old repo and add new org repo to spotlight studio
7. publish
8. you will notice you are getting a link that belongs to the user handle not the org (it works)
9. in the original studio window hit docs
10. you get a button telling you to publish (even though you did 🤔)

**Expected behavior**
I expect that when I publish a stoplight project that it's url is under the project's handle and not my handle

**Screenshots**
project added
<img width="453" alt="Screenshot 2020-05-13 at 21 59 36" src="https://user-images.githubusercontent.com/1708559/81871746-bac04b80-9578-11ea-967c-824ab8a66f89.png">
and opens correctly
<img width="466" alt="Screenshot 2020-05-13 at 21 59 51" src="https://user-images.githubusercontent.com/1708559/81871759-c14ec300-9578-11ea-8c27-0afa6408d320.png">
but publishing happens under user account

<img width="402" alt="Screenshot 2020-05-14 at 00 27 42" src="https://user-images.githubusercontent.com/1708559/81872266-bcd6da00-9579-11ea-81ee-8a6aa39ad765.png">
<img width="325" alt="Screenshot 2020-05-13 at 22 00 34" src="https://user-images.githubusercontent.com/1708559/81871780-cdd31b80-9578-11ea-9751-1337b2f99efd.png">
and so the org project docs doesn't exist
<img width="1601" alt="Screenshot 2020-05-13 at 22 00 06" src="https://user-images.githubusercontent.com/1708559/81871793-d3c8fc80-9578-11ea-924e-509f83a3d778.png">
even though the user it really was published just under the github user handle
<img width="1492" alt="Screenshot 2020-05-14 at 00 26 16" src="https://user-images.githubusercontent.com/1708559/81872187-92851c80-9579-11ea-9e38-64fb4d1e6bce.png">
FYI if I in the user handle hit the studio button I get redirected to the projects page instead of the actual project page (which I assume is correct as that project doesn't exist)

**Environment (remove any that are not applicable):**
 - Browser: Mac Google Chrome 81.0.4044.122

**Comment by rossmcdonald** [comment]
@amrdraz Thanks! We are aware of this issue when repositories are moved after initially being published. We have a fix for this issue coming in a big v2 update that will be available in the coming months.

**Comment by philsturgeon** [comment]
The new docs offering is now out as part of [Stoplight Platform](https://stoplight.io/welcome), enjoy!
