### ISSUE TITLE
Enums not converted to type of attribute

### ISSUE THREAD

**Issue by NikVandewouwer** [stoplightio/studio#421]
**Describe the bug**
By default every new attribute you add to a schema is of type string so if you add enums for this attribute they are also defined as string enums. 

If you change the type of the attribute to integer after you have defined the enums, the values of the enum stay string:

`    
"test": {
      "type": "integer",
      "enum": [
        "1",
        "2",
        "3"
      ]
    }`

This causes issues with schema validations (value not allowed in enum)

However if first set the type of the attribute to integer and only then define the enums they are defined as integer:

` "test": {
      "type": "integer",
      "enum": [
        1,
        2,
        3
      ]
    }`

**To Reproduce**
1. add new attribute to schema as string
2. define integer enums (1, 2, 3, 4,...)
3. change type of attribute to integer
==> enums stay string

**Expected behavior**
Enums are converted to the type of the attribute

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: macOS 10.15.4

**Comment by NikVandewouwer** [comment]
it seems to be fixed in latest version? I got a an validation error from spectral in stoplight

**Comment by rossmcdonald** [comment]
This should be fixed in the latest version of Studio.
