### ISSUE TITLE
Python Code Generation Sample Improvement

### ISSUE THREAD

**Issue by demitri** [stoplightio/studio#423]
**Chore summary**
Have the Python/Requests generated code reflect the API definition.

**Tasks**
This is really minor. In the generated docs, under "Try It" -> "Code Generation" -> "Python/Requests", the last line of the code generated is:

```python
print(response.text)
```

The `requests` package has a `.json()` method, [described here](https://requests.readthedocs.io/en/latest/user/quickstart/#json-response-content). The docs can check if the return data is `application/json`, and if so, suggest this line:

```python
print(response.json())
```

Yeah, it's a super minor thing...

**Comment by philsturgeon** [comment]
@demitri we defer the generation of snippets to this handy little package: https://github.com/Kong/httpsnippet I could take a swing at this PR but it seems like you've got a lot more context. Would you be willing to send them a PR?

**Comment by demitri** [comment]
Happy to file an issue, [here](https://github.com/Kong/httpsnippet/issues/167). But I wonder if the line isn't a little blurred here? For example, an API can declare that the return type is `application/json` or `text/plain`. For the former using

```python
print(response.json())
```

is the right thing to do, but for the latter

```python
print(response.text)
```

is correct. But that decision depends on the API response definition. I haven't used `httpsnippet` before so I don't know what the interface between it and Stoplight would look like.

**Comment by philsturgeon** [comment]
I'd hope httpsnipet is smart enough to let .json() only be used when json is the response type? 

Let's follow that over here.

https://github.com/Kong/httpsnippet/pull/153
