### ISSUE TITLE
Studio keep removing leading 0

### ISSUE THREAD

**Issue by vincent-paing** [stoplightio/studio#426]
**Describe the bug**
The Studio is removing leading 0 even in string values

**To Reproduce**

1. Create any endpoint
2. Go to example , enter this
```json
{
    "phone" : "091234567"
}
```
3. Click on any other endpoint 
4. Come back to the previous endpoint
5. It will be changed to 
```json
{
    "phone" : 91234567
}
```

**Expected behavior**
A value marked as string should not remove leading 0

**Screenshots**
If needed, I can send a video,

**Environment (remove any that are not applicable):**
 - Studio version: 1.11.0
 - OS: Ubuntu 20.04 LTS

**Comment by vincent-paing** [comment]
Seems like duplicate of #302?

**Comment by P0lip** [comment]
Yup! It's a duplicate.
I'll close it if you don't mind. As stated in the other ticket, the fix should be out shortly.
