### ISSUE TITLE
Remove published docs for a specific project branch in studio

### ISSUE THREAD

**Issue by wjwilkie** [stoplightio/studio#433]
**User story.**
As a Studio User, I want to be able to remove the published docs for a specific branch of a project, so they no longer appear in the Explorer.

**Is your feature request related to a problem?**
When I have a project with multiple versions of the API published, I need to be able to temporarily publish a development version (labeled as "alpha", etc.) and share it with clients and partners for review, and then remove it when the final version has been reviewed and approved.

**Describe the solution you'd like**
Please add a Group list and Delete button to the Project Settings page similar to where the Default Group is set, which would allow the user to select a published group and delete it.

**Additional context**

**Comment by philsturgeon** [comment]
Yeah you bet! This is coming, and we'll let you know how the progress is going.

**Comment by philsturgeon** [comment]
Added to Stoplight Platform v2.0, which you'll see an announcement about in your inbox soon if you've got a Stoplight account!

<img width="555" alt="image" src="https://user-images.githubusercontent.com/67381/85555567-563be600-b626-11ea-96f2-892385f299fb.png">
