### ISSUE TITLE
Studio Publish Dialog persists when you click elsewhere on the page. 

### ISSUE THREAD

**Issue by audieleon** [stoplightio/studio#434]
**Describe the bug**
When you publish on web studio, a text balloon comes up that says: 
"Your docs are live. Share this link with the world!" and provides a link and a button to view docs. 

The bug is that this dialog disables all other interactions with the page in a way that is not clear (page is not grayed out, and you can still select text, but not interact with it), In this state, you are required to click on the publish button again to clear this weird state - but there is no indication that's what you need to do. 

**To Reproduce**

1. open any project to a markdown editor page
2. publish the pages
3. try to copy and paste text from the markdown editor with the balloon still open
  - This is where you can see the bug
4. click Publish again and normal editing is possible

**Expected behavior**
1. open any project to a markdown editor page
2. publish the pages
3. try to copy and paste text from the markdown editor with the balloon still open
4. *The text balloon should clear immediately* and allow normal page interaction to resume

Thanks!

**Comment by philsturgeon** [comment]
Right, [v2 is out](https://stoplight.io/welcome), and we've removed the Publish modal and now it's just commit and push.

When you've got your project set up head over to Project Settings and enable the Webhooks.

<img width="1069" alt="Screen Shot 2020-06-26 at 2 40 57 PM" src="https://user-images.githubusercontent.com/67381/85857978-1b1eeb80-b7bb-11ea-9237-fcc2a49561c4.png">

You'll never need to click that publish button again, just merge PRs as you normally would.
