### ISSUE TITLE
Response example does not support $ref

### ISSUE THREAD

**Issue by thim81** [stoplightio/studio#435]
Describe the bug
Editing a GET request, in the response body example section. The example is empty even when the code shows a nice reference, like in the "schema". In other places (body for example) it works fine.

Expected behavior
Just like in body, to be able to see a "$ref" link to the example component.

Screenshots
UI
![image](https://user-images.githubusercontent.com/952446/82779981-f6e78c00-9e55-11ea-81bb-b4d1afc83a50.png)

Code
![image](https://user-images.githubusercontent.com/952446/82780015-0e267980-9e56-11ea-808f-b28d926d7bba.png)

Environment (remove any that are not applicable):

Studio version: Version 1.11.0 (1.11.0.22031)
OS: macOS

**Comment by P0lip** [comment]
We're on it!

**Comment by philsturgeon** [comment]
Job done! We've got this change deployed to production so now you can enjoy examples as another type of [Shared Component](https://meta.stoplight.io/docs/studio/docs/Design-and-Modeling/04-shared-components.md). I'll get the docs updated to reflect this shortly, but you should get the idea.
