### ISSUE TITLE
Could not delete parameter default value

### ISSUE THREAD

**Issue by rainmanhhh** [stoplightio/studio#437]
**Describe the bug**
once add. parameter default value could not be deleted in the `Form` view.

**To Reproduce**
add a default value for any parameter and try to delete it with backspace or delete key

**Expected behavior**
default value should be deleted

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: 1.12.0
 - OS: Windows 10
 - Browser: Edge 81

**Additional context**

**Comment by philsturgeon** [comment]
This is working on Studio Desktop v1.12 so I wonder if it's an Edge 81 thing.

![Screen Recording 2020-06-09 at 2 10 35 PM](https://user-images.githubusercontent.com/67381/84146019-3ec40100-aa5b-11ea-9fc4-b98f9ae6d331.gif)

@lottamus is Edge 81 a supported browser?

**Comment by lottamus** [comment]
> is Edge 81 a supported browser?

I'm not aware of any limitations using Studio with Edge 81. 

> default value should be deleted

@rainmanhhh do you mean pressing the delete key in the input is not removing the value? Or the "default" key in the OpenAPI document isn't being removed?

**Comment by rainmanhhh** [comment]
I mean the existing default value(saved and reopen) could not be removed

**Comment by philsturgeon** [comment]
@rainmanhhh sorry but its still not clear what you mean. Could you take a little video capture with quicktime and gifski or any other combination of tools so we can see what you mean?

**Comment by rainmanhhh** [comment]
could not reproduce now...
close it
