### ISSUE TITLE
Ability to "Abstract to Model"

### ISSUE THREAD

**Issue by hotmeteor** [stoplightio/studio#438]
**User story.**
As a developer, I can "abstract" an object into a Model, so that I can keep things organized.

**Is your feature request related to a problem?**
I often have existing response objects that should be distinct Models, but I don't want to mess with cutting and pasting code.

**Describe the solution you'd like**
It would be very useful to have a contextual (ie. right-click) "Abstract to Model" tool for an object that would automatically cut out the object and convert it into an Embedded or Common Model.

**Additional context**
Somewhat related to https://github.com/stoplightio/studio/issues/217

**Comment by philsturgeon** [comment]
Great idea! This is part of several "Refactoring" features we want to get stuck into after v2.0, and you're right I'd love to have this feature as well as simply being able to move models around.

**Comment by philsturgeon** [comment]
This issue tracker is no longer being used for feature requests so I've put this on roadmap over here. Please go and vote for it if you're still interested! https://roadmap.stoplight.io/4-stoplight-platform/c/141-abstract-object-to-model
