### ISSUE TITLE
Unable to reference path parameter values

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#44]
**Describe the bug**

Operation parameters are unable to be referenced, resulting in the error:

```
The Path "..." uses a parameter "..." that does not have a corresponding definition. To fix, add a path parameter with the name "...".
```

**To Reproduce**

Using specification:

```json
openapi: 3.0.0
info:
  title: Path Param Test
  version: '1.0'
  contact:
    name: Test
    url: test
    email: test@test.com
  description: Just a test
servers:
  - url: 'http://localhost:3000'
paths:
  '/todos/{todoID}':
    parameters:
      - $ref: './test.json#/todoParameter'
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      description: A description
      operationId: test
components:
  schemas: {}
```

Where `./test.json` contains a valid parameter value:

```
{
  "todoParameter": {
    "name": "todoId",
    "in": "path",
    "required": true,
    "type": "string"
  }
}
```

**Expected behavior**

Since the parameter is valid, this should work.

**Comment by marbemac** [comment]
Feels like a spectral integration issue. @P0lip since you're doing all sorts of Spectral work this sprint, tossing over to you to take a look at during hardening week.

**Comment by rossmcdonald** [comment]
@P0lip Have you had a chance to look into this? If not, let's update the milestone.

**Comment by P0lip** [comment]
@rossmcdonald 
The problem seems to be resolved.
I cannot reproduce it on my end, does it still occur?

**Comment by rossmcdonald** [comment]
@P0lip I'm not able to get this to work. The new path parameter functionality seems to be interfering any time I try to update the parameter to be a reference. I'll put together a better repro case.

**Comment by P0lip** [comment]
@rossmcdonald thanks, if you could, just zip the whole project with a spec and the model and any other relevant files.

**Comment by philsturgeon** [comment]
@rossmcdonald ping :D could you get that description document over to @P0lip ?

**Comment by rossmcdonald** [comment]
@philsturgeon @P0lip Issue description has been updated with a better repro case. Still getting the errors:

<img width="677" alt="Screen Shot 2019-10-16 at 9 55 47 AM" src="https://user-images.githubusercontent.com/4060903/66931047-264e3480-effb-11e9-8d66-39652f60cb5d.png">

**Comment by P0lip** [comment]
@rossmcdonald there is a typo in ` ./test.json`. You've got `todoId` placed instead of `todoID` - a subtle difference, but still.

**Comment by rossmcdonald** [comment]
@P0lip Ah, good catch. With that corrected I still see:

![image](https://user-images.githubusercontent.com/4060903/66943523-f447cd00-f010-11e9-979f-493f1e2a5cde.png)

**Comment by P0lip** [comment]
Yeah, this is kind of known and caused by imperfect oas2/oas3-schema validation rules.
We have a plan to improve these rules, but no work has been started yet.

cc @marbemac @philsturgeon as you were all involved in that.

**Comment by rossmcdonald** [comment]
@P0lip Makes sense. I'll close this issue then.
