### ISSUE TITLE
Publish feature not connecting

### ISSUE THREAD

**Issue by corypitt** [stoplightio/studio#442]
I'm clicking the publish button in the top right corner of the stoplight window - I receive this message: This project needs to be connected to a git repository before it can be published. Learn more

With the option to 'Log in'

I click log in and log in to my Github account and then nothing happens. 

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button '....'
3. See error

**Expected behavior**
I'd expect to be able to connect the repository in the GUI

**Environment (remove any that are not applicable):**
Version 1.12.0-build.34225
Mac App

**Comment by rossmcdonald** [comment]
Please see #340 for more information on this issue. There is a workaround in the issue description that can be used to bypass this until we get a proper fix in place.
