### ISSUE TITLE
Publishing docs not authorized

### ISSUE THREAD

**Issue by nurfaizahsafie** [stoplightio/studio#446]
I am a collaborator for a private git repository, which I am able to commit and push changes to the repository from StopLight Studio (Desktop App - Windows). However, when I tried to publish the documentation, it returned a "not authorized" message. I tried from both desktop app and web studios, both returned the same thing. See attached.

<img width="246" alt="2020-06-10 (4)" src="https://user-images.githubusercontent.com/66455047/84245563-d0a13c00-ab37-11ea-9f8f-03350a5d381e.png">

**Comment by philsturgeon** [comment]
Right, [v2 is out](https://stoplight.io/welcome)! 

The git integration is a lot nicer.

![git connect](https://user-images.githubusercontent.com/67381/85857878-f296f180-b7ba-11ea-8410-82a9e3442494.gif)

When you've got your project set up head over to Project Settings and enable the Webhooks.

<img width="1069" alt="Screen Shot 2020-06-26 at 2 40 57 PM" src="https://user-images.githubusercontent.com/67381/85857978-1b1eeb80-b7bb-11ea-9237-fcc2a49561c4.png">

You'll never need to click that publish button again, just merge PRs as you normally would.
