### ISSUE TITLE
Choose preferred YML multi-line description syntax

### ISSUE THREAD

**Issue by patrickp-bosch** [stoplightio/studio#447]
**User story.**
As a Stoplight-using API designer, I can choose preferred YML multi-line description syntax, so that I can 
* keep my git history much cleaner (= seeing much less noise).
* retain a better overview over the _actual_ changes to my specs

**Is your feature request related to a problem?**
I often struggle when I have to go through hundreds of changed lines of OpenAPI spec, and all the changes are just like converting from one YML multi-line variant to another.

Example:
![B0F07B16-DED8-4808-922E-ACDD038FFC4F](https://user-images.githubusercontent.com/47972716/84667038-1c7e2780-af22-11ea-890a-a4becef3891f.png)

**Describe the solution you'd like**
A preference pane where  I can select my favorite style. Just like code style settings in an IDE, where you can choose between tabs and spaces for indentation. This will also improve readability and consistency of my specs when (pitiful) people without Stoplight Studio view the plain text.

**Comment by philsturgeon** [comment]
Great idea @patrickp-bosch, this will be a simple way to get this diff noise down. 

We're working on a PR for something similar, so @P0lip is going to sneak this work into that one.

**Comment by patrickp-bosch** [comment]
Hello @philsturgeon, I've seen that version 2.1 has been released by now. What is the currently proposed solution or workaround? I'd like to give a recommendation to my co-workers. Thanks a lot for your support!

**Comment by philsturgeon** [comment]
The recommended approach is to use editor.lineWidth to avoid most line rewrites: https://meta.stoplight.io/docs/platform/2.-workspaces/c.config.md#reference

Even if we implement an option that allows certain multi-line syntax to be used, user B will be sat it's using user A's preference, so there's always going to be trouble. This lineWidth should help avoid it mattering.
