### ISSUE TITLE
Error Error while making the request Network Error The API did not return a response. Is it running and accessible? If you are sending this request from a web browser, does the API support CORS?

### ISSUE THREAD

**Issue by Garcia41999** [stoplightio/studio#449]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by rossmcdonald** [comment]
@Garcia41999 Please provide more information on the issue. Also related to this specific error message, a screenshot of the browser developer console when reproducing would also help.
