### ISSUE TITLE
Allow user to re-arrange properties

### ISSUE THREAD

**Issue by bmogensen** [stoplightio/studio#455]
When working with large JSON schema models it would be nice if the user can re-arrange the properties after adding them by dragging them up and down. Right now the user has to do this in the code which is cumbersome.

For example when user has added a lot of properties including a length property, later on adds width and height property the user can drag those newly added properties so they come in order of length, width and height. Later on when user adds a lengthUnit, widthUnit and heightUnit these can be dragged to appear right after each of the measurements.

**Comment by philsturgeon** [comment]
Totally agree. We've got a request for this already so let's track it in #147.
