### ISSUE TITLE
$id tag gets removed from JSON schema

### ISSUE THREAD

**Issue by bmogensen** [stoplightio/studio#456]
**Description**
When you have a simple JSON schema which for example is only for containing enum values, upon editing that schema via the UI, adding or removing enum values, the $id tag will be removed from the JSON schema source.

**To Reproduce**
1. Create a new model by clicking [+] button and select "Model"
2. Give the model a name "Test"
3. Click show advanced and select that it should be of format JSON
4. Click  [</> Code] button in top right corner
5. Input "$id": "Test.json" after the first {
6. Click [Form] button in top right corner
7. Click "object" and select "String" and deselect "Object" in the popup that appears
8. Click  [</> Code] button in top right corner and observe that the $id line has been removed

**Expected behavior**
It is expected that the tool does not remove the "$id": "Test.json" that was entered in to source when the user continues editing the model via UI.

**Environment (remove any that are not applicable):**
 - Studio version: 1.12.0
 - OS: Windows 10

**Comment by bmogensen** [comment]
I just noticed that the schma id attribute is also deleted from source on any JSON schema if you just flick the "_Disallow additional attributes_" switch.

**Before:**
![image](https://user-images.githubusercontent.com/6775666/84980760-7fabcc00-b165-11ea-8b0c-6bb106ccb175.png)

**Flip the switch:**
![image](https://user-images.githubusercontent.com/6775666/84980675-41aea800-b165-11ea-86b2-357482f00cfc.png)

**After:**
![image](https://user-images.githubusercontent.com/6775666/84980792-96eab980-b165-11ea-9152-8703cfb055f7.png)

**Comment by mallachari** [comment]
This is already fixed along with https://github.com/stoplightio/studio/issues/467.
Just checked it again - it works fine.
