### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by bmogensen** [stoplightio/studio#458]
It would be great if the tool could support refactoring of models so that renaming a JSON schema file you right click the file and select Refactor -> Rename (or similar). You will then get a pop-up box where you can input the new name and the tool will apply the name to the file and also all places where the file is referenced.

Further Refactor -> Move would allow the user to move a JSON schema file to another folder and have the tool correct all the places in other JSON schemas where the file is referenced.

**Comment by philsturgeon** [comment]
Thanks! This is something I'd like to see, and we've got an issue to track it already. #192
