### ISSUE TITLE
Prism: Example with status code different than 200

### ISSUE THREAD

**Issue by clemblanco** [stoplightio/studio#460]
**Describe the bug**

I'm experiencing [the same issue](https://community.stoplight.io/t/unable-to-specify-which-example-should-be-used-to-respond-to-an-api/917/2) using Stoplight 1.12.0.34225.

I think **[Examples](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/01-mocking.md#response-examples)** only work with a 200 response at the moment.

When I try to have it on a 404 response, this way:

![image](https://user-images.githubusercontent.com/668419/85030983-6a8f6700-b17e-11ea-8c17-30020cd14d7a.png)

And when I call it with either `?__example=not-found` or with the `Prefer: example=not-found` header, I also get:
```json
{
    "type": "https://stoplight.io/prism/errors#NOT_FOUND",
    "title": "The server cannot find the requested content",
    "status": 404,
    "detail": "Response for contentType: application/json and exampleKey: not-found does not exist."
}
```

**To Reproduce**

1. Given an **[Example](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/01-mocking.md#response-examples)** response setup for any HTTP code other than 200
2. When calling the endpoint with either the query parameter `?__example={example-key}` or with the HTTP header `Prefer: example={example-key}`
3. See same 404 error from Prism saying it couldn't find the **[Example](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/01-mocking.md#response-examples)**.

**Expected behavior**

Similar to when I use an **[Example](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/01-mocking.md#response-examples)** for a 200 response, I want to receive the data I'm specifying in Stoplight for another response code (100, 201, 400, 404, 500, etc).

**Screenshots**

![image](https://user-images.githubusercontent.com/668419/85030983-6a8f6700-b17e-11ea-8c17-30020cd14d7a.png)

**Environment:**

 - Studio version: 1.12.0.34225
 - OS: macOS 10.14.6 Mojave
 - Browser: Postman

**Comment by philsturgeon** [comment]
Can you try adding `&__code=404` onto that URL? I don't think you need to pick the example name, because you've only got the one example for 404 anyway.

**Comment by clemblanco** [comment]
It does work indeed 👍 

I thought the example name was the primary key used for the lookup. Turns out it will only look for 200 examples by default unless you specify otherwise.

Could be worth explaining that bit in the docs, in my opinion.

Happy to submit a PR if I'm pointed toward the right direction.

Thanks for the swift answer mate!

**Comment by philsturgeon** [comment]
@clemblanco it depends which mock server you use as to whether you get dynamic content or not by default. Prism via the CLI usually defaults to static, which will pick the first example available for whatever code is being returned. That's another issue. #440.

I'll close this down for now because we found something that works but if you could send a PR to make the docs more clear I'd really appreciate that!
