### ISSUE TITLE
Want a request method marker in a sidebar (published doc)

### ISSUE THREAD

**Issue by ryan-cha** [stoplightio/studio#462]
**User story.**
As **a reader**(not writer) of a published api document, there's no request method prefixed to each request. 
I could use the request name as "GET info" or "PUT info", but I wish there were the one beautifully decorated. 

**Is your feature request related to a problem?**
Not quite a problematic, but just makes the reader take one more step to find out the request method.

**Describe the solution you'd like**
Image on the left is the current appearance. I wish there were request method marker in front of each request title as the image on the right.
![image](https://user-images.githubusercontent.com/43307475/85217257-9e120180-b3c9-11ea-9991-5f464bb4cf7c.png)

**Additional context**
(I just found out your product and came from Swagger a few days ago and I do really really love it!!!!
I do really enjoy and feel happy working with it. Cheers!!!!  👍 💯 )

**Comment by philsturgeon** [comment]
@ryan-cha  hey, thank you for the feedback and I'm glad you're liking it so far! We've got a few changes coming to the ToC soon, and this has come up as one of them.

Various Stoplight products have tried to get this right, as have various other documentation tools, and there's definitely not _one way_ we can do it. 

We could have options, but I wonder... why does the HTTP method need to be in the left nav? 

For a REST API, the HTTP method is not relevant, we want to talk about resources and the affordances they have. 

Even if an API is RESTish, for users uninitiated with HTTP I wonder if seeing PUT PATCH POST feels like some weird jargon being shouted at you? 

I know Swagger UI does this, but I have always considered Swagger UI to be very RPC-based. I personally love the simplicity of the Stripe API documentation, which doesn't shout rando HTTP keywords at the user, but does mention it in the docs when you've gone in to see more information, and when you're seeing example code/requests.

<img width="1229" alt="Screen Shot 2020-06-22 at 6 09 39 PM" src="https://user-images.githubusercontent.com/67381/85309938-a5153e80-b4b3-11ea-824b-ec9078bbec06.png">

I sometimes think we're just used to seeing this in some tools so expect to see it in some tools, but I wonder if it's possible that this is just "different" and maybe not "missing" or "worse"?

**Comment by philsturgeon** [comment]
All the above thoughts aside, this has come up internally and I believe the outcome was to go with something closer to this for now:

![image](https://user-images.githubusercontent.com/67381/85310242-05a47b80-b4b4-11ea-81bb-3c09a9e0df36.png)

Maybe it'll be optional (unsure about "default on" or "default off").

**Comment by ryan-cha** [comment]
Hi, Phil.

I totally agree with you. Now that I think, this could be a matter of preference. 

As a developer, I'm just used to find out a "verb(method)" first. 

I'm glad the feature has been already discussed and got included in the future changelist. 
It should be very useful for those prefers it. ;)

Thank you for sharing your thoughts!
