### ISSUE TITLE
Studio wipes all non-commited work on pull

### ISSUE THREAD

**Issue by ratelsoft** [stoplightio/studio#463]
**Describe the bug**
We just lost a ton of work because of this. I was trying to push and was getting the Author cannot be empty message. I decided to try pulling to see if it works and also get the latest from my other colleagues and it just replaced my entire workspace with the remote commit and deleted all the files i've been working on. 

**To Reproduce**

1. Create/Modify one or more files
2. Pull from a remote repository that has changes
3. bam!

**Expected behavior**
At least if there is or will be a conflict one should be made aware. It should also not delete files especially new files that have no conflict whatsoever with remote files. If it needs to clear data then it should ask to commit first when it notices changes before pulling.

**Environment (remove any that are not applicable):**
 - Studio version: 1.12.0
 - OS: Windows 10
 - Browser: Chrome 80.0.3987.86

**Comment by lottamus** [comment]
Hey @ratelsoft, sorry for the delay on this one. Are you still experiencing this issue? Does this happening for you on Studio Desktop or Studio Web? 

Normally there is an error message warning you if there are conflicts that could overwrite your existing changes like so:

![image](https://user-images.githubusercontent.com/7423098/89471311-71306880-d743-11ea-916e-f7aef78769d8.png)

Does this error show for you?

**Comment by philsturgeon** [comment]
We've not heard back from this so we won't be able to narrow down this edge case... if anyone else experiences lost work, firstly... sorry. Secondly, please try and recreate it so we can make sure it's not happening to anyone else!
