### ISSUE TITLE
Change the Order of API Endpoints in the Nav Bar

### ISSUE THREAD

**Issue by keithb-qualtrics** [stoplightio/studio#464]
**User story.**

As a Documentation Creator, I can do change the order that endpoints in OAS can show up in the Navigation Bar, so that I can group endpoint logically by either product functionality to group similar endpoints or put most commonly used endpoints near the top.

**Is your feature request related to a problem?**
Customers often struggle to find the documentation they want to find. It is cumbersome for them to have to scroll a lot to view documentation about similar endpoints that could be logically grouped nearer to each other.

**Describe the solution you'd like**
It would be great to allow the Documentation creator to change the order that documentation elements show up in the Navigation Bar rather than to have these sorted by OAS description in alphabetical order.

**Additional context**

**Comment by philsturgeon** [comment]
Agreed! v2.0 will no longer sort everything alphabetically and will instead show them in the order they are defined in OpenAPI. 

Ordering functionality will come along later,  and I'll leave this issue here to track progress on that.

**Comment by keithb-qualtrics** [comment]
Just to confirm the scenario. we are not concerned with the ordering within a single OAS file, we have multiple OAS files. We want to control the order that these are displayed in the Nav Bar.

**Comment by philsturgeon** [comment]
You would like to control the order that the APIs show up, not the endpoints?

**Comment by keithb-qualtrics** [comment]
Yes. We group our endpoints into OAS files based on product area. We want to choose to change the order that we display these APIs to prioritize the heavily used product areas.

**Comment by philsturgeon** [comment]
Right! We're trying to reduce the number of places we track feature requests, and as this one has an "In Progress" card on the Roadmap I'm going to close it down over here. If you can subscribe to the roadmap card, and vote for anything else on there that you like the look of, you'll get email notifications when the features are ready to use. 

https://roadmap.stoplight.io/c/59-completely-custom-ordering-of-your-docs-sidebar
