### ISSUE TITLE
404 Error publishing from organization repo

### ISSUE THREAD

**Issue by rer145** [stoplightio/studio#465]
**Describe the bug**
Originally had a repo in my personal GH, connected with the Stoplight desktop application and was able to publish without issue. I then transferred the repo to an organization (for which I am an admin of). I authorized Stoplight to have access to my organization in my App settings.  

I can make and commit changes to my docs in the new org repo, but publishing returns a 404 not found error. The url for the old docs at stoplight.io gives a 404, as well as what I believe would be the new url at the new repo.

**To Reproduce**

1. Create a personal repo
2. Publish the docs from that repo
3. Transfer repo to organization account
4. Commit to new repo
5. Publish from desktop app to new repo

**Expected behavior**
The docs would appear at the new URL, being pulled from the new org repo.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: 1.12.0
 - OS: Windows 10
 - Browser: Chrome 80.0.3987.86 (app) / Chrome 83.0.4103.106 (windows)

**Additional context**

**Comment by rossmcdonald** [comment]
Hi @rer145! Can you double check that the Stoplight oauth app has the necessary permissions in your org? We have an article that discusses this in greater detail [here](https://support.stoplight.io/hc/en-us/articles/360036914232-Unable-to-clone-Github-repositories).

**Comment by rer145** [comment]
Hi @rossmcdonald !  Thanks for responding. I double checked the OAuth settings in my personal account, and they were set to grant access to my organization. I then went through the article you sent and followed the steps again. I'm still having the same issue.

Below are some screenshots of my settings after disconnecting and reconnecting according to the article.

**Personal Settings:**
![image](https://user-images.githubusercontent.com/874002/85482575-2abaec00-b591-11ea-9ab9-78cd05bd32fe.png)

**Organization Settings:**
![image](https://user-images.githubusercontent.com/874002/85482634-4920e780-b591-11ea-90c4-826fe87e2cff.png)

**Stoplight Settings:**
![image](https://user-images.githubusercontent.com/874002/85482653-563dd680-b591-11ea-8240-933a576eb2d2.png)


**App Error:**
![image](https://user-images.githubusercontent.com/874002/85482820-afa60580-b591-11ea-848a-5bcf940e8c39.png)

**Comment by philsturgeon** [comment]
There were some awkward situations folks could get in with publishing where personal and org permissions would get tripped up, and redirects were another source of confusion. We've massively changed how we handle this in v2 which we launched yesterday, so I'd recommend [heading over to v2](https://stoplight.io/welcome)! 

![git connect](https://user-images.githubusercontent.com/67381/85857564-684e8d80-b7ba-11ea-9269-02570a4ef975.gif)

We're removing the Publish button from Studio now, so just set up those project webhooks and push to publish :D
