### ISSUE TITLE
JSON Schema properties removed on additional properties change

### ISSUE THREAD

**Issue by mallachari** [stoplightio/studio#467]
**Describe the bug**
Custom JSON Schema properties are removed from a model when updating additional properties.

**To Reproduce**

1. Create a model
2. Add a custom property to root object in code view
3. Switch to forms
4. Edit any additional property
5. Switch to code view
6. Notice the custom property is missing

**Expected behavior**
Models keep all properties that were defined regardless of being inline with JSON Schema properties set.

**Screenshots**
![Peek 2020-06-25 11-06](https://user-images.githubusercontent.com/14196079/85690589-01ef3f80-b6d4-11ea-8942-44c3e3750de9.gif)

**Environment:**
 - Studio version: all

**Comment by marbemac** [comment]
Related - #456
