### ISSUE TITLE
Ref'd response headers are not working

### ISSUE THREAD

**Issue by MikiLoz92** [stoplightio/studio#473]
**Describe the bug**
If you reference a header in a response, it will **not** render. Request header works just fine, though.
Interestingly enough, if you reference a shared header located in another file in the response, it **does** render.

**To Reproduce**
1. Use the following API doc reproducer:
```
openapi: 3.0.0
info:
  title: testapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            header-0:
              $ref: '#/components/parameters/X-Test-Header'
      operationId: get-test
      parameters:
        - $ref: '#/components/parameters/X-Test-Header'
components:
  parameters:
    X-Test-Header:
      schema:
        type: string
        enum:
          - test1
          - test2
      description: A simple header, if you can read this, it means it's working.
      required: true
      name: X-Test-Header
      in: header
  schemas: {}
```

**Expected behavior**
Response header should be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/786375/87102407-1db92080-c252-11ea-9823-e0e2d20261d8.png)

**Comment by philsturgeon** [comment]
@MikiLoz92 hey there, are you using Studio Web, or are you using Studio Desktop? If so, which version?

I think this was solved on [Stoplight Platform](https://stoplight.io/welcome) which has a slightly newer version of Studio, and that newness will come to desktop soon.

**Comment by MikiLoz92** [comment]
Hello Phil,

Well I was actually using Stoplight Platform on the web...

Cheers,
Miguel.

**Comment by philsturgeon** [comment]
@MikiLoz92 thanks for that, helps me narrow down what's going on.

I gave this OpenAPI doc a try in a few different tools, and it's showing up as invalid.

> Semantic error at paths./test.get.responses.200.headers.header-0.$ref
> OAS3 header $refs should point to #/components/headers/... and not #/components/parameters/...

I cannot seem to figure out how to make this OpenAPI be good, because if I move it to headers then the `parameters` usage becomes invalid, and vice versa. 

Copy and paste:

```
openapi: 3.0.0
info:
  title: testapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers:
            header-0:
              $ref: '#/components/headers/X-Test-Header'
      operationId: get-test
      parameters:
        - $ref: '#/components/parameters/X-Test-Header'
components:
  parameters:
    X-Test-Header:
      schema:
        type: string
        enum:
          - test1
          - test2
      description: A simple header, if you can read this, it means it's working.
      required: true
      name: X-Test-Header
      in: header
  headers:
    X-Test-Header:
      schema:
        type: string
        enum:
          - test1
          - test2
      description: A simple header, if you can read this, it means it's working.
      required: true
  schemas: {}
```

This gets us closer. Most tools recognize this as valid, but Stoplight docs do not.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/67381/87586339-addae800-c6e0-11ea-9efc-dd3d60c33583.png">

So this is... 1x missing spectral rule, 1x user error, 1x mistake with docs rendering even when you've updated the OpenAPI. 🤣

**Comment by MikiLoz92** [comment]
@philsturgeon done! keep up the good work 👍

**Comment by philsturgeon** [comment]
Alright, shared parameters are a thing now, so they'll help guide Studio users to doing valid stuff despite how confusing OpenAPI v3.0 is here.
