### ISSUE TITLE
Application crashes randomly

### ISSUE THREAD

**Issue by radmiraal** [stoplightio/studio#478]
> For support questions, please use the [Stoplight Community Forum](https://community.stoplight.io). This repository's issues are reserved for feature requests and bug reports. If you are unsure if you are experiencing a bug, the [Community Forum](https://community.stoplight.io) is a great place to start.
>
> **Please delete this section, any any sections below that you don't use, before creating the issue.**

**Describe the bug**
Since yesterday my Stoplight Studio is crashing randomly. Today it worked fine for a few hours, but now it crashed again and won't start anymore.
I've tried rebooting (fixes it for a while) and removing the Application Support folder for Stoplight. That also seems to fix it for a while.

**To Reproduce**

Can't really give a reproduction path

**Expected behavior**
I expect the app to work fine like it did for a long time.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: 1.13.1
 - OS: MacOS Catalina 10.15.5

**Additional context**
This is the console output when I start stoplight from the CLI:

```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[0714/114855.038984:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee17a1000, 0x2000): (os/kern) invalid address (1)
[0714/114855.126126:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
[1]    7231 segmentation fault  /Applications/Stoplight\ Studio.app/Contents/MacOS/Stoplight\ Studio
```
The log entries & segfault are consistent for all crashes. My machine is reserving memory for Docker (4GB) but has a total of 32GB. I have an IDE, npm and browsers open while working and without Stoplight running this still leaves 8GB of free RAM.

**Comment by radmiraal** [comment]
I've made some changes to my .stoplight.json file to exclude more directories. Since then stoplight did not crash anymore.
I have the file in the root of my full project, and the api specs itself in a subdirectory. So stoplight was basically scanning node_modules folders and vendor folders too.

**Comment by radmen** [comment]
I've excluded the `vendor` and `node_modules` directories. Unfortunately the application still crashes.

**Comment by lottamus** [comment]
Hey @radmen we've just release Studio Desktop v2 which has loads of performance improvements. Can you download the new version and check if this issue still happens for you? https://github.com/stoplightio/studio/releases/tag/v2.0.0

**Comment by radmen** [comment]
Hey @lottamus I've upgraded the Studio Desktop and the problem seems to be fixed. Thank you!
