### ISSUE TITLE
Cannot set response example with plain text.

### ISSUE THREAD

**Issue by maxifom** [stoplightio/studio#481]
**Describe the bug**

**To Reproduce**

1. Given any OpenAPI document 
2. Create path 
3. Add body with text/plain
4. Set example to "OK" as string, not as JSON
5. See json parse error

**Expected behavior**
The OK text example appears instead of json parse error

**Screenshots**
![Screenshot from 2020-07-17 14-13-40](https://user-images.githubusercontent.com/20924207/87769929-c27dc400-c837-11ea-975a-c61068b4832b.png)

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0] 1.13.1
 - OS: [e.g. Windows 7] Ubuntu 20.04
 - Browser: [e.g. Chrome 61] Chrome 80.0.3987.86, node 12.13.0, electron 8.0.0, v8 v8.0.426.16-electron.0

**Comment by philsturgeon** [comment]
Thanks for this, but we've got an issue for tracking this problem. Please subscribe to that one if you'd like updates. https://github.com/stoplightio/studio/issues/289
