### ISSUE TITLE
login sync between web & desktop app

### ISSUE THREAD

**Issue by rarean** [stoplightio/studio#485]
**Describe the bug**
I am able to login to the web app for my workspace with email and password without issue. However, when trying to use the same email and password on desktop app, I am not able to login and get error "we could not find an account with those login details"

**To Reproduce**

1. Download & install desktop app for Windows
2. Login to web app workspace with email & password
3. Logout of web app workspace
4. Open desktop app and click login button
5. Use same email and password as did on website
3. See error

**Expected behavior**
Expect the credentials used to login to web, to also work with desktop app

**Environment (remove any that are not applicable):**
 - Studio version: 1.13.1
 - OS: Windows 10 64bit
 - Browser: Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Additional context**
none

**Comment by philsturgeon** [comment]
Hey there, sorry for confusion here, Studio Desktop v2.0 was delayed a little, and the login process changed when we unveiled [Stoplight Platform](https://stoplight.io/blog/stoplight-platform/).

In Studio Desktop v2.0 the login is actually being removed, as we've changed the way publishing works. Now docs are [published via webhooks] so you don't need to login to publish. 

See how that works in our [documentation on publishing](https://meta.stoplight.io/docs/studio/docs/Documentation/06-publishing.md).
