### ISSUE TITLE
Cannot compare changes using safari

### ISSUE THREAD

**Issue by audieleon** [stoplightio/studio#486]
**Describe the bug**
The compare changes button within the commit dialog fails to show a comparison on safari. All you see is an empty line with the same spacing as would normally be there for a comparison. 

**To Reproduce**
Using safari on a Mac
Open Studio with a git repository attached,
Make a change to a file and ensure it's saved,
Select Commit
Click the compare icon next to the file you changed. 
Observe the popup div. 

**Expected behavior**
I expect to see a comparison of the file with my changes against the branch version. 

**Screenshots**
![Screen Shot 2020-08-09 at 1 09 27 PM](https://user-images.githubusercontent.com/2258619/89740875-97a31c00-da41-11ea-979d-1d883f594ac7.png)

**Environment (remove any that are not applicable):**
 - Studio version: [unknown - happy to add, but I don't know how to find this.]
 - OS: [MacOS 10.15.6]
 - Browser: [Safari Version 13.1.2 (15609.3.5.1.3)]

**Additional context**
N/A

**Comment by philsturgeon** [comment]
Hello Audie, sorry to be the bearer of bad news, but we [do not support Safari in Studio](https://meta.stoplight.io/docs/platform/c.troubleshooting.md) at this time. 

There is normally a message that pops up to let you know this, so I'll pass this on to the eng team to let them know the message didn't pop up for you. You can use Firefox, Edge, Chrome, or use [Studio Deskop](https://stoplight.io/studio/) to avoid any browser troubles when working with Studio.

**Comment by philsturgeon** [comment]
Oh, the engineering team pointing out that it looks like you're on https://stoplight.io/p/studio/ when we've launched the new and improved Studio as a module in Platform: https://stoplight.io/welcome. Studio still does not support Safari, but it will at least make that clear now. :)
