### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by cainmodyo** [stoplightio/studio#487]
**Describe the bug**

When I try to login, it doesn't works, just see a loading icon. 
I complete the login flow in a popup. 
When I close the popup nothing happens.
After that I can't pull/push to github repository

**To Reproduce**

1. Open the studio from Mac
2. Click login
3. Follow login flow

**Expected behavior**
Successfully login
Allow pul/push to github

**Screenshots**

![image](https://user-images.githubusercontent.com/1738680/90267130-2093cc00-de23-11ea-8f61-c0c77e058fbe.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.13.1 (1.13.146868)
 - OS: [e.g. macOS 0.14.6 (18G4032) Mojave]

**Additional context**

**Comment by rossmcdonald** [comment]
This is unfortunately expected until the next release. Please see https://github.com/stoplightio/studio/issues/485#issuecomment-672822939 for more information.
