### ISSUE TITLE
Show all response headers 

### ISSUE THREAD

**Issue by ryan-cha** [stoplightio/studio#488]
**User story.**
As a developer, I want to see the cookies, so that I can use it for the consequent requests.

**Is your feature request related to a problem?**
Whenever I need cookies generated by my server, I need to open up the Chrome dev console and open network tab to grab the cookie.

**Describe the solution you'd like**
Currently, when I make a request using the "Try-It" tool, it displays only basic headers of a response,  
`Content-length` and `content-type`.

I wish it displays all the headers including `Set-Cookie` and `Cookie`, so I can simply grab it there and use it with the consequent requests. 

Thanks very much for you work, as always 👍 .

**Comment by checkin247** [comment]
I would appreciate the support of all Response Headers as well.

Currently:
![image](https://user-images.githubusercontent.com/12472764/95671349-3957fe00-0b96-11eb-9c49-e62d3608e385.png)

Expected:
![image](https://user-images.githubusercontent.com/12472764/95671353-42e16600-0b96-11eb-867f-acafd1707d3c.png)

**Comment by philsturgeon** [comment]
We'll be sure to show all the headers in the new Try It that is coming as part of our [shiny new docs interface](https://stoplight.io/open-source/elements/).
