### ISSUE TITLE
Studio reports that the Spectral ruleset is invalid if more than three functions are defined

### ISSUE THREAD

**Issue by klittlepage** [stoplightio/studio#489]
**Describe the bug**

If more than three functions are defined in the functions key of .spectral.yaml Studio will report that the Spectral config is invalid and stop linting.

**To Reproduce**

1. Define more than three functions in .spectral.yaml e.g.

```yaml
functions:
  - foo
  - bar
  - baz
```
2. Navigate to an API file
3. Observe that linting has stopped and that an error message stating "Your Spectral ruleset contains errors" appears next to the "Filter results..." search bar.

**Expected behavior**

You should be able to define more than three functions (Spectral itself reads the config file and works fine when run from the command line).

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.13.1 (1.13.1.46368)
 - OS: macOS Catalina 10.15.6 (19G73
 - Browser: NA

**Comment by philsturgeon** [comment]
Did you get a chance to recreate this @P0lip?

**Comment by P0lip** [comment]
No, it works fine for me.

**Comment by philsturgeon** [comment]
Ok. Hopefully we either get more information on this or it turns out to be fixed.
