### ISSUE TITLE
Bug: Editing model fields

### ISSUE THREAD

**Issue by KInGATiLLa** [stoplightio/studio#490]
**Describe the bug**
when I edit a single model field name and description, it can't push my changes to workspace.

**To Reproduce**

1. Select a model
2. Edit a model field name
3. Then push workspace to save
4. Error appears in modal

**Expected behavior**
When I save edit changes in model, It doesn't save in workspace

**Screenshots**
![Capture1assad](https://user-images.githubusercontent.com/17881842/90498332-be1c3200-e17a-11ea-9bbc-e589ecc8e54a.PNG)

**Environment (remove any that are not applicable):**
 - Studio version: 3.0.0
 - OS: Windows 10
 - Browser: Chrome 84

**Additional context**

**Comment by rossmcdonald** [comment]
Hi @KInGATiLLa this issue should have been resolved as of yesterday. Please let us know if you're still seeing issues here.

**Comment by KInGATiLLa** [comment]
> Hi @KInGATiLLa this issue should have been resolved as of yesterday. Please let us know if you're still seeing issues here.

Thank you! I will check it
