### ISSUE TITLE
can't edit the API Tolken

### ISSUE THREAD

**Issue by geertdiederen** [stoplightio/studio#494]
I have under /geertdiederen/ my own API that is called Tolken.
I can open it with stoplight studio but when I click edit in Studio, I can see the yaml with a rose cloud icon but not the models under it. It seems empty.

Thanks in advance.

please email me back on geert.diederen@gmail.com

**Comment by geertdiederen** [comment]
oh well, now it works again somehow... ??? didn't change anything only used another project icon.

Bye,
Geert Diederen
geert.diederen@gmail.com

**Comment by rossmcdonald** [comment]
Thanks for letting us know @geertdiederen. If the issue comes back, please re-open this issue so that we can take a closer look.
