### ISSUE TITLE
Mark API endpoints as deprecated/private

### ISSUE THREAD

**Issue by patrickp-bosch** [stoplightio/studio#496]
**User story.**
As an API developer, I can mark and endpoint as deprecated, so that I can easily see in the "Paths" overview that this endpoint has been marked as deprecated.

**Is your feature request related to a problem?**
I can easily set the attribute in the code view, but no visual aid is given which confirms that my input is valid as per OpenAPI specification.

**Describe the solution you'd like**
[Your comparison page](https://support.stoplight.io/hc/en-us/articles/360035390511-What-are-the-differences-between-the-Stoplight-products-) already lists the feature "Mark API endpoints as deprecated/private" but it is not marked as "on the roadmap for Stoplight Studio". While it is easy to add it in the code view, wouldn't it be good to have this feature, given that it is a situation that most API developers will eventually have to face during their API lifecycle?

"deprecated" option should be selectable through a toggle, just like the one that is already present at the "additional properties" pane of DTO attributes. 

Visual aids might include 
- reddish font 
- operation's endpoint name as strike-through (swagger editor does it this way)
- adjusted opacity (swagger editor does it this way)
- an "obsolete" icon next to the deprecated operation

And they might be applied in
- the "Paths" list
- the preview pane

**Additional context**
- Spec: https://swagger.io/specification/#operation-object
- I have searched the documentation + community forum to ensure I didn't just fail to notice the feature.

**Comment by philsturgeon** [comment]
Thanks for bringing this up! It's something we're taking care of in Q4 as part of some bigger work around documentation.

We're trying to get feature requests handled via the Roadmap "Submit Idea" interface these days, but I've gone ahead and made a roadmap card for this one: https://roadmap.stoplight.io/c/121-toggle-endpoint-as-private-or-deprecated

If you can subscribe to that, you'll get an email update when its done.
