### ISSUE TITLE
"Enum value 'null' does not respect type" for nullable parameter

### ISSUE THREAD

**Issue by KaiRoesner** [stoplightio/studio#497]
**Describe the bug**
Spotlight Studio shows the "Enum value 'null' does not respect the specified type" issue for a parameter that is defined with `nullable: true` as described in the "Nullable enums" section of the [Swagger data model specification](https://swagger.io/docs/specification/data-models/enums/).

**To Reproduce**

1. Given this OpenAPI document 
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: test
  description: test
  contact: Goofy
tags:
  - name: test
    description: test
host: test
servers:
  - url: http://test.com
schemes:
  - http
paths:
  /read:
    get:
      tags:
        - test
      summary: read
      description: read
      operationId: read
      parameters:
        - sort: query
          name: sort
          schema:
            type: string
            nullable: true
            enum: [asc, desc, null]
      responses:
        '200':
          description: Success
```
2. Load the api spec in Stoplight Studio.
3. An issue "Enum value 'null' does not respect the specified type 'string'" is shown.

**Expected behavior**
There should be no issue.

**Screenshots**
![2020-09-11_12-24-01](https://user-images.githubusercontent.com/43342031/92912256-e588b680-f429-11ea-9892-b3d1c9025536.png)

**Environment**
 - Studio version: v1.13.1 (Version 1.13.1-build.46368 (40a3cde))
 - OS: Windows 10

**Additional context**
n/a

**Comment by philsturgeon** [comment]
Thank you @KaiRoesner! This was also reported over here https://github.com/stoplightio/spectral/issues/1353 so we'll take care of it in Spectral and it'll bubble up to Studio.
