### ISSUE TITLE
Provide HTTP Response code text definitions in Studio UI

### ISSUE THREAD

**Issue by pazaan** [stoplightio/studio#5]
**User story.**
As a API Designer, I can add a new HTTP response without searching the web, so that I can save time.

**Is your feature request related to a problem?**
Studio currently lets me add Response Codes as a text field with the code number, and no additional context.

**Describe the solution you'd like**
It would be nice if Studio also showed the text meaning (ie, 401: Unauthorized), or even had a drop box that has a searchable list of codes.

**Comment by wmhilton** [comment]
So y'all what they are asking for is the ability to search by name or pick from a list. Right now it just shows a number and we should make it an auto-suggest or something. So a user can type "Forb" and get "403 - Forbidden" in the auto-suggest.
