### ISSUE TITLE
Could not dereference....

### ISSUE THREAD

**Issue by danherd** [stoplightio/studio#500]
When using a nested schema reference (an endpoint refers to a model that itself refers to another model), I get an error about not being able to deference when viewing the generated documentation.

**To Reproduce**

1. Given this OpenAPI document:

Customer.v1.yaml

```yaml
title: Customer
type: object
properties:
  title:
    type: string
    maxLength: 255
  first_name:
    type: string
    maxLength: 255
  last_name:
    type: string
    maxLength: 255
  email:
    type: string
    maxLength: 255
    format: email
  phone:
    type: string
    nullable: true
    default: null
    maxLength: 255
required:
  - title
  - first_name
  - last_name
  - email
```

CustomerNew.v1.yaml

```yaml
title: New Customer
allOf:
  - $ref: ./Customer.v1.yaml
  - type: object
    properties:
      password:
        type: string
        description: 'Must have at least 8 characters, including a lowercase, uppercase, number and special character.'
        minLength: 8
        format: password
    required:
      - password
```

Error.v1.yaml

```yaml
title: Error
type: object
properties:
  code:
    type: string
  message:
    type: string
```

POST /customers endpoint

```yaml
  /customers:
    post:
      summary: ''
      operationId: post-customers
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                required:
                  - jwt
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
      parameters: []
      description: Create a new customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./CustomerNew.v1.yaml
```

2. View the endpoint in Stoplight:

![image](https://user-images.githubusercontent.com/659658/94545946-1c8e0300-0245-11eb-9a58-306d25a05ed1.png)

3. See error

![image](https://user-images.githubusercontent.com/659658/94545487-80fc9280-0244-11eb-8d7b-4328010a6bf5.png)

**Expected behavior**

I expect to be able to see all the fields from the Customer model, alongside the password field. In the new customer model view, this is what happens:

![image](https://user-images.githubusercontent.com/659658/94546529-ed2bc600-0245-11eb-8def-6f810899ead0.png)

So there appears to be no reason why this can't appear in the endpoint.

**Environment:**

 - Studio version: Browser (so latest, I presume)
 - OS: Ubuntu 20.04
 - Browser: Firefox 80.0.1

**Comment by XVincentX** [comment]
Might have been fixed by https://github.com/stoplightio/platform-internal/pull/4461

**Comment by XVincentX** [comment]
The bug appears to be gone — we now display the reference correctly and you can navigate to it.

@danherd Can you check that out again?

![image](https://user-images.githubusercontent.com/1416224/95776080-3ee24080-0c89-11eb-932f-96f3bbf861c5.png)

**Comment by danherd** [comment]
Hi,

Thanks for looking into this.

I don't believe this has been fixed as I am still getting the issue described above.

The issue is not within Stoplight Studio, but the auto-generated documentation outside of it (in my Stoplight namespace):

![image](https://user-images.githubusercontent.com/659658/95870620-9b665e00-0d64-11eb-9eec-c518aadfc359.png)

**Comment by XVincentX** [comment]
Thanks for the clarification @danherd — we'll take another look.

**Comment by philsturgeon** [comment]
@danherd can you take another look now that we've got all sorts of new bundling and ref improvements done? Is this still happening?

**Comment by danherd** [comment]
@philsturgeon Whatever has been done has fixed it - many, many thanks.

I'll close this one for you...

![image](https://user-images.githubusercontent.com/659658/107242413-d8491580-6a23-11eb-8df4-733d771ca521.png)

**Comment by philsturgeon** [comment]
Phew! Thanks for your patience on this one, glad we got there in the end.
