### ISSUE TITLE
endpoint Param name change not reflected in Paths list

### ISSUE THREAD

**Issue by mattbishop** [stoplightio/studio#501]
**Describe the bug**

Given a path with a parameter in it, when the param name is renamed in the endpoint editor, the paths list panel in the lower left does not reflect this new name.

**To Reproduce**

1. Create a new path with a param, or start with an existing path. For instance, `/start/{here}`
2. Select that path in the paths list to view it in the endpoint editor.
3. Rename the param to something else, such as `/start/{now}`
4. Click the Save button.

**Expected behavior**
The paths list should reflect the new param name, `/start/{now}`

**Screenshots**
<img width="1071" alt="Screen Shot 2020-10-05 at 7 55 59 AM" src="https://user-images.githubusercontent.com/363909/95096172-cb688e00-06e0-11eb-840d-3341460f1fe9.png">

**Environment (remove any that are not applicable):**
 - Studio version: 2.0.0
 - OS: MacOS 10.15.7
 - Browser: Desktop app

**Comment by philsturgeon** [comment]
Hey @mattbishop, sorry this didn't get the speedy attention we normally strive for. We're trying to push bug reporting for Studio to Support, and feature requests over to roadmap.stoplight.io, so this hasn't been getting the same love. I've escalated it to the appropriate team so they can schedule the work.

**Comment by domagojk** [comment]
Hi @mattbishop, 
I've tried renaming the endpoint using the form and code editor, and I also tried renaming it in the sidebar, but I couldn't reproduce the issue - renaming was always synced as expected.

Could you please upgrade your studio app to the latest version and check if the error still occurs?

**Comment by mattbishop** [comment]
I tested again with 2.1.0 and indeed, the bug has been resolved. Thanks!
