### ISSUE TITLE
Stoplight Studio keeps asking for git credentials for local folder (solution)

### ISSUE THREAD

**Issue by liltor** [stoplightio/studio#503]
** Description **
Stoplight Studio periodically asks for GitHub (GIT) credentials for a solution open from local disk.
The folder is under source control by GIT but this is nothing the Stoplight Studio should care about since the repository is on local machine and opened by open folder.

**To Reproduce**

1. Run the local installation of Stoplight Studio MAC
2. Select "Open existing folder"
3. Stoplight Studio asks for git credentials
4. Ignore by closing dialog (no cancel function available)
5. Stoplight Studio will continue to ask for credentials every X minutes!

**Expected behavior**
Since this is a local project Stoplight Studio should not care about if the project or any of its parent folder is under source control be it Git or anything else.
If git credentials are not provided (ignored) Stoplight Studio should not ask again unless specific commands are used for sync, don't think there is such a command so should not ask again.

**Environment (remove any that are not applicable):**
 - Studio version: 2.0.0
 - OS: MAC OS 11
 - Browser: Native app

**Comment by lottamus** [comment]
> Stoplight Studio will continue to ask for credentials every X minutes!

This happens because Studio is trying to automatically pull new changes from the remote repository. You can disable the Git auto-pull via the Project settings dialog which is accessed via the "cog" icon in the bottom left of the screen.

![image](https://user-images.githubusercontent.com/7423098/95765260-384acd80-0c77-11eb-827a-e734e7fb48e3.png)

**Comment by liltor** [comment]
> > Stoplight Studio will continue to ask for credentials every X minutes!
> 
> This happens because Studio is trying to automatically pull new changes from the remote repository. You can disable the Git auto-pull via the Project settings dialog which is accessed via the "cog" icon in the bottom left of the screen.
> 
@lottamus Thanks for the reply.
Yeah I found that setting a few hours after submitting this ticket, still if no credentials were given it should not try to pull (makes for a strange user experience).

Anyway the setting solves the problem but if I can give my five cents as feedback maybe the functionality should be redesigned, honestly don't know why one would like an auto pull but for those that appreciate it I may make sense but still should honor if no credentials are given.
