### ISSUE TITLE
Stoplight Studio deletes file system folder when removed from API's view in sidebar

### ISSUE THREAD

**Issue by liltor** [stoplightio/studio#504]
**Describe the bug**
When removing a leaf node in the API's view of Stoplight Studio the corresponding filesystem folder was removed.
I hade added an api yaml file inside my dotnet project and when removing it from the API's in the Studio it removed the whole dotnet project not only the representation in the view.
I'd like to point out that this was from the tab for API and not Files.

**To Reproduce**

1. Place an apiservice.v1.yaml file in a subfolder of your project.
2. Open the solution from local disk (parent folder)
3. Remeve the description (folder name) in the API's view
4. Your whole project folder gets removed

**Expected behavior**
Removing a folder/leaf in the API's tab of the sidebar should only remove the visual reference of that folder.
If this leaf-node/folder still contains open api declarations, models or api's, the user should be asked if those files should be removed.

**Screenshots**
Hard to provide since it got deleted 

**Environment (remove any that are not applicable):**
 - Studio version: 2.0.0
 - OS: MAC OS 11 (10.15)
 - Browser: Native app

**Additional context**
Current behaviour erases any and all files and folders corresponding to that view which will have catastrophic implications if these files are not backed up.

**Comment by philsturgeon** [comment]
We intentionally delete the files when you use delete. This is a feature not a bug. :) 

If you'd like to ignore API files you can exclude the directory they're in using project config. https://meta.stoplight.io/docs/platform/2.-workspaces/c.config.md
