### ISSUE TITLE
Mocking an API with references does not work in v2.0.0

### ISSUE THREAD

**Issue by MohiuddinM** [stoplightio/studio#507]
I have tried to mock an api using builtin prism in v2.0.0, but mocking does not work on any field which has a reference. Those fields are simply ignored. I have tried mocking in v1.13, and it works.

**Comment by philsturgeon** [comment]
Mocking with references definitely works in general, there's probably some specific problem with the exact OpenAPI you have. Please report this to https://github.com/stoplightio/prism with more information so they can recreate your issue. Following the bug template should do!
