### ISSUE TITLE
Can't switch branches after remote branch is deleted

### ISSUE THREAD

**Issue by chrisullyott** [stoplightio/studio#509]
After I've deleted a branch from our remote repository, Stoplight studio is "stuck" on the branch, and doesn't seem to be able to switch to another one. Am I missing something?
 
**To Reproduce**

1. Switch to a new, example branch in Stoplight Studio and push that branch to the remote origin.
2. With Git on the command-line, or with another tool, delete the remote branch.
3. Return to Stoplight Studio and try to switch branches.
4. See the following error modal:

``` 
**Something went wrong**
Unfortunately, we were unable to retrieve the list of branches. Error: Expected "# service=git-upload-pack\n" but received "". 
```

**Expected behavior**
I'd expect Stoplight to know that the remote branch was missing, and switch to `main` or `master` for me.

**Environment:**
 - Studio version: Version 2.1.0 (2.1.0.66630)
 - OS: macOS Catalina 10.15.7 (19H2)

**Comment by wmhilton** [comment]
Hi @chrisullyott, I'm trying to reproduce your bug and not having any luck. Here's what I'm trying:

![2020-11-10 15 28 26](https://user-images.githubusercontent.com/587740/98730140-deb6eb00-2369-11eb-8a84-9658efb09437.gif)

I tried with Studio Desktop as well and couldn't reproduce. Which integration (GitHub, BitBucket, etc) are you using?

**Comment by philsturgeon** [comment]
@chrisullyott hey Chris, can you help us recreate this? More information would help as It Works on My Machine.

@wmhilton one other customer has mentioned this issue to support, and they were using GitHub.

@emorale112 could you maybe sprinkle in some extra context?

**Comment by rossmcdonald** [comment]
Unfortunately we haven't been able to reproduce this one. Let us know if you find a way to reliably recreate it.

**Comment by chrisullyott** [comment]
Thanks for looking into it. If I run into it again I'll pop back in.
