### ISSUE TITLE
Extract object to a model from request body 

### ISSUE THREAD

**Issue by kanishk1010** [stoplightio/studio#511]
**User story.**
I wish I could easily refactor the docs, by extracting object/schema from the request/response body to a reuseable component/model without any manual copy/paste. It would save a lot of time.

**Describe the solution you'd like**
Adding an 'extract to model/component' option/button for any object in the schema

**Comment by philsturgeon** [comment]
We've got an issue similar to this, please subscribe to that for updates. https://github.com/stoplightio/studio/issues/217
