### ISSUE TITLE
Can't sort API endpoint

### ISSUE THREAD

**Issue by warakornb57** [stoplightio/studio#513]
**Describe the bug**
When I try to sort api endpoint in a Paths for show for user  it seem can't do this

**To Reproduce**

1. Click edit in Studio then click API panel and select some of reference
2. On bottom panel click Paths
3. How to sort those endpoint

**Expected behavior**
When publish user should to see api endpoint respectively according to Studio setting

**Screenshots**
![image](https://user-images.githubusercontent.com/20918702/98798236-3cb60200-2440-11eb-8e53-d9a362e08db4.png)

![image](https://user-images.githubusercontent.com/20918702/98798325-58210d00-2440-11eb-8579-a4cc955797ad.png)

**Environment (remove any that are not applicable):**
 - Studio version: latest
 - OS: osx
 - Browser: Chrome Version 86.0.4240.183 (Official Build) (x86_64)

**Comment by philsturgeon** [comment]
Great point, this has come up a few times so I'm trying to funnel all feedback to our feature request system: roadmap.stoplight.io/c/134-drag-and-drop-operation-reordering

Would you vote for it there, and if you give your email you'll get an update when it's done. Thank you!
