### ISSUE TITLE
Undo doesn't track changes made in the GUI!

### ISSUE THREAD

**Issue by onecrayon** [stoplightio/studio#515]
**Describe the bug**
I just lost hours of work; this is absolutely inexcusable.

**To Reproduce**

1. Open an OpenAPI document
2. Switch to "Code" view and make some changes
3. Switch to "Form" view and make more changes
4. Switch back to "Code" view and trigger an "undo"

**Expected behavior**

The latest changes made through the GUI should be undone. What *actually* happens is that the last changes you made in the "code" view are undone, which means that any GUI changes made in the interim are **permanently destroyed**. Because Stoplight autosaves after every change, there isn't even any way to reclaim them if you accidentally hit control-Z in the code view.

**Environment (remove any that are not applicable):**

 - Studio version: 2.1.0 (2.1.0.66630)
 - OS: macOS 10.15.5

**Comment by philsturgeon** [comment]
Thanks for this! We’ve got #273 for fracking GUI Undo so I’ll close this one, and I’ve bumped the priority of that one.
