### ISSUE TITLE
Rending API path parameters

### ISSUE THREAD

**Issue by mrum-cuscal** [stoplightio/studio#516]
Stoplight does not render API path parameters if they created at the operation layer. Third party industry API swaggers have path parameter defined at the optional layer not at the API layer. Stoplight only recognises path parameter at the API layer. 

**To Reproduce**
  "paths": {
    "/{initgPtyIdOrgId}/mandates/{mandateId}/notifications": {
      "post": {
        "tags": [
          "Notification"
        ],
        "summary": "Receive Mandate Notification",
        "operationId": "resolveMandateAction",
        "parameters": [
          {
            "name": "x-traceId",
            "in": "header",
            "description": "Unique GUID that was passed to the request in the x-traceId header",
            "type": "string",
            "x-example": "4323b85f-a7cb-49ba-acfb-03abc7e07fb0"
          },
          {
            "name": "body",
            "in": "body",
            "description": "Notification along with mandate details and pending action details",
            "schema": {
              "$ref": "#/definitions/NotificationRequest1"
            },
            "required": false
          },
          {
            "type": "string",
            "name": "initgPtyIdOrgId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "mandateId",
            "in": "path",
            "description": "ID of mandate for which the notification is delivered.",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "x-traceId": {
                "description": "Unique GUID that was passed to the request in the x-traceId header",
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Invalid Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "URI not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Timeout error"
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "body"
      }
    }
  },

**Expected behavior**
Expected to render path parameters.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version:  1.13.1

**Additional context**
.

**Comment by rossmcdonald** [comment]
Hi @mrum-cuscal, I'm going to open a ticket for you in our support system for tracking this request. Please address all future issues/features to support@stoplight.io moving forward.
