### ISSUE TITLE
Endpoint path order messed up in Stoplight Studio 2.1 sidebar

### ISSUE THREAD

**Issue by konsta2106** [stoplightio/studio#517]
**Describe the bug**
After i updated from version 1.13 to 2.1, my endpoints are messed up in UI but they are correct in code

**Screenshots**
![Screenshot 2020-11-25 at 13 48 58](https://user-images.githubusercontent.com/54150208/100224145-1c4c7400-2f25-11eb-8741-38e3012e2c78.png)
![Screenshot 2020-11-25 at 13 48 36](https://user-images.githubusercontent.com/54150208/100224161-22425500-2f25-11eb-8ac9-b141365d0961.png)

**Environment (remove any that are not applicable):**
 - Studio version: 2.1.0
 - OS: macOS Big Sur

**Comment by lottamus** [comment]
Hey @konsta2106, thanks for reporting! I'm able to reproduce and have identified it only occurs for paths containing a parameter at the start. Either way we'll get this one fixed for you!

**Comment by konsta2106** [comment]
@lottamus Thank you.

**Comment by konsta2106** [comment]
Looks like this was fixed in todays release. Also nice additions for shared parameters and responses. Thank you guys!

**Comment by wmhilton** [comment]
@konsta2106 indeed! The path ordering should be fixed as of Studio Desktop [version 2.2.0-stable.5282.b08742e](https://github.com/stoplightio/studio/releases/tag/v2.2.0-stable.5282.b08742e). We’ll close this issue as done, but feel free to create a new issue if you find another bug!
