### ISSUE TITLE
Bundled exported yaml file gives errors in swagger-ui

### ISSUE THREAD

**Issue by NikVandewouwer** [stoplightio/studio#521]
**Describe the bug**
Since stoplight 2.x bundled export files don't render properly in swagger-ui due to invalid $ref. Exports of the same spec worked fine in stoplight 1.x

**To Reproduce**
1. Given this OpenAPI document '...'
`$ref: '#/paths/~1pois~1%7Bid%7D/get/responses/200/content/application~1json/schema/oneOf/0/allOf/1/properties/priceInformation'`
2
![error](https://user-images.githubusercontent.com/13423905/100854235-04c33d00-3489-11eb-8e51-38f4ebf9408c.jpg)
. See error
```
Semantic error at components.schemas.PoiDetails.oneOf.1.allOf.1.properties.priceInformation.$ref
$refs must reference a valid location in the document
Jump to line 731
```
**Expected behavior**
Yaml content renders fine on swagger-ui

**Screenshots**
attached

**Environment (remove any that are not applicable):**
 - Studio version: 2.1.0
 - OS: macos big sur
 - Browser: editor.swagger.io

**Additional context**
I believe due to the optimisations made to reduce the number of lines by reusing models in the bundled export functionality in stoplight 2.x this issue was introduced. I have the impression it has to do with the illegal chars (url encoding?) because other refs within the #/components/schemas work fine.

**Comment by philsturgeon** [comment]
@NikVandewouwer thanks for reporting this. We've got some improvements being cooked up internally and we'll let you know when it's ready.

**Comment by P0lip** [comment]
Hey!
I'm happy to inform that the bundling improvement Phil mentioned above has been merged recently.
I'll let you know once they're out.

**Comment by P0lip** [comment]
@NikVandewouwer, the change is out in Studio Web. It's supposed to be rolled out to desktop users later on as well.
Would you mind giving it a try to see if it improves your situation?

**Comment by philsturgeon** [comment]
This looks like it should work nicely. Great work @P0lip.

**Comment by NikVandewouwer** [comment]
> @NikVandewouwer, the change is out in Studio Web. It's supposed to be rolled out to desktop users later on as well.
> Would you mind giving it a try to see if it improves your situation?

Hi @P0lip I imported my API's into studio web and in have the impression that everything seems to render fine!

**Comment by philsturgeon** [comment]
Amazing! If anything weird pops up please let support know.

**Comment by NikVandewouwer** [comment]
> Amazing! If anything weird pops up please let support know.

I do have the impression that the preview pane sometimes has issues rendering $ref (the issue seems to happen with more complex matters: using same $ref multiple times, using combinations of oneOf, allOf,.. etc). But when I export the api (bundled - yaml) and paste it into editor.swagger.io it seems to work fine. So I believe it's not an issue with the spec, but more with stoplight's preview renderer having difficulties rendering the spec.

**Comment by philsturgeon** [comment]
Yep there's a few awkward allOf->oneOf->$ref situations and similar that'll be taken care of when we give Docs/Preview a bit of an overhaul. You can get sneak previews of that over here when we do the pre release. https://stoplight.io/open-source/elements/
