### ISSUE TITLE
Cannot create or switch branches

### ISSUE THREAD

**Issue by zustse** [stoplightio/studio#522]
**Describe the bug**
Trying to switch a branch or to create a new branch while committing changes cause the following error

> Something went wrong
> Unfortunately, we were unable to retrieve the list of branches. Error: Expected "# service=git-upload-pack\n" but received "version 2 ".

It seems that Stoplight does not support the git 2 protocol.

**To Reproduce**

1. Try to switch branches (Screenshot 1)
2. or try to commit changes into a branch while creating the branch at the same time.

**Expected behavior**
Branch switch is successful in the first case and the changes are commit to the newly created branch successfully in the second case.

**Screenshots**
- https://ibb.co/y5gtjMk
- https://ibb.co/ZfQhdgm

**Environment (remove any that are not applicable):**
 - Studio version: 2.1.0
 - OS: macOS Catalina 10.15.7

**Comment by wmhilton** [comment]
Uh oh, I thought I tested it against Git Protocol 2. 😕 Which git provider are you using? I'm not able to reproduce with either GitHub or GitLab.

**Comment by philsturgeon** [comment]
@zustse hey, could you help us out with some debug information?

@wmhilton do you think we could work some identifying information into the error messages here to help make it easier to figure out in the future?

**Comment by zustse** [comment]
@wmhilton, @philsturgeon Sorry for my late reply. I was on holiday. I used a free BitBucket cloud account when the error occurred.

**Comment by wmhilton** [comment]
I've just retested with both BitBucket Cloud and BitBucket Server and it appears this issue is resolved.

**Comment by philsturgeon** [comment]
Brilliant, thanks for checking @wmhilton !

**Comment by zustse** [comment]
I've also retested this issue in the original setup. The bug does not occur anymore. So the issue is resolved from my side, too.
