### ISSUE TITLE
Images stored on assets/images are not shown when publishing

### ISSUE THREAD

**Issue by dgonzalezordonez** [stoplightio/studio#525]
**Describe the bug**
When editing in studio (web) and try to add an image with the regular markdown code:
```
![image A](../assets/images/image_a.png)
```
then the image can be seen correctly using the *Preview*  window. But when leaving the *Edit* the image is not displayed and a broken link icon appear instead.

**To Reproduce**

1. Create a project and jump into *Edit in Studio*
2. Upload an image and respect the recommended folder structure: *assets/images/<image>*
3. Create a new .md file (*docs/<markdown file>*) and insert the image. Bear in mind the relative path of the image.
4. Check the image is displayed on the *Preview* view
5. Push changes to the workspace/git
6. Check if the image can be seen now on the normal view

**Expected behavior**
Images must be seen once changes are pushed into workspace/git on the normal view

**Screenshots**
*Images are displayed on editing*
![image](https://user-images.githubusercontent.com/16107609/101795589-57939900-3b08-11eb-99e8-64224cbac640.png)

*But not when published*
![image](https://user-images.githubusercontent.com/16107609/101795952-beb14d80-3b08-11eb-958b-5a08a0802930.png)

**Environment (remove any that are not applicable):**
 - Studio version: current web version (today: 2020/12/10)
 - OS: [e.g. Windows 10]
 - Browser: Chrome. Version 87.0.4280.88 (Official Build) (64-bit)
 - Using Bitbucket as git provider

**Additional context**
I would prefer to avoid to upload the images on a 3rd party host and retrieve them from there.

**Comment by rossmcdonald** [comment]
Sorry for the delay here @dgonzalezordonez. We have a roadmap item for tackling image support [here](https://roadmap.stoplight.io/c/100-display-images-from-private-git-repositories) that I believe should address this issue, and, although not ideal, for the time being we recommend using a 3rd party hosting for images. Images should work for public repositories, however that is not always the case.

For any further questions or problems, please direct them to support@stoplight.io.

**Comment by dgonzalezordonez** [comment]
Thanks for the update @rossmcdonald !
