### ISSUE TITLE
edit mode is not working properly

### ISSUE THREAD

**Issue by PeterFerndriger** [stoplightio/studio#527]
1. I want to edit the API at url:
https://m-p.stoplight.io/docs/jc-jcapp-interface/reference/cm.v1.yaml/paths/~1api~1measurement~1/post
2. I press "Edit in Studio", but then an empty page is shown and the url:
https://m-p.stoplight.io/studio/jc-jcapp-interface/edit

I logged in with github-account with administrator privileges, but I cannot do any changes, because nothing is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/58338430/103633907-a507f800-4f46-11eb-98b8-e55c8dd43758.png)
![image](https://user-images.githubusercontent.com/58338430/103633929-acc79c80-4f46-11eb-8110-0bd5c667e876.png)

**Comment by rossmcdonald** [comment]
Hi @PeterFerndriger, do you mind putting this in an email to support@stoplight.io? We can follow-up over email to troubleshoot this issue further.
