### ISSUE TITLE
Error when using Allof

### ISSUE THREAD

**Issue by c-alirwin** [stoplightio/studio#528]
**Describe the bug**
I'm using the Form Editor to add allof/oneof elements to my JSON schema.  For some reason it's adding a "children" keyword that I don't see documented anywhere in the JSON schema spec.  This is causing Stoplight to give me an error.

This is my first time using "allof" so I may be doing something wrong, but I was hoping the Form Editor wouldn't allow it.  

**To Reproduce**

I've included the openapi document with the schema I produced and the [errors.]

[Location.v1.yaml.txt](https://github.com/stoplightio/studio/files/5797022/Location.v1.yaml.txt)

**Comment by P0lip** [comment]
Hey!
I think we have a similar issue already filed in the repo.
https://github.com/stoplightio/studio/issues/415 - could you verify whether this behavior is what you experience?
Let me know. Thanks

**Comment by c-alirwin** [comment]
Looking at that I'm sure it's similar and didn't realize that properties should go there.  The only difference is that I'm seeing "children" multiple times.  Maybe I just need to delete one and replace one with "properties"?

**Comment by c-alirwin** [comment]
Yeah I checked that and it's definitely similar, though I see two "children" sometimes.  Also is it considered a Linting issue when it's an "error"?

**Comment by c-alirwin** [comment]
I've redone this in JSON and it looks different (I had done it in YAML before).

I've attached the JSON version

**Comment by c-alirwin** [comment]
I think I found the problem.  I am using allOf with a nested oneOf inside, that's probably not correct (see attachment snapshot).

If I replace the allOf with the oneOf and get rid of the nested oneOf my errors go away (though I still have to verify it works the way I want).  See 2nd snapshot for change.

Sorry about the issue.  I guess I didn't understand the use of allOf.

Thanks,

Allen
