### ISSUE TITLE
Support the Mac accessibility frameworks

### ISSUE THREAD

**Issue by akrabat** [stoplightio/studio#53]
It would be helpful if the Mac app could hook into the Mac's Accessibility Frameworks so that it works with VoiceOver and [Shortcat](https://shortcatapp.com). 

This would allow people who struggle with using the mouse to be able to use the app via the keyboard/voice.

For example, using Shortcat, with PyCharm I can target every control in the application as you can see here:

![pycharm](https://user-images.githubusercontent.com/33135/63103513-330bc900-bf75-11e9-9aeb-d507563f921a.png)

(The yellow overlays are each individual control that I can target from the keyboard)

However, for Stoplight Studio, I get this:

![stoplight](https://user-images.githubusercontent.com/33135/63103586-4d45a700-bf75-11e9-83f7-15bfe5f09ad1.png)

**Comment by philsturgeon** [comment]
Moved over to productboard. Sorry this hasn't be quick.
