### ISSUE TITLE
Request Body "required" flag not supported

### ISSUE THREAD

**Issue by erik-hansen** [stoplightio/studio#531]
**Describe the bug**
OAS 3.x [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#requestBodyObject) "required" flag is not available in the designer form view and does not reflect in the documentation.

**To Reproduce**

1. Given this OpenAPI document 'https://petstore3.swagger.io/api/v3/openapi.json'
2. Browse to the PUT /pet operation in Stoplight Studio
3. Check "code" view to see that "required: true" is present on "requestBody", but not reflected in "form" or "preview"

**Expected behavior**
Studio form view should have a toggle for responseBody required and this should be reflected in the generated documentation if set to true.

**Screenshots**
![image](https://user-images.githubusercontent.com/6989957/104506978-f6ddfd00-559a-11eb-8494-d606b5014b22.png)

**Environment (remove any that are not applicable):**
 - Studio version: latest on stoplight.io as of (01/13/2021)

**Comment by philsturgeon** [comment]
Thanks @erik-hansen, I've passed this feedback onto the product folks for prioritization.
