### ISSUE TITLE
Parameters unable to reference schema directly in components/schemas

### ISSUE THREAD

**Issue by silesky** [stoplightio/studio#533]
**Describe the bug**

Parameters unable to reference schema directly in components/schemas; UI autocomplete only works with shared parameters.

If there is some OpenAPI documentation about only being able to reference Shared Parameters, it'd be great if you could share it (my google-fu failed me). However, if the OpenAPI spec does in fact prohibit references to anything but components/Parameters, spectral should complain.

**To Reproduce**
```yaml
# Spectral records no errors here!

openapi: 3.0.0
info:
  title: index
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      parameters:
        - name: user_id
          in: query
          schema:
            $ref: '#/components/schemas/Base64ID'
        
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        firstName:
          type: string
    Base64ID:
      title: ID
      type: string
````
**Which produces**
![image](https://user-images.githubusercontent.com/5115498/104827984-1048a880-582a-11eb-967f-bef418009739.png)

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 2.2.0-stable.5343.git-ab43444]
 - OS: [e.g. Mac]

**Comment by philsturgeon** [comment]
That's valid OpenAPI so Spectral is correct to not give any errors about it. Sadly due to OpenAPI often offering seemingly infinite ways to do something, the GUI is not always going to be able to keep up with the most advanced use-cases. For that, there's always the code view. As the tool develops we add more support for more things that people want, so I'll add this feedback to the list.

In the meantime, if you'd like to create something that the rest of your team can easily use, I would recommend using Shared Parameters and $ref'ing things in the code view. 

```
openapi: 3.0.0
info:
  title: index
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
      parameters:
        - $ref: '#/components/parameters/UserQueryParam'
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        firstName:
          type: string
    Base64ID:
      title: ID
      type: string
  parameters:
    UserQueryParam:
      name: user_id
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/Base64ID'
```

This works great. 

Cheers!

**Comment by silesky** [comment]
@philsturgeon Not sure I agree that it works great; the UI doesn't support linking to any schema from the Parameters -- you need to manually edit the OpenAPI document.

![image](https://user-images.githubusercontent.com/5115498/104935092-6d4e7680-5970-11eb-9579-647fc99904c4.png)

**Comment by philsturgeon** [comment]
Right that's what I'm trying suggest.

Other users will be able to pick the Parameter you've defined without having to worry about the implementation details of how that Parameter works.

**Comment by silesky** [comment]
Thanks @philsturgeon. I see, so the expected behavior is that you can't actually link Parameters to components without code view! Gotcha. It was just a bit confusing, since most place where the $ref autocomplete is allowed to reference any component.

Anyway, if this is "expected behavior", I appreciate your quick response.
