### ISSUE TITLE
Request Example does not support $refs

### ISSUE THREAD

**Issue by JayanathP** [stoplightio/studio#536]
**Describe the bug**
I want to use a $ref link for the example of a request body. 
a) There is no way to specify a $ref in the UI.
b) When I specify the example in the code view, the preview ignores the $ref.
c) Examples defined under the components object are not listed in the sidebar.

**Expected behavior**
a) The ability to insert a reference from the Examples tab, similar to how I can insert examples in the Schema tab.
b) For referenced examples to display in the preview as well as the published view.
c) To have  Examples defined under Components listed in the sidebar, just like how Models, Parameters, and Responses are listed.  

**Screenshots**

![image](https://user-images.githubusercontent.com/33196800/105805857-d58b0100-5fdd-11eb-864d-44a139ee42c6.png)

![image](https://user-images.githubusercontent.com/33196800/105805922-f3f0fc80-5fdd-11eb-9d82-d4a570054f97.png)

![image](https://user-images.githubusercontent.com/33196800/105806454-ff90f300-5fde-11eb-91ca-545a828555a0.png)

**Environment (remove any that are not applicable):**
 - Studio version: [2.2.0-stable]
 - OS: [MacOS Catalina 10.15.7]
 - Browser: [Chrome 88.0.4324.96]

**Comment by P0lip** [comment]
Hey!
We've recently added support for OAS3 examples.
The Studio version containing the change has not been released yet, but the browser version should already support it.
![image](https://user-images.githubusercontent.com/9273484/105834316-999a7080-5fca-11eb-8318-4bbedd6f72d0.png)

**Comment by philsturgeon** [comment]
I'll close this one down as it can be used via Studio Web, and a release should be out shortly. Enjoy!
