### ISSUE TITLE
OneOf not validating

### ISSUE THREAD

**Issue by c-alirwin** [stoplightio/studio#537]
I have written a JSON schema that uses the oneOf feature.  Every time I try and create an example using the 2nd choice of the oneOf it fails with the error "'LatitudeDetails' property should match exactly one schema in oneOf"

There are two oneOf's defined, if I try and change the 2nd one to use the 2nd choice in the oneOf it creates an error for the first oneOf even if it's using the 1st choice.  Doesn't make any sense.

I've attached the schema so you can see how the oneOf's are defined.  And in the Example that's included you can see the error I'm receiving when I try and refer to the 2nd choice.
[Location.v1.json.zip](https://github.com/stoplightio/studio/files/5876868/Location.v1.json.zip)

I am running this on the client on Windows 10 and it's the latest version

**Comment by c-alirwin** [comment]
I'm not 100% sure but I think the problem might be that the JSON Schema form in Stoplight requires me to assign a name to the oneOf.  For example using my code:

                      "LatitudeDetails": {
                        "oneOf": [
                          {
                            "properties": {
                              "Latitude": {
                                "type": "object",
                                "properties": {
                                  "LatitudeDegrees": {
                                    "type": "integer",
                                    "description": "NULL FOR MOBILE UPDATE"
                                  },
                                  "LatitudeMinutes": {
                                    "type": "integer",
                                    "description": "NULL FOR MOBILE UPDATE"
                                  },
                                  "LatitudeSeconds": {
                                    "type": "number",
                                    "description": "NULL FOR MOBILE UPDATE"
                                  }
                                }
                              }
                            }
                          },
                          {
                            "properties": {
                              "LatitudeDecimal": {
                                "type": "number",
                                "description": "Latitude in decimal degrees",
                                "example": 39.742043
                              }
                            }
                          }
                        ],
                        "type": "object"
                      },

The Form editor requires me to put a name in for the oneOf (in the above case LatitudeDetails).  If I go into the Code editor and take that name off it still appears in the Form (though it doesn't give me any errors).  All the examples I've found so far of oneOf online do not have that name field.

**Comment by c-alirwin** [comment]
I was able to get this to work if I just did a Model file (JSON schema) and then created an example using that.  I receive no errors.

However, if I use it from within an OpenAPI file I get an error.

**Comment by c-alirwin** [comment]
Just checking to see if this is being looked at at all?

**Comment by philsturgeon** [comment]
Sorry we've been trying to close this issue tracker for ages but more requests come in as we do. Please can you get in touch with support? https://support.stoplight.io/
