### ISSUE TITLE
Invalid bundled export. Parameter $ref placed in components/schema 

### ISSUE THREAD

**Issue by vmatos** [stoplightio/studio#538]
[minimal_bug.tar.gz](https://github.com/stoplightio/studio/files/5880746/minimal_bug.tar.gz)
**Describe the bug**
When having a yaml as:

```
my.yaml
    ...
components:
  parameters:
    Id:
      $ref: ./parameters/Id.yaml
```
And I export it as a bundled yaml. I get:

```
exported.yaml
    ...
components:
  parameters:
    Id:
      $ref: '#/components/schemas/Id'
  schemas:
    Id:
      name: id
      description: Unique id
      in: path
      required: true
      example: 54321
      schema:
        type: integer
        format: int64
        minimum: 1
```
When I reopen the geenrated file in spotlight, it warns me about invalid `name` property in the schema `Id`.

**To Reproduce**

1. Given this attached OpenAPI document
2. Export yaml as bundles. (exported.yaml in attachment)
3. Open exported yaml in spotlight, check error `name` should not be here

**Expected behavior**
I would expect the referenced parameter be imported into parameter

**Environment:**
 - Studio version: 2.2.0-stable.5379.git-75c5189
 - OS: Ubuntu 20.04

**Comment by P0lip** [comment]
Hey this should be fixed in the latest platform.
