### ISSUE TITLE
"Try It" section is misinterpreting data when using application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by karololszacki** [stoplightio/studio#540]
**Describe the bug**
I am trying to document a part of our API that requires usage of `application/x-www-form-urlencoded`.

I tried to do it using your GUI, then resorted to OpenAPI guidelines and finished the example in YAML.

The issue is that in "try it", my schema is interpreted as "raw" and filled with JSON, instead of being a form with filled field names.
See the screenshot at the end.

Here is the link to a minimal example showing the issue:
https://timecamp.stoplight.io/docs/minimal-example/reference/minimal-example.v1.yaml/paths/~1group~1%7Bgroup_id%7D~1user/post

**To Reproduce**

```yaml
paths:
  '/group':
    post:
      operationId: post-group-user
      description: Invite user to a group
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
      summary: Manage users in a group
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: array
                  items:
                    type: string
                guest:
                  type: boolean
              required:
                - email
            encoding:
              email:
                style: form
                explode: true
        description: desc
      parameters:
        - schema:
            type: string
            default: application/x-www-form-urlencoded
          in: header
          name: Content-Type
          required: true
```

**Expected behavior**
I would expect it to follow OpenAPI spec and treat form properly.
Link to the spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#requestBodyObject

**Screenshots**

Stoplight Studio interpreting data as raw:
![Screenshot_20210205_100808](https://user-images.githubusercontent.com/3579195/107012987-103d2800-679a-11eb-807c-8597ce257e60.png)
Stoplight Studio not interpreting it as form (form option resulting in empty fields):
![Screenshot_20210205_100829](https://user-images.githubusercontent.com/3579195/107013041-234ff800-679a-11eb-832c-81a10cc9ecf8.png)
Stoplight Studio code generation for curl making a JSON string:
![Screenshot_20210205_101052](https://user-images.githubusercontent.com/3579195/107013339-804bae00-679a-11eb-8e79-9c3d339bad85.png)

**Environment:**
 - Studio version: web version (so latest?)

**Additional context**

Other software manages just fine, eg:
Readme IO: https://preview.readme.io/reference/?url=https://tc3-img-dev.s3.eu-central-1.amazonaws.com/7ef836a4e34164396a321e475691a02f1990744e438fd700af1f5aa9c3ac8e4e
![Screenshot_20210205_101138](https://user-images.githubusercontent.com/3579195/107013375-8a6dac80-679a-11eb-9877-65dd31aa625f.png)

I might be wrong and maybe I am misinterpreting OpenAPI spec, if so, can you tell me how to use `application/x-www-form-urlencoded` in Stoplight Studio, or give a proper minimal OpenAPI example?

**Comment by mpodlasin** [comment]
Hello @karololszacki 

Sorry for the long wait on this one.

We are currently in full swing completely redoing the Docs section, including the TryIt component.

I've tested your case in our new, unreleased version, and it will work correctly in that new version.

I cannot tell yet when the new component will be in the studio, but standalone docs - which we call "Elements" - premieres at the end of this month. You can check out the details at https://stoplight.io/open-source/elements/.

Closing this, but if you have further questions, feel free to reach out.
