### ISSUE TITLE
An internal server error occurred

### ISSUE THREAD

**Issue by shilpiarya** [stoplightio/studio#541]
**Describe the bug**

I tried  to load the  OAS file to stoplight from https://github.west.isilon.com/eng-papi/isilon_sdk/ branch = master_powerapi  file= papi_schemas/9.0.0.0_OAS2.json ) , it loads in stoplight with no issue .
But when I try to “publish” the content it gives error. Please find attached the screenshot for the same
![screenshot_stoplight_3](https://user-images.githubusercontent.com/58098798/107513106-c0ad9080-6bcd-11eb-8b6e-94a20f879337.png)
 

**To Reproduce**

1. Given this OpenAPI document '...'
2. Click this button '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]

**Additional context**

**Comment by philsturgeon** [comment]
Please could you try and create a bug report using the template provided as there's not enough here to action. Thank you!
