### ISSUE TITLE
RequestBody is not showing up in Request Maker

### ISSUE THREAD

**Issue by m-develops** [stoplightio/studio#543]
**Describe the bug**
The requestBody is not showing up in the Request Maker if this is coming from a Reusable Request Body.
I am also not seeing the shared requestBodies in the menu.

**To Reproduce**

For example the shared requestBody from the Stoplight blog is not showing up:
https://stoplight.io/blog/keeping-openapi-dry-and-portable/

**Expected behavior**
The the requestBody is working in the Request Maker and showing up in the overview.

**Screenshots**
![petstore](https://user-images.githubusercontent.com/16712065/107748826-f1024580-6d19-11eb-8f2f-3e660c7903e1.png)
![requestBody](https://user-images.githubusercontent.com/16712065/107748848-f6f82680-6d19-11eb-8e9f-eb89552e1996.png)
![stoplight-version](https://user-images.githubusercontent.com/16712065/107748861-fe1f3480-6d19-11eb-88f6-9160d0367cce.png)

**Environment (remove any that are not applicable):**
 - Studio version: 2.3.0
 - OS: Kubuntu 20.04

**Comment by philsturgeon** [comment]
Can you please reach out to support with an the smallest repeatable instance in an OpenAPI doc? 

We're closing this issue tracker down ASAP so best handle it there.

**Comment by philsturgeon** [comment]
https://support.stoplight.io/
