### ISSUE TITLE
Provide sha256sums

### ISSUE THREAD

**Issue by thefoxie** [stoplightio/studio#546]
**Chore summary**
Add sha256sums to realeases.

**Additional context**
As a maintainer of [AUR package](https://aur.archlinux.org/packages/stoplight-studio-appimage/) I'd love to have sha256sums available, so I won't have to download the package first (waste of resources and not eco friendly either) to get the sum. Plus my sum could be wrong and won't work for others if something goes wrong.

**Comment by wmhilton** [comment]
Hi @thefoxie ! Hashes are already provided for every release in the `latest-linux.yml` and `latest-linux-ia32.yml` files, which are generated automatically by `electron-builder`:

![image](https://user-images.githubusercontent.com/587740/109997493-3fce4a00-7cde-11eb-8fcf-4cf983d9ec1b.png)

Does that help?

**Comment by thefoxie** [comment]
@wmhilton yes, thank you 😊
Haven't opened the file before and had no idea sums are there. Even though sha256sums are more commonly used in PKGBUILDs, sha512sums should do the work.

I've noticed there's source archive in every release. Would it be possible (without violating any licence) to recompile it and use system's electron instead of what's bundled? vscode-oss does this (https://github.com/microsoft/vscode/issues/56686)

**Comment by wmhilton** [comment]
> I've noticed there's source archive in every release. Would it be possible (without violating any licence) to recompile it and use system's electron instead of what's bundled? vscode-oss does this ([microsoft/vscode#56686](https://github.com/microsoft/vscode/issues/56686))

Oh that's a good question. @lottamus @marbemac got any idea?

**Comment by philsturgeon** [comment]
If you can build the source you're welcome to, the license doesn't stop that, but you cannot distribute the modified work. So if you taught folks at your company how they could build it, that's ok, but if you shared a ZIP or some other package, that's not ok.

More on the license here: https://creativecommons.org/licenses/by-nd/4.0/
