### ISSUE TITLE
Cannot edit APIs/Docs while having Admin rights to Stoplight project and Edit permissions to github

### ISSUE THREAD

**Issue by max-fex** [stoplightio/studio#549]
**Describe the bug**
As a user I cannot edit APIs/Docs while having Admin rights to Stoplight project and Edit permissions to GitHub.

**To Reproduce**
*Workspace owner:*
1. Create a workspace on Free plan
2. Create a private project
2. Add an API and several endpoints
3. Share the project with another member
4. Give that member an Admin permissions
5. Share edit permissions to the related GitHub repo with the member's related GitHub account
*That new member:*
6.  go to project, check that API and Endpoints are visible, "Edit" button is visible too
7. click on "Edit" button

**Expected behavior**
Already created API documentation is available for editing.

**Screenshots**
No API is available for editing, message is: "You do not have any APIs, models, or articles"

**Environment (remove any that are not applicable):**
 - Studio version: web version from March 10, 2021
 - OS: Windows 10 64-bit
 - Browser: Google Chrome. Version 89.0.4389.82 (Official Build) (64-bit)

<img width="152" alt="1" src="https://user-images.githubusercontent.com/78878765/110654512-de6b1700-81c6-11eb-9a57-4d07f071b8e3.png">
<img width="569" alt="2" src="https://user-images.githubusercontent.com/78878765/110654514-de6b1700-81c6-11eb-8d96-103056de0a15.png">
<img width="171" alt="3" src="https://user-images.githubusercontent.com/78878765/110654507-ddd28080-81c6-11eb-9dad-abd544c281b6.png">

**Comment by philsturgeon** [comment]
Did you publish your work?

**Comment by max-fex** [comment]
Yep, the work was published.

After double-checking rights on Worskpace level, Project level and within Git repo,
+ after re-cloning the project from git
+ contacting support directly (not sure eventually if smth. was fixed on Stoplight site or it was mine misconfiguration),
the target contact got an opportunity to Edit the project.

Closing the issue.
