### ISSUE TITLE
Seeing validation error for valid model reference

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#56]
**Describe the bug**

I'm seeing validation errors for models that have been referenced properly (that were created with the form-based designer and display properly in the Read view).

**To Reproduce**

1. Clone [this](https://github.com/rossmcdonald/studio-test/commit/cabbe4f11aa9a95855ae5fe6dc895de3ea68d872) repository in Studio
2. View validations

**Expected behavior**

There should be no errors, instead I'm seeing: `Target $ref not found: ./models/gizmo.v1.yaml`

**Screenshots**

![Screen Shot 2019-08-19 at 11 39 49 AM](https://user-images.githubusercontent.com/4060903/63283328-8d0ed600-c276-11e9-88e3-24d317f8684e.png)

**Environment (remove any that are not applicable):**

 - Studio version: web, current production
 - OS: macOS
 - Browser: Chrome

**Comment by marbemac** [comment]
Likely spectral related, tossing over to you @P0lip for during the hardening week.

**Comment by P0lip** [comment]
Should be fixed in https://github.com/stoplightio/studio-internal/pull/616
Will verify it before merging.

**Comment by P0lip** [comment]
Fixed in https://github.com/stoplightio/spectral/pull/458
