### ISSUE TITLE
Make directory structure configurable / optional

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#57]
**Related**

- https://github.com/stoplightio/studio/issues/197
- https://github.com/stoplightio/studio/issues/127

**User story.**
As an API developer, I may want to just throw my API descriptions inside the root of the repository (or under some other directory that is not `/reference`).

**Is your feature request related to a problem?**
The current directory structure is fairly restrictive, especially when being used with a pre-existing repository that must now be updated to conform to the structure.

**Describe the solution you'd like**
The directory structure should be customizable, with the ability to be disabled wholesale if wanted.

**Comment by erik-hansen** [comment]
Yes! We have many repos with more than one component/service where we have OAS files living beside the service that implements the API.  It would not make sense for us to recreate the service structure at some root level folder.  Instead, I should be able to give you a RegEx that matches the folder name that contains my API/model/doc files.  That RegEx should be able to discover more than one folder within the hierarchy of my repo.
Example RegEx: "`\/resources\/schema`" would pick up the following folders in my Repo to be displayed and manipulated within Stoplight Studio.

- `my-repo/service-a/src/main/resources/schema/` 
- `my-repo/service-b/src/main/resources/schema/`
- `my-repo/component-x/service-y/src/main/resources/schema/`
- `my-repo/component-x/service-z/src/main/resources/schema/`

**Comment by nhuray** [comment]
IMHO the studio should be viewed exactly as an IDE (Code, Webstorm...), so the API developer should have the ability to create a project (or workspace) and to add as much as API, documentation ... to the project. 

The project will be saved in a .stoplight file (for example) saving all preferences.

**Comment by ahx** [comment]
We usually have one API description per repo:
- `my_repo/openapi/openapi.yaml`
- `my_repo/openapi/components/schemas/mymodel.yaml`
- ...

> As an API developer, I may want to just throw my API descriptions inside the root of the repository

**Comment by P0lip** [comment]
From our design meeting today:

- the APIs tree becomes a tree showing all files relevant to APIs (i.e. OAS documents), represented as they appear in the filesystem,

- the APIs tree behaves like a regular file tree meaning you can drag and drop files, rename them, etc.,

- the rich tree view containing detailed information about currently selected file (see attached draft screenshot),

- the rich view behaves in the same manner as it does now, with that different it shows nodes relevant only to the chosen document. That means drag and drop, renaming, etc. will still be fully operational and no different,

- a similar filtering strategy will apply to other trees, such as the docs tree,

- last but not least, the top tabs will have slightly changed naming, `APIs filter`, `Docs filter` to indicate the docs and potential models trees similarly provide a filtered view.

Features we might want to consider:

- a list of glob patterns can be applied to ignore certain documents in the APIs tree,

- a new tree for JSON Schema files only.

Draft:
![sidebar view draft](https://user-images.githubusercontent.com/9273484/66870151-199cf280-efa1-11e9-8326-39cb5c9cbf9a.png)


TODO
- @wmhilton to sync with @lottamus on the docs approach.

**Comment by marbemac** [comment]
> last but not least, the top tabs will have slightly changed naming, APIs filter, Docs filter to indicate the docs and potential models trees similarly provide a filtered view.

Suggest we leave without the extra "filter" word, we're already space constrained up there :).

> a list of glob patterns can be applied to ignore certain documents in the APIs tree,

<3 for potential separate issue to tackle later.

> a new tree for JSON Schema files only.

<3 - "Schemas"? "Models"? We are running out of space though, might have to brainstorm options.

**Comment by erik-hansen** [comment]
From the screenshot, it looks like I still must have "reference" as the root folder - this would not work for us.  Please be sure you just display OAS/MD files within the directory structure as is.  I would be even happier to specify a RegEx that helps you identify only the directory structures you should scan - so it doesn't take so long to load a project, like now...

Thanks!  Looking forward to this being implemented!

**Comment by rossmcdonald** [comment]
@erik-hansen The last screenshot was taken from a project that was already in the previous format, but the requirement on a `reference` directory will be completely lifted as soon as this change lands in a release. For example, here is a project with the API specs stored at the root of the repo:

![image](https://user-images.githubusercontent.com/4060903/67246583-76c2f900-f424-11e9-88ba-3a6680d62703.png)

And regarding:

> I would be even happier to specify a RegEx that helps you identify only the directory structures you should scan - so it doesn't take so long to load a project, like now...

Yep, completely agree. I'll create a separate issue around this as soon as this issue is closed and we verify the problem is still present with the new sidebar format.

**Comment by StoplightDeb** [comment]
Talked through with @rossmcdonald, looks good for release, closing.
