### ISSUE TITLE
Add ability to store multiple schemas within a single JSON Schema file

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#60]
Add support for storing and referencing multiple files within the same model file. For example:

```
type: object
properties:
  legs:
    type: array
    items:
      $ref: '#/definitions/ABC123'
definitions:
  ABC123:
    type: object
    properties:
      CDE456:
        type: string
```

The file above written to a JSON schema file would allow for simultaneous editing of both the top-level and nested definitions.

---

Now that we have the split sidebar with v1.4.0, the way I envision this working is similar to modifying API models. Using the example above as `test.v1.yaml`, I would expect editing this model to look like:

![Screen Shot 2019-11-26 at 3 59 07 PM](https://user-images.githubusercontent.com/4060903/69676694-e4d38f00-1066-11ea-860e-0dd3c78f1927.png)

Which when clicking on the ABC123 model in the lower left pane, would look like:

![Screen Shot 2019-11-26 at 3 59 07 PM](https://user-images.githubusercontent.com/4060903/69677109-ca4de580-1067-11ea-8f50-4d8bad9ee301.png)

**Comment by rossmcdonald** [comment]
Also `definitions` objects should be listed at the bottom of the raw file for consistency sake.

**Comment by philsturgeon** [comment]
I'm also having this problem. For example http://hl7.org/fhir/2018Sep/fhir.schema.json

Ignore the discriminator OpenAPI-specific stuff, they're being a bit odd here and confusing OpenAPI and JSON Schema, but who doesn't. 

Look at the `definitions` keyword. This is valid JSON Schema and valid OpenAPI, and is common practice. There is one file with multiple definitions in it, but when I try to $ref to a "Model" I just see the entire file, and thats not going to work. 

<img width="894" alt="Screen Shot 2019-11-14 at 13 46 43" src="https://user-images.githubusercontent.com/67381/68862601-a55f8700-06e5-11ea-924a-07c207e5273f.png">

**Comment by philsturgeon** [comment]
Let's ditch this up because it's not come up all that often, and there are ways around it. We cannot perfectly support all variations of how people try to store schemas, and one schema per file is relatively standard in the wild (ignoring FHIR),
