### ISSUE TITLE
Validations not showing for models

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#62]
**User story.**

As an API designer working on a model, I'd like to see the validations for the model in the same place it is shown for an API (bottom right-hand corner of the screen).

**Is your feature request related to a problem?**

It's hard to know there are any errors when the validation display is not present.

**Describe the solution you'd like**

Show the validation UI when viewing models, even if it's for file syntax (ie, JSON errors).

We should probably just show the validations pane for all yaml and json files.

**Additional context**

Screenshot demonstrating the pain here:

![image](https://user-images.githubusercontent.com/4060903/63551932-0d923880-c4fc-11e9-9917-ea0d77312c3a.png)

The model is incorrectly formatted (note the red vertical bar in the write view), but no validations are shown.

**Comment by P0lip** [comment]
IIRC I might have fixed that in Spectral overhaul PR. Either way, the fix should be quite straightforward, so I will cope with it.
