### ISSUE TITLE
Blank screen when creating a project

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#63]
**Describe the bug**
Blank screen (dark mode its a black screen) when trying to create a project. Two people have reported this, both dark mode, both on desktop, one said it was when clicking "Open Existing" to create the project. 

**To Reproduce**

Not able to reproduce. 

**Screenshots**

![image](https://user-images.githubusercontent.com/67381/63583341-1dad2500-c59b-11e9-89bd-0b1f1f1c8437.png)

**Environment:**
 - Studio version: v1.0.1
 - OS: macOS

**Additional context**

https://twitter.com/leitom/status/1164423711023411200
https://twitter.com/rdohms/status/1164831650833821699

**Comment by rossmcdonald** [comment]
This happens sporadically for me. Unfortunately looking at dev tools is not helpful:

![image](https://user-images.githubusercontent.com/4060903/63606712-4e3e9000-c596-11e9-8472-70bf25b07e52.png)

Not sure if there's somewhere else I can look to see what's going on?

**Comment by marbemac** [comment]
Could we maybe DM those twitter users to see if they're able to reproduce? For example, does it happen every time they try to open xyz existing folder? If so, would they be able to share that folder with us? And the `cwd` of that folder on their computer?

**Comment by philsturgeon** [comment]
I’m meeting one of them for coffee this week so I’ll tell him to being his laptop.

**Comment by lottamus** [comment]
This issue has been fixed in v1.1.2: https://github.com/stoplightio/studio/releases/tag/v1.1.2. Please reopen if you run into this issue again.
