### ISSUE TITLE
Web Version - Login with GitHub - Wrong redirect

### ISSUE THREAD

**Issue by eduardostuart** [stoplightio/studio#64]
**Describe the bug**

Just created a new account using GitHub and got redirect to a blank page (web version).

**To Reproduce**

1. Github sign up
2. Authorize account
2. Redirect goes to `/p/p/studio`. Correct should be `/p/studio` (I guess..)

**Expected behavior**

1. Redirect to `/p/studio` (?)

**Screenshots**

-

**Environment (remove any that are not applicable):**

Web version

**Additional context**

-

**Comment by marbemac** [comment]
Should be fixed in https://github.com/stoplightio/app-gen3/pull/309.
