### ISSUE TITLE
Multiple line breaks in markdown cause strange issues

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#68]
**Describe the bug**

The markdown editor does really weird things when there are multiple line breaks between paragraphs. Trying to edit the paragraphs makes the issues worse.

**To Reproduce**

Using the API description:

```
openapi: 3.0.1
info:
  version: 2.4.0
  title: Test API
  description: >
    # API information

    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.




    Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
```

Within the Forms view, try removing the multiple line breaks between the two paragraphs in the API description and then click off the markdown editor, notice that more line breaks will be inserted between the paragraphs.

**Expected behavior**

That the markdown would be edited and modified correctly (and not auto-corrected in a bad way, which is what seems to take place).

**Environment (remove any that are not applicable):**
 - Studio version: v1.0.1

**Comment by P0lip** [comment]
Alright, done with investigation and it's [safeDump](https://github.com/mulesoft-labs/yaml-ast-parser/blob/717578fb4c2589264fe7992bf950852ea201004b/src/dumper.ts) that causes it.
The [fold](https://github.com/mulesoft-labs/yaml-ast-parser/blob/717578fb4c2589264fe7992bf950852ea201004b/src/dumper.ts#L395) function basically adds 2 new lines.
Luckily, when you parse the previously stringified content again, everything is back to its initial state.
I believe we could try using `>+` but I need to find a way how we can trick `safeDump` to use it.
