### ISSUE TITLE
Re-add model version tags to sidebar display

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#69]
**User story.**

As an API developer, I need to be able to see the different versions available of a given model. Otherwise it's just the same version name repeated.

![image](https://user-images.githubusercontent.com/4060903/63621529-c36f8c80-c5b9-11e9-8fd0-81510f280264.png)

**Is your feature request related to a problem?**

I need to see the model version from the sidebar.

**Describe the solution you'd like**

The version tags should be re-added to the sidebar.

**Comment by rossmcdonald** [comment]
It looks like this regressed with the directory layout changes in v1.4.0.

**Comment by P0lip** [comment]
@rossmcdonald 
I believe we removed it on purpose, given that `version` is inferred from the filename which is now always displayed. Moreover, we no longer display standalone models in the design tree.
cc @marbemac

**Comment by rossmcdonald** [comment]
@marbemac I guess it's your call here. I think the aesthetic of listing the version number to the side is appealing and helps differentiate the models better than the raw file names, but I'm fine with letting it go if that's the consensus.

**Comment by philsturgeon** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/67381/75804941-28821700-5d81-11ea-9eed-e70371aebc48.png">

It's back in the filename now.
