### ISSUE TITLE
Add ability to define and create new files from a template

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#72]
**User story.**
As an API developer and tech writer, I would like to rapidly create new files (particularly models and articles) from a base template that I define.

**Is your feature request related to a problem?**
There are currently no ways to quickly create many files apart from copy-and-pasting.

**Describe the solution you'd like**
Add ability to define a base template that can be accessed when creating new files.

**Comment by philsturgeon** [comment]
https://roadmap.stoplight.io/c/63-crud-builder
