### ISSUE TITLE
Unable to run on Debian or Manjaro

### ISSUE THREAD

**Issue by akrantz01** [stoplightio/studio#73]
**Describe the bug**
The AppImage file throws a sandbox error on Manjaro Linux. The error shown is below: 
```
18294:0826/173141.303217:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_StopliW7A3MT/chrome-sandbox is owned by root and has mode 4755
```
It would appear to be a packaging issue with electron ([#17927](https://github.com/electron/electron/issues/17972)), but I'm not entirely sure. Also, if I run it using `sudo`, no output is generated but it outputs a non-zero exit code.

**To Reproduce**

1. Download `Stoplight-Studio-1.0.1.AppImage` from the Releases tab
2. Mark as executable `chmod +x Stoplight-Studio-1.0.1.AppImage`
3. Run with `./Stoplight-Studio-1.0.1.AppImage`

**Expected behavior**
The app should run.

**Environment:**
 - Studio version: 1.0.1
 - OS: Manjaro 18.0.4

**Additional Information:**
Later today I will test on Ubuntu 18.04 Desktop to see if it is a Manjaro problem or if it spans to other distros.

**Comment by philsturgeon** [comment]
@cebe @akrantz01 did you two figure out the trouble with running this on Manjaro Linux? Are later versions (v1.10.0) still not working?

**Comment by cebe** [comment]
I did not bother to try again since.

Just downloaded the latest version from the website:

```php
$ ./stoplight-studio-linux-x86_64.AppImage 
[27881:0306/172755.016743:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_stoplipCN72R/chrome-sandbox is owned by root and has mode 4755.
Trace/Breakpoint ausgelöst
```

Still the same issue.

I'm not on Manjaro, but plain Debian stable:

```
$ cat /etc/debian_version 
9.12
```

**Comment by P0lip** [comment]
I used to be a Arch Linux user back in the day and faced a similar issue with Chromium.

I'm not 100% sure whether this will do the trick for you or not, since I no longer use Arch, so cannot verify it on my own, but here is something you might want to try out:
```shell
./stoplight-studio-linux-x86_64.AppImage --appimage-extract
sudo chown root:$USER ./squashfs-root/chrome-sandbox
sudo chmod 4755 ./squashfs-root/chrome-sandbox
./squashfs-root/stoplight-studio
```

Obviously replace `stoplight-studio-linux-x86_64.AppImage` with the whatever Studio version you wish to use.
LMK whether it does the trick. I know it's kind of a manual process, but may help you out.

**Comment by cebe** [comment]
looks like you can fix it by changing permission on the chrome-sandbox binary inside of the package:

https://github.com/electron/electron/issues/17972#issuecomment-487369441

**Comment by cebe** [comment]
the steps described by @P0lip work for me too, so if you fix this inside of the image, that should solve the problem.

**Comment by philsturgeon** [comment]
@P0lip we got a thumbs up on your solution, can we commit it?

**Comment by P0lip** [comment]
Is this still an issue, though?
I'm on Arch Linux and I don't experience that issue anymore.
Manjaro is built on top of Arch Linux, so I'd expect the issue to be gone there as well.
As mentioned in my previous comment, in the past it used to be an actual problem, but now it appears to be be resolved.

**Comment by warrn** [comment]
Still hitting this issue on stable debian (10)...

```
$ ./Applications/stoplight-studio-linux-x86_64_e836db7f5768a38d37061992344e581a.AppImage 
[7459:0119/095357.942429:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_stopliOocS6n/chrome-sandbox is owned by root and has mode 4755.

$ uname -a
Linux warren-t480s 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

```

**Comment by P0lip** [comment]
@warrn which version of Studio are you trying to execute?

I'll try one trick in the evening. Stay tuned, please.

**Comment by P0lip** [comment]
Alright. I think I know why it might be working for me.
What's the value of `sysctl kernel.unprivileged_userns_clone`? It's `1` in my case.
If it's `0` in yours, then this is likely to be the culprit.

**Comment by warrn** [comment]
Version is 2.2.0 btw :)
```
$ sudo sysctl kernel.unprivileged_userns_clone
kernel.unprivileged_userns_clone = 0

$ ./stoplight-studio-linux-x86_64.AppImage 
[27761:0120/121000.686697:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_stopli9TuQUk/chrome-sandbox is owned by root and has mode 4755.

$ sudo sysctl -w kernel.unprivileged_userns_clone=1
kernel.unprivileged_userns_clone = 1

$ ./stoplight-studio-linux-x86_64.AppImage 
It works :)
```

That's the fix in the interim - however it disables hardening that the debian developers have patched into the kernel so I will not be leaving it that way. I rather unpack stoplight studio and run it outside sandbox (with the proper chown and chmod).

Is it possible to fix as proposed earlier in this thread, leading to stoplight in the future being repackaged with the proper changes?

**Comment by P0lip** [comment]
> Is it possible to fix as proposed earlier in this thread, leading to stoplight in the future being repackaged with the proper changes?

I'm not sure whether that'd actually work. I'd need to verify it.
I'm not sure how file permissions & ownerships are preserved (and if at all) during the packaging.
AppImage uses squashfs fs under the hood.

> That's the fix in the interim - however it disables hardening that the debian developers have patched into the kernel so I will not be leaving it that way. I rather unpack stoplight studio and run it outside sandbox (with the proper chown and chmod).

If you wish to run studio without sandbox, you can simply pass `--no-sandbox` flag, like so `./studio-xyz.AppImage --no-sandbox`
