### ISSUE TITLE
Receiving error "Author Name cannot be empty" when pushing to repository

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#74]
**Describe the bug**
Seeing an intermittent error when trying to push to a remote project where the message "Author Name cannot be empty" is produced. Unfortunately it's not clear why this error is caused or how to reproduce it.

**To Reproduce**

1. Try to push to remote

**Expected behavior**
To push to the remote.

**Workaround**
Refresh the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/4060903/63780123-3f651f80-c8ad-11e9-8c57-f3ef25814546.png)

**Environment (remove any that are not applicable):**
 - Studio version: web, latest production as of 2019.08.27

**Comment by casserni** [comment]
Some updates one this,  it happens consistently in incognito windows. So that should help give us a hint on when it might happen

**Comment by rossmcdonald** [comment]
It seems this error is triggered by a certain order of events in the UI, and should be resolved by refreshing the window.

**Comment by marbemac** [comment]
I know how to reproduce, can fix this weekend.

1. load studio while logged out (so that studio store is initialized with empty user token)
2. login
3. open new project
4. try to commit, authorized user not set yet so no author

**Comment by nigelfo** [comment]
Can't open existing projects, saved my work on Friday, can't open on Monday morning. I'm guessing it has auto-updated ?!

I now get the message in console "CANNOT FIND AUTHOR NAME! TRIED: undefined undefined undefined undefined undefined undefined"

The project doesn't load the local file. 

If I create a new API in the folder that is fine. If I close and re-open Stoplight it opens the new API file but also produces the above error, presumably when it tries to open the original file.

Tried copying contents of original file into the new API file I created, that fails too, so something in the content of the file (JSON format).

Using on Windows 10. Local files only, not using git.

**Comment by mlk621** [comment]
I'm receiving this same error.

I'm using the desktop version of Stoplight Studio. I am not logged in, not sure if that matters as it is hard to tell what the resolution was in the discussion.

![image](https://user-images.githubusercontent.com/42215983/88823062-4619a800-d18a-11ea-9f08-253ff9b3e173.png)

![image](https://user-images.githubusercontent.com/42215983/88823380-a14b9a80-d18a-11ea-9534-dcb81d6748b1.png)
