### ISSUE TITLE
Unable to delete project

### ISSUE THREAD

**Issue by paulyk1983** [stoplightio/studio#75]
**Describe the bug**
Unable to delete project: When I go to project setttings and delete project and hit confirm, it brings back to 'studio' page but the project is still there and accessible.

**To Reproduce**

1. o to project setttings and delete project and hit confirm
2. See project still remaining in view
3. click on project.

**Expected behavior**
I expect the project to be removed and not accessible, and I can create a new project with the same name.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: ? web version
 - OS: Windows 10
 - Browser: [e.g. Firefox]

**Additional context**

**Comment by marbemac** [comment]
Hi @paulyk1983, this is fixed in Studio v1.1.4 - thanks for the report!
