### ISSUE TITLE
Changing field name of model fails in web version (Error: Minified React error #185)

### ISSUE THREAD

**Issue by jeanpaulsmit** [stoplightio/studio#76]
**Describe the bug**
The issue is experienced when a model in a request or response body of an operation is changed. Not when a model is defined separately, but when it's done as part of the operation definition.
Web edition only, it works on the Windows app.

Stack trace:

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Rs (commons.c3f499c5bd0296568376.js:1)
    at Object.enqueueSetState (commons.c3f499c5bd0296568376.js:1)
    at t._.setState (commons.c3f499c5bd0296568376.js:1)
    at t.updateInputDimensions (commons.c3f499c5bd0296568376.js:1)
    at t.componentDidUpdate (commons.c3f499c5bd0296568376.js:1)
    at commons.c3f499c5bd0296568376.js:1
    at t.unstable_runWithPriority (commons.c3f499c5bd0296568376.js:1)
    at ui (commons.c3f499c5bd0296568376.js:1)
    at js (commons.c3f499c5bd0296568376.js:1)
    at Ms (commons.c3f499c5bd0296568376.js:1)
```

**To Reproduce**
1. Open Web studio version
2. Create new project
3. Create new API
4. Create new path, for example /demo
5. Click the created path and the GET tab shows up
6. Click '+ Add Body', the 'Schema' tab becomes visible
7. Click on the '+' sign in front of 'object {0}', a field:string shows up
8. Click on 'field' and start typing to update the name
9. "Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Expected behavior**
On the Windows App version this works fine, so I would expect the same behavior on the Web version

**Screenshots**
![image](https://user-images.githubusercontent.com/10231104/63809417-922cee80-c922-11e9-8fb0-4f156f4c78c2.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.0.1
 - OS: Windows 10
 - Browser: Chrome and  Brave Version 0.68.131 Chromium: 76.0.3809.100

**Comment by rossmcdonald** [comment]
I'm seeing this issue reliably with the v1.1.0 candidate (web version).

**Comment by rossmcdonald** [comment]
This issue is fixed with v1.1.1. @jeanpaulsmit Let us know if you see this error again after updating.

**Comment by jeanpaulsmit** [comment]
I cannot reproduce it anymore, so this one is fixed. Thanks.

**Comment by rossmcdonald** [comment]
Thanks @jeanpaulsmit, let us know if you encounter any other issues.
