### ISSUE TITLE
Unable to scroll in 'write' window

### ISSUE THREAD

**Issue by paulyk1983** [stoplightio/studio#77]
**Describe the bug**
Unlike in the read and directory columns I cannot use my mouse or touchpad to scroll up and down in the 'write' column. I can drag the scroll bar on the screen to scroll, but not with my mouse.

**To Reproduce**

1. Given this OpenAPI document 'https://stoplight.io/p/studio/sl/_/2lmrkqfn'
2. Try scrolling using mouse over the 'write' column/window
3. does not scroll.

**Expected behavior**
Should be able to scroll with mouse

**Screenshots**

**Environment (remove any that are not applicable):**
 - Studio version: studio web version
 - OS: windows 10
 - Browser: Firefox

**Additional context**

**Comment by P0lip** [comment]
Hey @paulyk1983.
Thank you very much for your report.
We are aware of the issue and track it in the following ticket https://github.com/stoplightio/studio/issues/36.
I'll close your ticket for now, feel free to watch the above issue.
