### ISSUE TITLE
link testing button to product board

### ISSUE THREAD

**Issue by marbemac** [stoplightio/studio#8]
**User story.**

As a studio user, I can understand that testing is in the roadmap, and have some way of indicating it is important to me.

related to #10 

**Is your feature request related to a problem?**

Next users will wonder where our testing stuff is. Since we do plan on adding some form of testing back, we should let them know and give them a way to indicate how important this is to them.

**Describe the solution you'd like**

Add a testing tab (pictured below). When clicked, instead of actually switching tabs, it opens a modal with some helpful text explaining this is a feature under consideration, and user can visit our product board to indicate interest and influence when / how we create this. Modal should have two buttons, close and visit product board. 

Clicking visit product should open up our product board in a new window (target blank), specifically opening the relevant idea card.

<img width="330" alt="Screen Shot 2019-07-28 at 11 45 45 PM" src="https://user-images.githubusercontent.com/847542/62022413-e2812700-b191-11e9-848f-48a56f37df57.png">

**Comment by chris-miaskowski** [comment]
I don't think it's a good idea to link from an actual product to "ideas" board. This reminds me of the annoying "page under construction" pattern from the 90'. We can have a public board of ideas and link from products to those page but the proposed behavior seems odd to me.

When I click "Testing" the last thing I expect is being redirected to a product ideas page. I would be hugely disappointed as a user. Let's not over-promise if we can't deliver something right now.
