### ISSUE TITLE
Examples always display error, not displaying in Read view

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#80]
**Describe the bug**
Examples are always marked with "Invalid JSON: Unexpected token o at position 1"

**To Reproduce**

1. Input JSON into an example field
2. See error

**Expected behavior**
Valid JSON examples should be displayed in the read view without error.

**Screenshots**

![Screen Shot 2019-08-30 at 3 42 30 PM](https://user-images.githubusercontent.com/4060903/64050356-5621a580-cb3d-11e9-917f-5185ce39105e.png)

![Screen Shot 2019-08-30 at 3 44 20 PM](https://user-images.githubusercontent.com/4060903/64050363-5b7ef000-cb3d-11e9-8fb2-ba39c8d0589c.png)

**Comment by anidotnet** [comment]
Thanks for addressing this issue. So when can we expect the fix in studio desktop app?

**Comment by P0lip** [comment]
@anidotnet The fix will be available in the next studio desktop app version, which is supposed to be released in upcoming days, therefore it's expected to land soon.

**Comment by NEJEtherington** [comment]
Should this issue now be resolved in the web app as the issue has been closed?  My examples are still not displaying.  Thanks.

**Comment by rossmcdonald** [comment]
@NEJEtherington It's not yet been deployed to production, but should be soon. I'll update here once it's live.

**Comment by rossmcdonald** [comment]
@NEJEtherington Apologies on the delay here. The fix for this issue was deployed last week. Let us know if you run into any other issues!
