### ISSUE TITLE
Guide users to "Import existing APIs"

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#82]
**User story.**
As a user new to Studio, opening an existing repo for the first time, I want to edit my existing APIs which are in folders Studio does not know about.

**Is your feature request related to a problem?**

I am confused when trying to use Studio to edit existing OpenAPI files. Folks are asking me how it's done and I myself keep forgetting. :D 

**Describe the solution you'd like**

We have a "Import existing API" option but its only used when you click on the + icon, then click API:

<img width="542" alt="Снимок экрана 2019-09-02 в 18 07 39" src="https://user-images.githubusercontent.com/67381/64129282-837b8700-cdbb-11e9-829d-3db18ea3215b.png">

When you click on the most obvious API button, it always adds a new one, the dialog with import is missing. 

![image (1)](https://user-images.githubusercontent.com/67381/64129281-837b8700-cdbb-11e9-854a-b431b1b51e14.png)

Let's make this button open that great dialog with the import option.

**Comment by rossmcdonald** [comment]
I'm wondering why we don't just have a 'move my stuff' button that automatically moves everything where it wants. 

This is somewhat related to #57, which so far has generated a lot of complaints. This would ease a lot of that pain if there was a less painful way for getting existing projects into the correct format.

**Comment by philsturgeon** [comment]
Yeah I think there’s a lot which needs to be done here. I think this small tweak would initially make things less confusing, but then a better “hey we notice you have APIs around but they’re not in the right place, do you wanna move them or change the cod if?” Type UI/wizard would be fantastic. 

I think we should do this, and #57, then add that simple UI as a feature after, especially if folks are still struggling.

**Comment by dgrstl** [comment]
At this point, it would be easier to enumerate prospects who will accept this than the other way around. This was a major reason Adobe could not adopt us. I'd say this comes up 1-3 times per week as a major problem. The crux is that these repos already exist and their current structure is purposeful.

**Comment by P0lip** [comment]
I think this can be closed once https://github.com/stoplightio/studio-internal/pull/1034 is merged

**Comment by philsturgeon** [comment]
@P0lip im not sure it can. Clicking API in an empty project does not offer you the import file option which "+ > API" does. This issue was about making both those buttons do the same thing. 

Also, when I import one via "+ > API" and another via right click "Import OAS file", the two files go to different places and im not sure why?

<img width="352" alt="Screen Shot 2019-11-14 at 13 21 16" src="https://user-images.githubusercontent.com/67381/68860716-fc635d00-06e1-11ea-8b67-ec8d020612e4.png">

I know I sound like a grumpy technophobe who doesn't know how to use the remote, but if I'm getting confused about all this then it seems rather likely we have a problem, and our users will also have a problem.

**Comment by P0lip** [comment]
@philsturgeon The changes have not been released yet.
This is how the screens will ultimately look like
![image](https://user-images.githubusercontent.com/9273484/68945882-c392b900-07b1-11ea-9acf-f56ec11d1ce2.png)
![image](https://user-images.githubusercontent.com/9273484/68945891-cab9c700-07b1-11ea-8d98-0302799a71a8.png)
![image](https://user-images.githubusercontent.com/9273484/68945901-d2796b80-07b1-11ea-9f2e-38cb95002911.png)
![image](https://user-images.githubusercontent.com/9273484/68945915-db6a3d00-07b1-11ea-9f9e-60d4f0d838c0.png)
![image](https://user-images.githubusercontent.com/9273484/68945931-e1f8b480-07b1-11ea-8c85-a62d81b13447.png)
![image](https://user-images.githubusercontent.com/9273484/68945943-e9b85900-07b1-11ea-883c-8c4e65ea7b04.png)
Captured while checked out at develop branch

**Comment by philsturgeon** [comment]
Awesome! I'll close this out and if I have any feedback we can make a new issue. This looks great.
