### ISSUE TITLE
Add LICENSE 

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#84]
**Chore summary**

Pick a license and place the plain text version in the root as LICENSE.

**Tasks**
- [ ] LICENSE
- [ ] Update package.json

**Comment by philsturgeon** [comment]
@marbemac getting multiple requests about this. Certain companies require a license for all software before they can approve its use, and our lack of license is scaring them away.

**Comment by iamalnewkirk** [comment]
@philsturgeon @marbemac Any updates on this? Since I’m told that Studio is open source, and since Spectral and Prism both use Apache2 licenses, could someone simply provisionally add the license until a deeper discussion is had?

**Comment by philsturgeon** [comment]
@iamalnewkirk Studio is not open-source, nothing should have said that anywhere. Waiting on a decision for the license from @marbemac as he's the owner of this product.

**Comment by iamalnewkirk** [comment]
@philsturgeon @marbemac Any updates on this? Previously I conflated "free" with "open source", my mistake.

**Comment by transitive-bullshit** [comment]
Just want to ping this issue -- this library really looks OSS at first and it was disappointing to learn that it's not.

We're still very interested in using Stoplight Studio, however, it's just not a great first experience to feel like we've been bait & switched. In particular, we're interested in a deeper integration and/or white labeled or self-hosted solution for [Saasify](https://saasify.sh).

**Comment by philsturgeon** [comment]
@transitive-bullshit hey Travis. Nothing about GitHub suggests that all software is OSS by default even when the repo is public, so I don’t feel like there’s any cause for comments about bait and switch. 

So far this conversation has been about picking an appropriate license for the downloadable binaries here, so that folks can tel their corporate higher ups that it is indeed ok for them to use it for commercial purposes. It is! 😎

That doesn’t make it open source though. Our source is closed for Stoplight Studio, but it’s free and you’re all welcome to use it. We’ll get that typed up soon but it’s going to be a lot of words echoing this exact sentiment.

**Comment by transitive-bullshit** [comment]
Thanks for the quick response, Phil && I totally understand that it's not mandated by GH or anything. It just feels OSS-y 😄 I was expecting it to be an [open core project](https://coss.media/open-core-definition-examples-tradeoffs/) or something, which I guess it kind of is considering some of your team's other related OSS work like `http-spec`, `prism`, etc.

I'm working on some [docs](https://github.com/saasify-sh/saasify/blob/feature/updated-docs/docs/openapi.md#visual-designer) that will actively push Saasify users to use Stoplight Studio btw and would love to chat about the potential for a tighter integration (which is what led me down this path in the first path hah). I'm in NY as well.

Thanks for all the great API goodness & lemme know if you or someone from Stoplight would be free to chat.

**Comment by philsturgeon** [comment]
@transitive-bullshit this sounds interesting. Lmk more at phil@stoplight.io. 

I'm going to lock this issue for now just because there's nothing more anyone can add. If anyone wants to know if they can use studio at work, then yes, yes you can. Click that thumb icon to show support, but no need for more comments here. 🙌
