### ISSUE TITLE
Unable to publish personal Github projects from Studio

### ISSUE THREAD

**Issue by hirenoble** [stoplightio/studio#85]
**Describe the bug**
While trying to publish the docs getting an error.

**To Reproduce**

1. Click on publish

**Expected behavior**
Published documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/3747836/64202791-35b05e80-ce4f-11e9-97d4-054035cfab2a.png)

**Environment (remove any that are not applicable):**
 - Browser: Chrome

**Comment by rossmcdonald** [comment]
@hirenoble Was this a personal project, or was it under an organization?

**Comment by marbemac** [comment]
Quick follow-up for whoever picks this up - confirmed at least in my preliminary testing that this seems to be an issue with personal github projects - organizational projects seem to be OK.

**Comment by casserni** [comment]
Was able to fix the issue and we should hopefully have a patch out shortly!

**Comment by rossmcdonald** [comment]
This was fixed with v1.1.1. @hirenoble Let us know if you run into any further issues publishing personal projects.

**Comment by hirenoble** [comment]
Thank you @rossmcdonald @marbemac @casserni !!
