### ISSUE TITLE
Discarding changes when moving between branches doesn't actually discard the changes

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#86]
**Describe the bug**
Changes are not discarded when moving between branches.

**To Reproduce**

1. Clone repo
2. Create feature branch
3. Make any change, e.g., add a model
4. Change to another branch without committing (e.g., decide branch/change is not needed)
5. Accept warning that uncommitted changes will be discarded by clicking Discard button
6. Branch changes but changes from step 3 above appear in new branch

**Expected behavior**
Changes would be discarded.

**Workaround**
Using the commit button at the top of the screen to discard the changes actually discards them.

**Comment by rossmcdonald** [comment]
@wmhilton Do you know if this has been fixed? We can't reproduce anymore, so I wanted to double check.

**Comment by wmhilton** [comment]
Yes, should be fixed now.
