### ISSUE TITLE
When recording screen with macOS screen cap tool, "s" key stops working

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#87]
**Describe the bug**
A bit of a bizarre issue, but whenever I try to record my screen using the built-in macOS screen cap utility, my "s" key stops working in Studio. This happens in Stoplight Next as well, but it's continuing to happen in Studio for some reason.

**To Reproduce**

1. Open Studio, start screen cap
2. Try to hit "s" key

**Environment:**
 - OS: macOS Mojave

**Comment by tkawachi** [comment]
"s" key often stop working on my machine (macOS High Sierra 10.13.6). I'm not recording my screen. It worked again when I switch to another window by cmd-tab and back to stoplight studio.
