### ISSUE TITLE
Schema Editor: $refs list contains an empty item

### ISSUE THREAD

**Issue by P0lip** [stoplightio/studio#93]
**Describe the bug**
$refs list contains an empty item

**To Reproduce**

1. Given any schema model
2. Open form view
3. Change the type of any property to `$ref`
4. Select `this project` dropdown
5. Click on the other dropdown

**Expected behavior**
There is a proper label displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9273484/64414131-202b7680-d093-11e9-9728-b74b4a72f83a.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.1 alpha

**Comment by StoplightDeb** [comment]
👍 No blank lines! Closing this one.
