### ISSUE TITLE
stoplight-flavored markdown tabs don't render in Studio

### ISSUE THREAD

**Issue by polarweasel** [stoplightio/studio#96]
**Describe the bug**

The default `stoplight-flavored-markdown.md` file that populates in a new project is, I assume, a showcase of how to write docs in Stoplight-flavored Markdown.

There's either a _Markdown problem_ in the source, or a _rendering problem_ in the Studio app, because the `## Tabs` section starting on line 109 does not render as tabs in the preview UI.

**To Reproduce**

1. Make a new project.
2. Navigate to docs > markdown > stoplight-flavored-markdown.md
3. Click the Read button and scroll down to the Tabs section.

**Expected behavior**
Should render some tabs.

**Screenshots**
<img width="556" alt="Screen Shot 2019-09-09 at 6 15 58 PM" src="https://user-images.githubusercontent.com/538384/64576546-ed50df00-d32d-11e9-8b31-7c50afc35038.png">

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.1.0 (1.1.0.5783)
 - OS: macOS 10.14.6
 - Browser: n/a (native app)

**Comment by lottamus** [comment]
@polarweasel thanks for reporting! We've added more integration tests to account for Stoplight-Flavored Markdown so this won't slip through the cracks again. The fix will be in the next patch release of Studio Desktop.
