### ISSUE TITLE
Unable to view the docs after publishing

### ISSUE THREAD

**Issue by hirenoble** [stoplightio/studio#97]
**Describe the bug**
Once I publish the docs, my expectation is that I can share the url and it should be accessible in world wide web.

**To Reproduce**
Publish the docs in studio and open the url in incognito mode.

**Expected behavior**
Docs should be accessible in the incognito mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/3747836/64584178-00c17180-d351-11e9-963e-eb527f65778a.png)
![image](https://user-images.githubusercontent.com/3747836/64584197-0f0f8d80-d351-11e9-9e12-930924d8d979.png)

**Comment by lottamus** [comment]
Hey @hirenoble ,

Right now we are using the visibility level from your GitHub repo and applying those to your docs. So for example if you publish docs from a private repository, only members who are a part of your GitHub org will be able to see them.

We are planning to allow you to change that visibility level in Stoplight, so you will be able to set a private repo's docs as "public". This feature is on our roadmap and you can vote on it to give it a higher priority here: https://stoplight.io/p/roadmap

**Comment by richartkeil** [comment]
Just wondering, I changed my repo to "public" in order to get public documentation, however the change does not seem to be picked up by Stoplight. Is there any action one has to take besides changing the repo visibility in Github?

Right now I'm still getting the "Docs not found" message.

**Comment by richartkeil** [comment]
This seems to be fixed just with the new Platform v1.4 update and the dropdown for visibility in the project settings, that's awesome! 

I think this issue can be closed then.

**Comment by lottamus** [comment]
@richartkeil agreed, closing this issue now! 🎉 

@hirenoble let me know if you are still unable to make your docs public

You can access the visibility dropdown via your project settings page

For example: https://stoplight.io/p/settings/general/gh/{your-org}/{your-project}

![image](https://user-images.githubusercontent.com/7423098/67978035-3105ed80-fbe7-11e9-86a7-f05861f9926e.png)

**Comment by thomasruiz** [comment]
@lottamus I'm having the same problem. Project is public, but when I try to publish docs, the preview is empty. If I try accessing them, I get the same error. I'm on the web studio, here's the version shown: Platform v1.5.0 | Stoplight Studio v1.5.4-beta.0 (0588365)

**Comment by rossmcdonald** [comment]
@thomasruiz Can you verify that your visibility is set to public? We have docs on this [here](https://support.stoplight.io/hc/en-us/articles/360035849711-How-to-control-project-documentation-visibility). Right now there's a bug where you might have to toggle the setting to private and back to public to verify.

**Comment by thomasruiz** [comment]
I figured out why: the files must be in the `reference` directory, or it won't work. I had my openapi file at the root, moved them to `reference` and now I have docs. \o/

**Comment by azhar-gruff** [comment]
I have the free download studio app.   My github repository was private so the published documents were not visible.  
But I changed it to public and republished my docs.  My docs still cannot be viewed.

What can I do?
